Repository nanocurrency/nano-node, pull requests merged in 2018-10, with the labels that each got.

#1247 Change default desktop config.json
  rai/rai_wallet/entry.cpp
Labels: enhancement

#1249 Updated script to generate source tarball and changelog
  etc/gpg/argakiig.asc
  util/changelog_generator
  util/makesrc
Labels: enhancement

#1248 Better build prep scripts
  .gitlab-ci.yml
  ci/bootstrap_boost.sh
  ci/ubuntu_prep.sh
  docker/node/Dockerfile
  util/build_prep/bootstrap_boost.sh
  util/build_prep/common.sh
  util/build_prep/macosx/prep.sh
  util/build_prep/ubuntu/prep.sh
  util/build_prep/update-common
Labels: enhancement

#1253 Revert " Escalation for long unconfirmed elections"
  rai/node/node.cpp
Labels: bug

#1254 Fix deadlock for elections escalation
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1255 Check epoch_link before checking balance of state blocks
  rai/secure/ledger.cpp
Labels: enhancement

#1186 Blockstore move visitors
  rai/node/lmdb.hpp
  rai/secure/blockstore.cpp
  rai/secure/blockstore.hpp
  rai/secure/common.cpp
  rai/secure/ledger.cpp
Labels: quality improvements

#1256 Add a max time to batch processes
  rai/node/node.cpp
  rai/node/node.hpp
Labels: functionality quality improvements

#1170 Remove generate_hash_votes_at from config
  rai/core_test/gap_cache.cpp
  rai/core_test/network.cpp
  rai/core_test/node.cpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/wallet.cpp
  rai/qt/qt.cpp
  rai/slow_test/node.cpp
Labels: functionality quality improvements, universe

#1258 Name threads by role
  rai/lib/CMakeLists.txt
  rai/lib/plat/darwin/thread_role.cpp
  rai/lib/plat/freebsd/thread_role.cpp
  rai/lib/plat/linux/thread_role.cpp
  rai/lib/plat/windows/thread_role.cpp
  rai/lib/utility.cpp
  rai/lib/utility.hpp
  rai/lib/work.cpp
  rai/node/bootstrap.cpp
  rai/node/node.cpp
  rai/node/wallet.cpp
Labels: enhancement

#1261 Add vote status stats even when vote logging is off
  rai/node/node.cpp
Labels: functionality quality improvements

#1246 Remove processing blocks from confirm_req
  rai/core_test/node.cpp
  rai/node/node.cpp
Labels: enhancement

#1259 Extended bulk.offline_send
  rai/core_test/network.cpp
Labels: bug

#1265 Remove process_active from confirm_req
  rai/node/node.cpp
Labels: enhancement

#1262 Factor out logging
  rai/node/CMakeLists.txt
  rai/node/logging.cpp
  rai/node/logging.hpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: functionality quality improvements

#1269 Fix node.password_fanout test with running beta node
  rai/core_test/node.cpp
Labels: bug

#1278 Log common exceptions before asserting
  rai/node/logging.hpp
  rai/node/node.cpp
Labels: enhancement

#1276 Separate config option for network threads
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1277 Save DB random block read with include_active
  rai/node/rpc.cpp
Labels: functionality quality improvements

#1263 Move port/address parsing to common, where it's declared
  rai/node/common.cpp
  rai/node/node.cpp
Labels: functionality quality improvements

#1279 Force macOS wallet to use aqua light mode whilst QT adds support for …
  Info.plist
Labels: enhancement

#1286 Build prep enhancements
  .gitignore
  .gitlab-ci.yml
  docker/node/Dockerfile
  util/build_prep/bootstrap_boost.sh
  util/build_prep/common.sh
  util/build_prep/macosx/prep.sh
  util/build_prep/macosx/prep.sh.in
  util/build_prep/ubuntu/prep.sh
  util/build_prep/ubuntu/prep.sh.in
  util/build_prep/update-common
Labels: enhancement

#1287 Better changelog generation
  util/changelog_generator
Labels: enhancement

#1282 Fix escalation source block check
  rai/node/node.cpp
  rai/secure/ledger.cpp
Labels: bug

#1288 Improve pending & unchecked search performance
  rai/node/lmdb.cpp
  rai/node/rpc.cpp
  rai/node/wallet.cpp
Labels: quality improvements

#1289 std::thread to boost::thread
  rai/core_test/network.cpp
  rai/core_test/processor_service.cpp
  rai/core_test/rpc.cpp
  rai/core_test/wallet.cpp
  rai/lib/interface.cpp
  rai/lib/utility.cpp
  rai/lib/utility.hpp
  rai/lib/work.cpp
  rai/lib/work.hpp
  rai/node/bootstrap.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/wallet.hpp
  rai/slow_test/node.cpp
Labels: enhancement

#1225 Better error messages
  rai/node/common.cpp
  rai/node/common.hpp
  rai/node/node.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: enhancement

#1290 Revert stack size linking for windows
  CMakeLists.txt
Labels: enhancement

#1291 Add mutex around peers.get<T>()
  rai/node/node.cpp
Labels: bug

#1296 Factor out node_config
  rai/node/CMakeLists.txt
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
Labels: functionality quality improvements

#1293 No longer decrement the count if the entry is empty during account_history RPC call.
  rai/node/rpc.cpp
Labels: bug

#1194 Enhance version rpc
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
Labels: enhancement

#956 Batch state blocks signatures verification
  rai/core_test/node.cpp
  rai/lib/blocks.cpp
  rai/lib/blocks.hpp
  rai/lib/numbers.cpp
  rai/lib/numbers.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/rai_node/entry.cpp
  rai/secure/ledger.cpp
  rai/secure/ledger.hpp
Labels: enhancement, major

#1307 Exclude confirmed & aborted elections from RPC confirmation_active
  rai/node/rpc.cpp
Labels: enhancement

#1301 New unit labels from legacy XRB to NANO style
  rai/qt/qt.cpp
  rai/qt/qt.hpp
Labels: enhancement

#1314 Immediate election starts
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1306 Using decode_account instead of decode_hex in account_move RPC handler
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
Labels: bug

#1299 Using QSettings to persist application settings for selected ratio scale
  rai/qt/qt.cpp
  rai/qt/qt.hpp
  rai/qt_system/entry.cpp
Labels: enhancement

#1326 Create a separate tail constructor for distributed work
  rai/node/node.cpp
Labels: enhancement

#1300 Add weight option and account filter to representative_online rpc cal…
  rai/core_test/rpc.cpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
Labels: enhancement

#1152 Stop test nodes with deadline expired
  rai/core_test/network.cpp
  rai/core_test/node.cpp
  rai/core_test/rpc.cpp
  rai/node/testing.cpp
  rai/slow_test/node.cpp
Labels: quality improvements

#948 Node ID RPC
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
  rai/node/rpc.hpp
Labels: enhancement

#1329 Add unreachable host stats
  rai/node/node.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: enhancement

#1327 Update README.md
  README.md
Labels: documentation

#1193 Add "latest-rc" tag for Docker
  ci/deploy-docker.sh
Labels: enhancement, help wanted, incomplete

#1334 Increase minimum protocol version to when epoch blocks were introduced (V15.2)
  rai/core_test/peer_container.cpp
  rai/node/peers.cpp
  rai/node/peers.hpp
  rai/secure/common.hpp
Labels: incomplete, quality improvements

#1342 Remove unused local shared_ptr
  rai/node/lmdb.cpp
Labels: quality improvements
