Repository nanocurrency/nano-node, pull requests merged in 2018-09, with the labels that each got.

#1142 Improve rai::election::publish
  rai/core_test/node.cpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: bug

#1148 Pass transaction to vote observer to avoid tx nesting
  rai/node/node.cpp
  rai/node/node.hpp
Labels: functionality quality improvements

#1151 Fix test rpc.payment_begin_end
  rai/core_test/rpc.cpp
Labels: bug

#1165 Compare value in merge itr only when key is equal
  rai/core_test/block_store.cpp
  rai/node/lmdb.cpp
Labels: bug

#904 RPC confirmation_active, confirmation_info
  rai/lib/errors.cpp
  rai/lib/errors.hpp
  rai/node/node.hpp
  rai/node/rpc.cpp
  rai/node/rpc.hpp
Labels: enhancement

#1163 Add --clear_send_ids CLI option
  rai/node/cli.cpp
  rai/node/wallet.cpp
  rai/node/wallet.hpp
Labels: enhancement

#1169 Exclude active blocks from the pending RPC
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
Labels: enhancement, rpc semantics change

#1171 Script to make source tarball to replace Github's broken one
  util/makesrc
Labels: functionality quality improvements

#1172 data_path file permissions hardening
  rai/core_test/block_store.cpp
  rai/lib/CMakeLists.txt
  rai/lib/plat/posix/perms.cpp
  rai/lib/plat/windows/perms.cpp
  rai/lib/utility.hpp
  rai/node/lmdb.cpp
  rai/node/node.cpp
  rai/rai_node/daemon.cpp
  rai/rai_node/entry.cpp
  rai/rai_wallet/entry.cpp
Labels: functionality quality improvements

#1160 Validate pending blocks
  rai/rai_node/entry.cpp
Labels: enhancement

#1128 Check for invalid private keys in wallet_decrypt_unsafe
  rai/node/cli.cpp
Labels: functionality quality improvements

#1179 Initial bootstrap weight for betanet
  ci/record_rep_weights.py
  rai/secure/CMakeLists.txt
  rep_weights_beta.bin
  rep_weights_live.bin
Labels: enhancement

#1182 Enable bootstrap weights on betanet
  rai/node/node.cpp
Labels: bug

#1191 fixed config.json file permissions
  rai/rai_node/daemon.cpp
  rai/rai_wallet/entry.cpp
Labels: bug

#1184 Minimum bootstrap node version
  rai/node/node.cpp
  rai/secure/common.hpp
Labels: enhancement

#1201 Added support for PENDING_HASH_AMOUNT_AND_ADDRESS to bulk_pull_account
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/common.hpp
Labels: enhancement

#1203 Swallow exceptions regarding changing filesystem permissions
  rai/node/lmdb.cpp
  rai/node/node.cpp
  rai/rai_node/daemon.cpp
  rai/rai_wallet/entry.cpp
Labels: enhancement

#1210 Service UDP receive socket more frequently
  rai/core_test/network.cpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: enhancement, major

#1213 Resize stack to 8MB to match Linux
  CMakeLists.txt
Labels: bug

#1215 Abstracted setting file permissions into platform-specific code
  rai/core_test/block_store.cpp
  rai/lib/plat/posix/perms.cpp
  rai/lib/plat/windows/perms.cpp
  rai/lib/utility.hpp
  rai/node/lmdb.cpp
  rai/node/node.cpp
  rai/node/wallet.cpp
  rai/rai_node/daemon.cpp
  rai/rai_wallet/entry.cpp
Labels: bug

#1217 Expand the beta network acceptable range of protocols
  rai/node/common.cpp
  rai/node/node.cpp
  rai/secure/common.hpp
Labels: enhancement

#1211 Allow watch-only accounts json import
  rai/node/wallet.cpp
Labels: enhancement

#1222 Improve node.quick_confirm test
  rai/core_test/node.cpp
Labels: bug

#1218 Retry failed core test a few times for 90 days until we can find and …
  ci/test.sh
Labels: bug

#1219 Start elections for processed blocks after transaction commit
  rai/node/node.cpp
  rai/node/node.hpp
Labels: bug

#1224 Better `--snapshot` CLI error messages
  rai/node/cli.cpp
Labels: bug

#1226 Release assert on DB failures
  rai/node/lmdb.cpp
Labels: quality improvements

#1227 Add a test for bulk_pull_account
  rai/core_test/network.cpp
Labels: quality improvements

#964 Fix max vote sequence comparison
  rai/node/node.cpp
Labels: bug

#1038 Node breakup: port mapper
  rai/node/CMakeLists.txt
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/portmapping.cpp
  rai/node/portmapping.hpp
Labels: quality improvements

#1230 In broadcast_confirm_req case, limit to 32 peers
  rai/node/node.cpp
Labels: enhancement, question

#1232 Republish unconfirmed blocks with delay
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
Labels: enhancement

#1229 Basic confirm_req improvements
  rai/node/node.cpp
Labels: enhancement

#1239 Copy processed_active before dequeuing it
  rai/node/node.cpp
Labels: enhancement

#1233 Fix vote check
  rai/node/node.cpp
Labels: bug, release_blocker
