Repository nanocurrency/nano-node, pull requests merged in 2018-12, with the labels that each got.

#1419 Support RCs for changelogs
  util/changelog_generator
  util/makesrc
Labels: bug

#1420 Differentiate between lazy and non-lazy bootstrap in stats
  rai/node/bootstrap.cpp
  rai/node/node.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: quality improvements

#1426 Fix RPC shutdown in acceptor loop
  rai/node/rpc.cpp
  rai/node/rpc_secure.cpp
Labels: bug

#1432 Extend "bulk_pull" to have a count parameter
  rai/core_test/network.cpp
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/common.cpp
  rai/node/common.hpp
Labels: enhancement, protocol feature

#1433 Extend Confirmation History
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
Labels: enhancement

#1427 [v17] Lazy bootstrap improvements
  rai/core_test/network.cpp
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
  rai/node/rpc.cpp
  rai/rai_node/daemon.cpp
  rai/rai_node/daemon.hpp
  rai/rai_node/entry.cpp
Labels: enhancement, major

#1438 Confirm dependent active elections
  rai/core_test/node.cpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement, major

#1442 Update Confirmation Timers to be ms not sec
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
Labels: quality improvements

#1444 Reducing the number of alarms
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/node.cpp
Labels: enhancement

#1449 Fixed issue with incorrect timing computation
  rai/node/node.cpp
Labels: bug

#1448 Count state blocks in rai::block_processor::full ()
  rai/node/node.cpp
Labels: bug

#1452 Do not accept incoming bulk_push requests while bootstrapping
  rai/node/bootstrap.cpp
Labels: enhancement

#1440 Add max_broadcast_queue for rai::active_transactions
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1445 Close sockets gracefully
  rai/node/bootstrap.cpp
Labels: quality improvements

#1454 Add epoch timepoint for election end to confirmation history
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
Labels: enhancement

#1466 Consume future outside of client scope
  rai/node/bootstrap.cpp
Labels: bug

#1468 Add more support for building boost with different options
  util/build_prep/bootstrap_boost.sh
Labels: enhancement, incomplete

#1467 Fix initialization order
  rai/node/bootstrap.cpp
Labels: functionality quality improvements

#1473 Remove random items from the uniquer sets
  rai/lib/blocks.cpp
  rai/secure/common.cpp
Labels: bug

#1450 Verify more state blocks if blocks deque is empty
  rai/node/node.cpp
  rai/node/node.hpp
Labels: functionality quality improvements

#1480 update bootstrap weights
  rep_weights_beta.bin
  rep_weights_live.bin
Labels: routine, universe

#1483 Remove dupsort from unchecked table
  rai/core_test/block_store.cpp
  rai/node/lmdb.cpp
  rai/node/lmdb.hpp
  rai/node/node.cpp
  rai/node/rpc.cpp
  rai/secure/blockstore.hpp
  rai/secure/common.cpp
  rai/secure/common.hpp
Labels: enhancement

#1490 Slight improvements of block_exists usage in bootstrap & ledger
  rai/node/bootstrap.cpp
  rai/secure/ledger.cpp
Labels: functionality quality improvements

#1493 Remove beast from .gitmodules
  .gitmodules
Labels: quality improvements

#1495 Extend test retry
  ci/test.sh
Labels: bug

#1469 Move from deprecated io_service to io_context
  rai/core_test/ledger.cpp
  rai/core_test/network.cpp
  rai/core_test/node.cpp
  rai/core_test/processor_service.cpp
  rai/core_test/rpc.cpp
  rai/core_test/wallet.cpp
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
  rai/node/rpc.hpp
  rai/node/testing.cpp
  rai/node/testing.hpp
  rai/qt_system/entry.cpp
  rai/rai_node/daemon.cpp
  rai/rai_node/entry.cpp
  rai/rai_wallet/entry.cpp
  rai/slow_test/node.cpp
Labels: functionality quality improvements, universe

#1498 Replace bind with lambda
  rai/node/rpc_secure.cpp
Labels: functionality quality improvements

#1502 CLI --debug_profile_bootstrap
  rai/node/node.cpp
  rai/node/node.hpp
  rai/rai_node/entry.cpp
Labels: enhancement

#1451 Block builder
  rai/core_test/block.cpp
  rai/core_test/testutil.hpp
  rai/lib/CMakeLists.txt
  rai/lib/blockbuilders.cpp
  rai/lib/blockbuilders.hpp
  rai/lib/blocks.hpp
  rai/lib/errors.cpp
  rai/lib/errors.hpp
  rai/lib/numbers.cpp
  rai/lib/numbers.hpp
  rai/secure/common.hpp
Labels: low effort remaining, major, quality improvements

#1506 Update DockerHub username
  ci/deploy-docker.sh
Labels: universe

#1503 Improve requesting frontier performance
  rai/core_test/uint256_union.cpp
  rai/lib/numbers.cpp
Labels: functionality quality improvements

#1501 Fix crash when announcing votes
  rai/node/node.cpp
Labels: bug

#1494 Fix a possible thread stall
  rai/node/node.cpp
  rai/node/node.hpp
Labels: bug

#1482 Reduce UI lockups
  rai/qt/qt.cpp
  rai/qt/qt.hpp
Labels: enhancement, low effort remaining

#984 Option to disable automatic wallet backups
  rai/node/node.cpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
  rai/rai_node/entry.cpp
  rai/rai_wallet/entry.cpp
Labels: enhancement

#1510 Update UI block status
  rai/qt/qt.cpp
Labels: enhancement

#1500 Disable pool_connection () for stopped bootstrap or bootstrap_client
  nano/node/bootstrap.cpp
Labels: bug

#1512 Migrate existing data from ~/RaiBlocks to ~/Nano
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/secure/utility.cpp
  nano/secure/utility.hpp
Labels: enhancement, universe

#1513 UI feedback when changing seed
  nano/node/cli.cpp
Labels: enhancement, low effort remaining

#1167 Remove redundant config_file parameter of fetch_object
  nano/core_test/uint256_union.cpp
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
  nano/secure/utility.hpp
Labels: low effort remaining, quality improvements
