Repository nanocurrency/nano-node, pull requests merged in 2018-08, with the labels that each got.

#1040 Misc blockstore code improvements
  rai/secure/blockstore.cpp
Labels: quality improvements

#1002 Require less boost components
  CMakeLists.txt
  ci/bootstrap_boost.sh
Labels: quality improvements

#1037 Update ledger Information
  README.md
Labels: documentation

#1015 Fix duplicate send ID insufficient balance
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
Labels: bug

#1076 Improve rai::ledger::could_fit
  rai/secure/ledger.cpp
Labels: quality improvements

#1047 Remove some unused or duplicated header files
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/rpc.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
  rai/node/wallet.cpp
Labels: quality improvements

#953 Remove unused code
  rai/node/node.cpp
  rai/node/node.hpp
Labels: quality improvements

#1071 Add callback stats
  rai/node/node.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: enhancement

#1106 Fix duplicate send ID insufficient balance again
  rai/core_test/rpc.cpp
  rai/node/rpc.cpp
Labels: bug

#828 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#1114 Added start of "release_assert()"
  rai/lib/utility.cpp
  rai/lib/utility.hpp
Labels: quality improvements

#1115 Abort if decoding hex numbers fails
  rai/lib/numbers.cpp
Labels: quality improvements

#1116 Improve account_decode
  rai/lib/numbers.cpp
Labels: bug

#1104 Improve rai::ledger::could_fit v2
  rai/core_test/ledger.cpp
  rai/secure/ledger.cpp
  rai/secure/ledger.hpp
Labels: bug

#1003 Disable logging for broadcasting confirm req resumption
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1118 Add warning tag to constructors using release_assert
  rai/lib/numbers.hpp
  rai/lib/utility.cpp
Labels: documentation, quality improvements

#920 CLI validate blocks
  rai/rai_node/entry.cpp
Labels: enhancement

#1108 Deprecate bulk_pull_blocks
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: bug

#952 CLI debug_profile_process to test block_processor speed
  rai/rai_node/entry.cpp
Labels: enhancement
