Repository nanocurrency/nano-node, pull requests merged in 2018-11, with the labels that each got.

#1343 Filter password, wallet, key, seed from RPC logging
  rai/node/rpc.cpp
Labels: enhancement

#1335 Reply to confirm_reqs with a vote by hash
  rai/node/node.cpp
Labels: enhancement

#1357 CLI wallet_import force wallet creation if requested
  rai/node/cli.cpp
Labels: documentation, enhancement, quality improvements

#1330 Bootstrap traffic stats
  rai/node/bootstrap.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
  rai/qt/qt.cpp
Labels: enhancement

#1353 Make signatures non-deterministic
  ed25519-donna/ed25519.c
  rai/core_test/interface.cpp
Labels: enhancement

#1362 Fix vote_cache
  rai/node/lmdb.cpp
  rai/node/lmdb.hpp
Labels: bug

#1363 Fix new tests relying on deterministic signatures
  rai/core_test/block.cpp
  rai/core_test/conflicts.cpp
Labels: bug, release_blocker

#1371 Limit the amount of deduplication items we store
  rai/node/bootstrap.cpp
Labels: enhancement

#1368 Dedicate a full r hash block to attacker unknown bytes
  ed25519-donna/ed25519.c
Labels: enhancement

#1349 removing std::endl from filter_request
  rai/node/rpc.cpp
Labels: bug

#1376 Update .clang-format to be consistent with new version
  .clang-format
Labels: quality improvements

#1360 Actually use also_publish flag
  rai/node/node.cpp
Labels: bug

#1344 Log vote processing time
  rai/node/node.cpp
Labels: enhancement

#1375 Only observe blocks if callback is configured
  rai/node/node.cpp
Labels: enhancement

#1350 Single active_transactions mutex for vote_blocking
  rai/core_test/ledger.cpp
  rai/core_test/node.cpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: quality improvements

#1348 Make config upgrades more robust
  rai/node/logging.cpp
  rai/node/logging.hpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
  rai/rai_node/daemon.cpp
  rai/rai_node/daemon.hpp
  rai/rai_wallet/entry.cpp
Labels: functionality quality improvements

#1377 Add batch votes verification
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1378 Ensure ".clang-format" works with current clang-format tool
  .clang-format.base
  .gitignore
  ci/check-commit-format.sh
  ci/clang-format-all.sh
  ci/update-clang-format
  util/makesrc
Labels: quality improvements

#1379 RPC confirmation_quorum: optionally include account/ip/rep weight
  rai/node/peers.cpp
  rai/node/peers.hpp
  rai/node/rpc.cpp
Labels: enhancement

#1382 Replay votes in response to a confirm_req for an active block
  rai/core_test/node.cpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1243 Broadcast confirm_req in batches
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/peers.cpp
  rai/node/peers.hpp
Labels: enhancement

#1365 Add vote_processor overflow mode
  rai/node/node.cpp
Labels: enhancement

#1390 Restart the RPC connection acceptor in the face of errors
  rai/node/rpc.cpp
  rai/node/rpc_secure.cpp
Labels: bug

#1199 Message header extensions: remove unused flags
  rai/core_test/message.cpp
  rai/node/common.cpp
  rai/node/common.hpp
Labels: quality improvements

#1394 Add vote overflow stats
  rai/node/node.cpp
  rai/node/stats.cpp
  rai/node/stats.hpp
Labels: enhancement

#1396 Disable Arch linux gitlab builds will create an issue to address miss…
  .gitlab-ci.yml
Labels: bug, universe

#1395 git clone with a single branch does not include annotated tags ?
  util/makesrc
Labels: bug

#1401 Difficulty extraction
  rai/core_test/message.cpp
  rai/core_test/work_pool.cpp
  rai/lib/work.cpp
  rai/lib/work.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/wallet.cpp
Labels: enhancement

#1404 Fix secure rpc build
  CMakeLists.txt
  rai/node/CMakeLists.txt
Labels: functionality quality improvements

#1405 Add missing header
  rai/node/CMakeLists.txt
Labels: quality improvements

#1407 Use "count" in frontier_req_server
  rai/core_test/network.cpp
  rai/node/bootstrap.cpp
Labels: bug

#1406 Early detection for votes overflow
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1370 Add a config option to allow local peers
  rai/node/node.cpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
Labels: enhancement

#1332 Add support for Lazy Bootstrapping
  rai/core_test/message.cpp
  rai/core_test/network.cpp
  rai/core_test/node.cpp
  rai/node/bootstrap.cpp
  rai/node/bootstrap.hpp
  rai/node/common.cpp
  rai/node/common.hpp
  rai/node/lmdb.hpp
  rai/node/node.cpp
  rai/node/node.hpp
  rai/node/nodeconfig.cpp
  rai/node/nodeconfig.hpp
  rai/node/rpc.cpp
  rai/node/rpc.hpp
  rai/node/testing.cpp
  rai/rai_node/daemon.cpp
  rai/rai_node/daemon.hpp
  rai/rai_node/entry.cpp
  rai/secure/ledger.hpp
Labels: enhancement, major

#1411 Signature checking thread
  .gitignore
  rai/core_test/CMakeLists.txt
  rai/core_test/signing.cpp
  rai/lib/utility.cpp
  rai/lib/utility.hpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement

#1410 Ensure the block exists in account_history
  rai/node/rpc.cpp
  rai/secure/ledger.cpp
Labels: bug

#1413 Prioritizing transaction processing by difficulty.
  rai/core_test/conflicts.cpp
  rai/core_test/ledger.cpp
  rai/node/node.cpp
  rai/node/node.hpp
Labels: enhancement, major

#1415 Update bootstrap weights
  rep_weights_beta.bin
  rep_weights_live.bin
Labels: routine

#1366 CLI --debug_profile_votes
  rai/node/node.cpp
  rai/rai_node/entry.cpp
Labels: enhancement

#1417 Fix iteration in rai::bootstrap_attempt::lazy_finished
  rai/node/bootstrap.cpp
Labels: bug
