Repository nanocurrency/nano-node, pull requests merged in 2019-07, with the labels that each got.

#2111 Use confirmation request count instead of announcement term
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
Labels: non-functional change

#2115 only log if blocks have been processed and logging enabled
  nano/node/blockprocessor.cpp
Labels: bug

#2112 fix windows installer path
  CMakeLists.txt
  appveyor.yml
Labels: qt

#2116 remove else and always flush if over config.json active_elections_size
  nano/node/active_transactions.cpp
Labels: bug

#2121 Docker cache
  .travis.yml
  ci/deploy-docker.sh
  docker/ci/Dockerfile-base
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
  docker/node/Dockerfile
Labels: performance, universe

#2119 update default limit to (5 * 1024 * 1024) or 5Mb/s
  nano/core_test/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: performance

#2125 Send confirm_req each request_confirm loop
  nano/node/active_transactions.cpp
Labels: enhancement

#2127 Improve assert in tcp_channels::process_message ()
  nano/node/transport/tcp.cpp
Labels: bug

#2126 More aggressive setting confirmation height of frontiers during low tps
  nano/node/active_transactions.cpp
Labels: quality improvements

#2129 tsan: missing lock in ws active_difficulty unit test
  nano/core_test/websocket.cpp
Labels: sanitizers, unit test

#2130 Improve broadcast_confirm_req_batch delays and max size
  nano/node/network.cpp
Labels: bug, functionality quality improvements

#2132 Cleanup inactive channels from rep crawler
  nano/core_test/node.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/transport/tcp.cpp
Labels: functionality quality improvements

#2133 Improve assert in TCP node_id_handshake
  nano/node/bootstrap.cpp
Labels: bug

#2135 RPC stop action can take a long time to close the node down
  nano/nano_node/daemon.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/ipc.cpp
Labels: rpc nonbreaking change

#2140 Strange TSAN warnings running nano_rpc & making simultaneous requests
  nano/lib/errors.hpp
  nano/lib/ipc_client.cpp
  nano/rpc/rpc.cpp
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_connection.hpp
  nano/rpc/rpc_connection_secure.cpp
  nano/rpc/rpc_connection_secure.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc/rpc_handler.hpp
  nano/rpc/rpc_secure.cpp
Labels: sanitizers

#2141 Move confirm_frontiers higher up request loop
  nano/node/active_transactions.cpp
Labels: quality improvements

#2138 test validating #2116
  nano/core_test/active_transactions.cpp
Labels: unit test

#2131 [TSAN] Use only async signal safe functions in signal handlers
  nano/lib/work.cpp
  nano/nano_node/daemon.cpp
  nano/nano_rpc/entry.cpp
  nano/node/vote_processor.cpp
  nano/secure/utility.cpp
Labels: sanitizers

#2143 set default active_election_size to 50k
  nano/core_test/node.cpp
  nano/node/nodeconfig.hpp
Labels: performance

#2038 update docker config template and include default rpc config
  docker/node/config/beta.json
  docker/node/config/beta_rpc.json
  docker/node/config/live.json
  docker/node/config/live_rpc.json
  docker/node/entry.sh
Labels: bug, documentation

#2146 pre release maintenance
  .travis.yml
  ci/record_rep_weights.py
  rep_weights_live.bin
Labels: routine

#2144 Set genesis account to have a confirmation height of 1 after initial upgrade
  nano/core_test/block_store.cpp
  nano/node/cli.cpp
  nano/node/lmdb.cpp
Labels: bug

#2145 [Valgrind] Check if running under valgrind before doing death tests
  nano/core_test/difficulty.cpp
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/node/lmdb.cpp
Labels: sanitizers

#2136 Refactor ledger database code for reuse with different backends
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
Labels: non-functional change

#2142 Improve stacktrace output during release_assert
  nano/lib/CMakeLists.txt
  nano/lib/plat/default/debugging.cpp
  nano/lib/plat/linux/debugging.cpp
  nano/lib/rpcconfig.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_node/daemon.cpp
Labels: quality improvements

#2148 Improve docker build speed on multi-core machines
  docker/node/Dockerfile
Labels: quality improvements

#2147 Fix unused variable error in deployments
  nano/lib/plat/linux/debugging.cpp
Labels: build-error

#2150 Remove extra core utilised during docker deployment build
  docker/node/Dockerfile
Labels: build-error

#2157 Add RocksDB to the build system
  .travis.yml
  CMakeLists.txt
  appveyor.yml
  ci/build-travis.sh
  cmake/Modules/FindRocksDB.cmake
  docker/ci/Dockerfile-base
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
  nano/core_test/CMakeLists.txt
  nano/core_test/rocksdb_test.cpp
  nano/node/CMakeLists.txt
Labels: database, tool

#2158 Fix compile errors in release mode after warning->error change
  nano/core_test/block_store.cpp
  nano/core_test/difficulty.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/lib/blocks.hpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
  nano/node/cli.cpp
  nano/node/election.cpp
  nano/node/lmdb.cpp
  nano/node/network.cpp
  nano/node/testing.cpp
  nano/node/voting.cpp
  nano/node/wallet.cpp
  nano/node/websocket.cpp
  nano/qt/qt.cpp
  nano/secure/blockstore.hpp
  nano/secure/common.cpp
  nano/secure/ledger.cpp
Labels: build-error

#2152 Fix node_id assign for bootstrap_server
  nano/node/bootstrap.cpp
Labels: bug

#2155 Improve votes caching for same account & increase max cache size
  nano/core_test/node.cpp
  nano/node/network.cpp
  nano/node/voting.cpp
  nano/secure/common.cpp
Labels: quality improvements

#2163 Assert for disabled bootstrap modes
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/json_handler.cpp
Labels: documentation, quality improvements, rpc semantics change

#2173 Move alarm/operation out of node
  nano/lib/CMakeLists.txt
  nano/lib/alarm.cpp
  nano/lib/alarm.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: non-functional change

#2169 Travis/streamline
  .travis.yml
Labels: universe

#2178 fix boost downloads
  util/build_prep/bootstrap_boost.sh
Labels: build-error, universe

#2180 escaping regex for deployment on master or releases/v* branches
  .travis.yml
Labels: build-error, docker

#2177 More preparation for new database backends
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/node/CMakeLists.txt
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_env.cpp
  nano/node/lmdb/lmdb_env.hpp
  nano/node/lmdb/lmdb_iterator.hpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/node/lmdb/wallet_value.cpp
  nano/node/lmdb/wallet_value.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/secure/CMakeLists.txt
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/slow_test/node.cpp
Labels: blocker, database

#2162 Allow the RPC server to be run on a different system
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/rpc/rpc_request_processor.cpp
  nano/rpc_test/rpc.cpp
Labels: bug, rpc nonbreaking change

#2182 Principal representative factor as a network constant
  nano/lib/config.hpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: non-functional change

#2170 add git commit hash and compiler info to logging and version calls
  CMakeLists.txt
  nano/core_test/CMakeLists.txt
  nano/lib/config.hpp
  nano/nano_node/CMakeLists.txt
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_rpc/CMakeLists.txt
  nano/nano_rpc/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/rpc.cpp
Labels: documentation, non-functional change, rpc nonbreaking change

#2185 boost 1.70 requires log_setup component specifically updated CMAKE 1.…
  CMakeLists.txt
  util/build_prep/bootstrap_boost.sh
Labels: build-error, non-functional change

#2151 Accept multiplier in work_generate and work_validate
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, rpc semantics change

#2184 RPC version network label and identifier
  nano/node/active_transactions.cpp
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: non-functional change, rpc nonbreaking change

#1847 Compute work differently on Beta networks
  nano/lib/work.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#2164 Use confirm_req by hash + root for upgraded peers
  nano/node/active_transactions.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/repcrawler.cpp
Labels: functionality quality improvements, networking
