Repository nanocurrency/nano-node, pull requests merged in 2019-09, with the labels that each got.

#2266 Add config option to conditionally enable RocksDB backend
  nano/core_test/block_store.cpp
  nano/core_test/core_test_main.cc
  nano/core_test/toml.cpp
  nano/lib/CMakeLists.txt
  nano/lib/rocksdbconfig.cpp
  nano/lib/rocksdbconfig.hpp
  nano/lib/walletconfig.cpp
  nano/lib/walletconfig.hpp
  nano/nano_node/daemon.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/secure/blockstore.hpp
Labels: documentation, quality improvements

#2270 Add log when a block difficulty is updated in active transactions
  nano/core_test/toml.cpp
  nano/node/active_transactions.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: documentation, enhancement, non-functional change

#2271 Fix delay in stopping the node
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
Labels: bug

#2269 CLI --debug_validate_blocks enhancement
  nano/nano_node/entry.cpp
Labels: enhancement

#2273 Fix possible issue in active_transactions.adjusted_difficulty_overflow_min test
  nano/core_test/active_transactions.cpp
Labels: bug, unit test

#2265 Prevent possible from_multiplier () function overflow
  nano/core_test/difficulty.cpp
  nano/lib/numbers.cpp
Labels: quality improvements

#2275 add rocksdb to build artifacts lacking it
  ci/build-deploy.sh
  docker/node/Dockerfile
Labels: docker, universe

#2272 Disable unchecked cleanup if node is not synchronized
  nano/node/node.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: quality improvements

#2274 Split bootstrap source files
  nano/node/CMakeLists.txt
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_bulk_push.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/node.hpp
Labels: non-functional change, quality improvements

#2277 Use distributed work in work watcher
  nano/node/wallet.cpp
Labels: bug

#2278 Fixing test to use unique_path each time.
  nano/core_test/socket.cpp
Labels: bug, unit test

#2254 Remove preferred TPC response channels
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: networking

#2276 add master tag for beta and caching for subsequent artifacts_beta builds
  .travis.yml
  ci/deploy-docker.sh
Labels: docker

#2159 Cache recently arrived votes
  nano/core_test/active_transactions.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
Labels: enhancement

#2280 Fix off by one in broadcast_confirm_req_batch
  nano/node/network.cpp
Labels: bug, networking

#2279 Fix active transactions difficulty update for state blocks
  nano/core_test/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
Labels: bug

#2281 Handle work generation failure and cancel
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement

#2282 Enhance block processor filter
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
Labels: functionality quality improvements

#2284 docker `--cache-from` set as single string argument with =
  ci/deploy-docker.sh
Labels: docker

#2287 Add --config option to rpc process
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/nano_rpc/entry.cpp
  nano/node/daemonconfig.cpp
Labels: toml

#2286 Improve bootstrap attempt locking
  ci/build-travis.sh
  nano/lib/locks.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
Labels: performance

#2288 Build RocksDB library as portable in docker
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
Labels: database, docker

#2283 Replace account_info::rep_block with representative account
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: documentation, quality improvements

#2289 Websocket subscription for work notifications
  nano/core_test/distributed_work.cpp
  nano/core_test/websocket.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2291 Some minor cleanup
  nano/core_test/epochs.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/node.cpp
  nano/secure/CMakeLists.txt
  nano/secure/epoch.cpp
  nano/secure/epoch.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: non-functional change, quality improvements

#2294 Fix rpc.work_peer_bad
  nano/core_test/distributed_work.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
Labels: bug, unit test

#2290 Add block count cache
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node_observers.hpp
  nano/node/online_reps.cpp
  nano/node/vote_processor.cpp
  nano/node/voting.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt_test/qt.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: functionality quality improvements, performance

#2292 Lazy bootstrap cleanup & basic improvements
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: quality improvements

#2299 Verify pubkey against special keys in wallet
  nano/core_test/active_transactions.cpp
  nano/core_test/epochs.cpp
  nano/core_test/wallet.cpp
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
Labels: api semantics change

#2295 Support --config option in Qt wallet
  nano/nano_wallet/entry.cpp
Labels: qt

#2303 Update broadcast_confirm_req_batch to handle PoW priority
  nano/node/active_transactions.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: bug, functionality quality improvements

#2305 Make generate_config produce commented-out entries by default
  nano/lib/tomlconfig.hpp
  nano/node/cli.cpp
Labels: toml

#2298 Stacktrace with backtrace to display files and lines
  CMakeLists.txt
  nano/lib/CMakeLists.txt
  nano/lib/utility.cpp
  nano/nano_node/CMakeLists.txt
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/lmdb/lmdb_txn.cpp
Labels: documentation, quality improvements, tool

#2302 Checking for frontiers only if necessary
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: performance

#2297 Fix a bug in the rep_block -> representative conversion
  nano/core_test/ledger.cpp
  nano/secure/ledger.cpp
Labels: bug, unit test

#2307 ws keepalive
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
Labels: documentation, websockets

#2308 Quality of life updates for distributed work
  nano/core_test/distributed_work.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#2311 Snapshot/Vacuum should use the rocksdb config option
  nano/node/cli.cpp
  nano/node/cli.hpp
Labels: bug, database

#2313 Set NANO_ROCKSDB define even when set to OFF
  CMakeLists.txt
  nano/node/cli.cpp
Labels: build-error

#2316 Add some RocksDB TOML config options to tune memory usage
  nano/core_test/toml.cpp
  nano/lib/rocksdbconfig.cpp
  nano/lib/rocksdbconfig.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/secure/blockstore.hpp
Labels: database, toml

#2317 Fix init order warning
  nano/node/distributed_work.cpp
Labels: static-analysis

#2309 Classify traffic stats correctly
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/transport/udp.cpp
  nano/qt/qt.cpp
Labels: api semantics change, documentation

#2318 Account creation refresh in qt wallet
  nano/qt/qt.cpp
Labels: qt

#2233 Fire callback & add to history after confirmation height is set
  nano/core_test/CMakeLists.txt
  nano/core_test/confirmation_height.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/write_database_queue.hpp
Labels: quality improvements

#2156 Remove querying pending confirmation height in various operations
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
Labels: awaiting response, documentation, rpc semantics change

#2310 Support epoch 2
  nano/core_test/block_store.cpp
  nano/core_test/epochs.cpp
  nano/core_test/ledger.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallets.cpp
  nano/lib/blocks.hpp
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_iterator.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_iterator.hpp
  nano/node/testing.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/epoch.cpp
  nano/secure/epoch.hpp
  nano/secure/ledger.cpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
Labels: enhancement

#2319 Periodic rep crawler weights update
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: quality improvements

#2320 Add confirmation request count to election_status
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, websockets
