Repository nanocurrency/nano-node, pull requests merged in 2019-01, with the labels that each got.

#1528 Block size computation improvement
  nano/lib/blocks.hpp
Labels: quality improvements

#1527 Update license year 2019
  LICENSE
Labels: documentation, routine, universe

#1515 Remove dead link to forum from readme
  README.md
Labels: documentation

#1533 Add recursive_mutex to foreach_representative
  nano/core_test/node.cpp
  nano/node/wallet.cpp
Labels: bug

#1537 Rename all links to our GitHub repo
  .github/ISSUE_TEMPLATE.md
  CMakeLists.txt
  README.md
  util/changelog_generator
  util/makesrc
Labels: documentation, universe

#1531 "update_existing_accounts" option for RPC wallet_representative_set
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: enhancement

#1507 Only build essential boost libraries in docker
  docker/ci/Dockerfile
Labels: documentation

#1364 Slightly more efficient way of storing duplicates
  nano/core_test/network.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: functionality quality improvements, low effort remaining

#1223 Zero-terminate all things we refer to as strings
  nano/core_test/interface.cpp
  nano/lib/interface.cpp
  nano/lib/interface.h
Labels: api semantics change, bug

#1540 Deprecate all existing API calls
  nano/lib/interface.h
Labels: api semantics change

#1499 Remove ip_address_hash from std namespace
  nano/node/common.hpp
Labels: quality improvements

#1549 Get rid of nounset flag when running the Boost bootstrap subscript
  util/build_prep/bootstrap_boost.sh
  util/build_prep/update-common
Labels: bug

#1547 Optional deterministic index in RPC account_create
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: enhancement

#1509 Disable voting by default
  docker/node/config/beta.json
  docker/node/config/live.json
  nano/node/nodeconfig.cpp
Labels: enhancement, major

#1446 Check origination time before starting election
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1536 Lack of contact timestamping drops peers
  nano/core_test/network.cpp
  nano/node/peers.cpp
Labels: enhancement, experiment

#1526 Timer utilities
  nano/core_test/CMakeLists.txt
  nano/core_test/timer.cpp
  nano/lib/CMakeLists.txt
  nano/lib/timer.hpp
  nano/node/node.cpp
Labels: enhancement

#1356 (Proposal) Fix multiple rpc callbacks for same host.
  nano/node/node.cpp
  nano/node/node.hpp
Labels: awaiting response, functionality quality improvements

#1045 Move to random_pool for shuffling
  nano/node/node.cpp
  nano/node/peers.cpp
Labels: quality improvements, universe

#1550 Improve RPC shutdown
  nano/node/rpc.cpp
Labels: bug

#1524 Fix tests broken with #1510
  nano/qt_test/qt.cpp
Labels: bug, unit test

#1569 Restore blocks_hashes.insert
  nano/node/node.cpp
Labels: bug

#1570 Limit recursive confirm_back ()
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#1572 Remove unnecessary inline specifier
  nano/node/common.hpp
  nano/node/stats.hpp
Labels: quality improvements

#1228 For Docker, log output to a file (unrotated !)
  docker/node/entry.sh
Labels: functionality quality improvements, low effort remaining

#1581 List of rolled back blocks in block_processor
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1586 Fix RPC wallet_change_seed
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: bug

#1421 MDB improvements
  nano/node/lmdb.cpp
Labels: enhancement, experiment

#1594 Test node.block_processor_reject_rolled_back
  nano/core_test/node.cpp
Labels: unit test

#1600 Expanding root to uint512_union
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: enhancement

#1599 json config: fix upgrade of required child nodes
  nano/core_test/node.cpp
  nano/core_test/uint256_union.cpp
  nano/lib/jsonconfig.hpp
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
  nano/node/logging.cpp
  nano/node/nodeconfig.cpp
  nano/node/rpc.cpp
Labels: bug

#1532 Fix intermittent send_node_id_handshake failure
  nano/node/node.cpp
Labels: bug, unit test

#1598 Rename announce_votes () to request_confirm ()
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: quality improvements

#1565 Priority lazy bootstrap for wallet accounts
  nano/core_test/gap_cache.cpp
  nano/core_test/network.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/rpc.cpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: enhancement

#1486 Stop usual pull request with more than 16k unexpected blocks
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: enhancement

#1571 Check state blocks existence in ledger before verification
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1595 Fix asan issue (illegal downcast) in test
  nano/core_test/rpc.cpp
Labels: unit test

#1579 Remove checksum table
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/lib/numbers.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/secure/blockstore.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: medium effort remaining, quality improvements, question

#1601 Indicate active network in Qt wallet
  nano/qt/qt.cpp
Labels: enhancement

#1615 Remove deprecated bulk_pull_blocks
  nano/core_test/message_parser.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/node.cpp
Labels: quality improvements

#1613 Upgrade preconfigured peers in config.json file to use nano url instead of rai
  nano/core_test/node.cpp
  nano/lib/jsonconfig.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: quality improvements

#1591 Include assert.h, needed for assert()
  nano/lib/blocks.hpp
  nano/lib/errors.hpp
  nano/lib/plat/windows/perms.cpp
Labels: bug

#1623 Increase default max log folder size to 128Mb
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: enhancement

#719 Modify `wallet_create` CLI to allow seed & password change
  nano/node/cli.cpp
Labels: awaiting response, question

#1593 Make asan/tsan link on macOS, add tsan cache variable
  CMakeLists.txt
Labels: enhancement

#1592 Fix rare time_bound & time_cutoff tests failures
  nano/core_test/network.cpp
Labels: bug, unit test

#1590 Connect to a bootstrap peer only once concurrently
  nano/node/bootstrap.cpp
  nano/node/common.hpp
Labels: enhancement

#1603 Add existing blocks check for lazy bootstrap pulls
  nano/node/bootstrap.cpp
Labels: enhancement

#1577 RPC debug command line option
  nano/nano_node/entry.cpp
Labels: enhancement

#1105 Allow local preconfigured peers
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
Labels: enhancement

#1580 Add size expressions to bootstrap types
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
Labels: quality improvements

#1626 Improved error message when unable to accept RPC connection
  nano/node/rpc.cpp
Labels: enhancement

#1622 Add optional "offset" & "reverse" parameters for RPC chain
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: enhancement

#1628 Fix rpc.wallet_create_seed test
  nano/core_test/rpc.cpp
  nano/node/testing.cpp
Labels: bug, unit test

#1639 Add support for getting the current thread's name as a string
  nano/lib/plat/darwin/thread_role.cpp
  nano/lib/plat/freebsd/thread_role.cpp
  nano/lib/plat/linux/thread_role.cpp
  nano/lib/plat/windows/thread_role.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
Labels: enhancement, quality improvements

#1616 RPC uptime
  nano/core_test/rpc.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: enhancement

#1642 fix wallet.startup_balance
  nano/qt_test/qt.cpp
Labels: unit test

#1641 update .travis.yml
  .travis.yml
Labels: unit test

#1627 Add wallet locked check to RPC wallet_representative_set
  nano/node/rpc.cpp
Labels: bug

#1619 Reload wallets list from disk each 5 minutes
  nano/core_test/wallets.cpp
  nano/node/node.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: enhancement, experiment

#1646 Count processed forks in stats
  nano/node/node.cpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: enhancement

#1647 Update balance on ratio change
  nano/qt/qt.cpp
Labels: qt

#1554 Add sideband information to database.
  nano/core_test/block_store.cpp
  nano/core_test/rpc.cpp
  nano/core_test/versioning.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/interface.h
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/ledger.cpp
Labels: enhancement, major

#1649 Filter outdated_version errors from logging
  nano/node/node.cpp
Labels: enhancement

#1589 [QT] Automatic determinictic accounts check after leaving the synchronisation state
  nano/core_test/wallet.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/qt/qt.hpp
Labels: enhancement

#1652 Fix vc++ compile error in write_legacy_sideband
  nano/core_test/block_store.cpp
Labels: build-error

#1638 Better handling of TCP accept overflow
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: functionality quality improvements

#994 Add wallet_history with timestamps
  nano/core_test/rpc.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: enhancement

#1241 RPC "sign" (hash, block)
  nano/core_test/rpc.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: enhancement

#1046 confirm_req_hash to reduce bandwidth usage
  nano/core_test/block.cpp
  nano/core_test/message_parser.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/secure/common.hpp
Labels: enhancement, protocol feature

#1434 Support external RPC servers via IPC
  nano/core_test/CMakeLists.txt
  nano/core_test/ipc.cpp
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/ipc.cpp
  nano/node/ipc.hpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: enhancement, major

#1625 RPC to clear stats
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: enhancement

#1650 Fix race conditions reported by TSAN
  nano/node/bootstrap.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#1651 Multi-thread the signature checker
  nano/core_test/node.cpp
  nano/core_test/signing.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#1542 Local votes cache to reduce CPU usage for representatives
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: enhancement

#1492 Store timestamp & verified signature status in unchecked table
  nano/core_test/block_store.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: enhancement

#1663 Fix windows tests for ipc
  nano/node/ipc.cpp
Labels: bug

#1629 Fix potential div-by-zero issue in receive_frontier
  nano/node/bootstrap.cpp
Labels: bug

#1632 Memory stats in RPC
  nano/core_test/rpc.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
  nano/node/rpc.cpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: enhancement

#1664 Improve node::process_confirmed ()
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#1657 Fixing issue where blocks were not being rebroadcast immediately upon…
  nano/node/node.cpp
  nano/node/node.hpp
Labels: quality improvements

#1665 Encapsulate and lock stat_datapoint, fixes core_test tsan
  nano/node/node.cpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: unit test

#1666 Set current time for block in RPC process
  nano/node/rpc.cpp
Labels: bug

#1673 Add missing headers in timer
  nano/lib/timer.hpp
Labels: build-error

#1674 Fix scope issue when setting thread names in the multi-threaded signature checker
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#1644 Initial Travis Windows support
  .travis.yml
  ci/build-travis-win.sh
  ci/packages.config
  ci/test.sh
  util/build_prep/windows/packages.config
  util/build_prep/windows/prep.sh
Labels: unit test
