Repository nanocurrency/nano-node, pull requests merged in 2019-05, with the labels that each got.

#1940 Improve receivable_processor.send_with_receive test
  nano/core_test/network.cpp
Labels: unit test

#1948 Fix some websocket test issues
  nano/core_test/websocket.cpp
Labels: unit test

#1951 Allow long running read transactions to be broken up
  nano/core_test/block_store.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/slow_test/node.cpp
Labels: blocker, functionality quality improvements

#1949 Fix regression introduced by 100-continue
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_connection.hpp
Labels: bug

#1955 Add pull request failure to stats
  nano/node/bootstrap.cpp
  nano/node/stats.cpp
  nano/node/stats.hpp
Labels: rpc nonbreaking change

#1943 Work value in RPC work_validate response
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#1960 updating work_watcher::run
  nano/node/wallet.cpp
Labels: bug

#1961 nano_rpc included in packaging
  nano/nano_rpc/CMakeLists.txt
  nanocurrency-beta.spec.in
  nanocurrency.spec.in
Labels: bug, build-error

#1939 Add work check for ledger::process () in Debug mode
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/secure/ledger.cpp
Labels: unit test

#1952 Fix RPC block_create error getting overridden
  nano/node/json_handler.cpp
Labels: bug

#1964 Stop node when using an incompatible ledger
  nano/core_test/block_store.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: bug

#1966 Fix tests failing after PR#1939
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
Labels: unit test

#1969 No longer use bin & lib sub-folders in the installers
  .travis.yml
  CMakeLists.txt
  nano/lib/CMakeLists.txt
  nano/nano_node/CMakeLists.txt
  nano/nano_rpc/CMakeLists.txt
Labels: universe

#1967 Makes sure a write lock can be avoided when launching an inactive_node
  nano/core_test/node.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/wallet.cpp
Labels: quality improvements

#1947 LMDB transaction time tracker
  nano/core_test/node.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/lib/timer.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/CMakeLists.txt
  nano/node/diagnosticsconfig.cpp
  nano/node/diagnosticsconfig.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/lmdb_txn_tracker.cpp
  nano/node/lmdb_txn_tracker.hpp
  nano/node/logging.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
Labels: documentation, rpc nonbreaking change

#1959 Backup config files when upgrading
  nano/core_test/node.cpp
  nano/lib/jsonconfig.hpp
  nano/node/node_rpc_config.cpp
Labels: documentation, functionality quality improvements

#1954 Reduce length holding read transaction open for in confirmation height processor
  nano/core_test/block_store.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#1970 Version and allow_unsafe upgrade in ipc config
  nano/core_test/ipc.cpp
  nano/node/ipcconfig.cpp
  nano/node/ipcconfig.hpp
  nano/node/nodeconfig.cpp
Labels: bug

#1968 Fixing dynamic re-work and trend from elections
  nano/core_test/CMakeLists.txt
  nano/core_test/difficulty.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
Labels: functionality quality improvements

#1980 Move io_threads to rpc process config node
  load-tester/src/launch_node_and_rpc.rs
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/nano_rpc/entry.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation

#1978 Prevent (optionally) block processor batched writes from being logged by the lmdb tracker
  nano/core_test/node.cpp
  nano/node/diagnosticsconfig.cpp
  nano/node/diagnosticsconfig.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/lmdb_txn_tracker.cpp
  nano/node/lmdb_txn_tracker.hpp
  nano/node/node.cpp
Labels: rpc nonbreaking change

#1979 Add modify callback to prevent violating boost multiindex invariants
  nano/core_test/peer_container.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: bug

#1938 TCP socket rewrite with strand and queueing support
  nano/core_test/CMakeLists.txt
  nano/core_test/logger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/socket.cpp
  nano/core_test/testutil.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_wallet/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/ipc.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/stats.cpp
  nano/node/stats.hpp
  nano/node/testing.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/qt_system/entry.cpp
Labels: documentation, networking

#1965 Prevent dropping of unchecked on restart if high unchecked
  nano/node/lmdb.cpp
  nano/node/node.cpp
Labels: enhancement

#1972 Framing support for realtime network messages
  nano/core_test/block.cpp
  nano/core_test/message.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
Labels: enhancement, networking

#1981 Finish up difficulty/multiplier semantics in RPC work_generate and work_validate
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation

#1971 Move common UDP/TCP channels functions to transport
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: enhancement, rpc nonbreaking change

#1984 Work multiplier format and RPC work_validate fix for lower difficulties
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/lib/work.cpp
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug

#1985 Update config path on macos/boost 1.69
  nano/nano_node/daemon.cpp
Labels: build-error

#1986 Fix UDP channels insert
  nano/node/node.cpp
  nano/node/transport/udp.cpp
Labels: bug

#1983 Fix race when notifying bootstrap initiator listeners
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: sanitizers

#1987 Show opencl device memory stats
  nano/node/openclwork.cpp
Labels: tool

#1988 Add unnecessary lambda capture to please VS2017
  nano/core_test/socket.cpp
Labels: build-error

#1989 Rewrite load tester in C++
  .gitignore
  .travis.yml
  CMakeLists.txt
  ci/build-travis.sh
  ci/test.sh
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
  load-tester/Cargo.lock
  load-tester/Cargo.toml
  load-tester/src/launch_node_and_rpc.rs
  load-tester/src/main.rs
  load-tester/src/rpc.rs
  nano/core_test/CMakeLists.txt
  nano/core_test/test_messages.cpp
  nano/load_test/CMakeLists.txt
  nano/load_test/entry.cpp
Labels: tool

#1992 Fix off by one error in frontier req server
  nano/node/bootstrap.cpp
Labels: functionality quality improvements

#1995 Reinstate debug_rpc command
  nano/nano_node/entry.cpp
Labels: bug

#1993 Clean up json upgrade code/unused variables
  nano/nano_wallet/entry.cpp
  nano/node/daemonconfig.cpp
  nano/node/logging.cpp
  nano/node/nodeconfig.cpp
Labels: non-functional change

#1996 Fix test by disabling confirmation, as a result the block wont be con…
  nano/core_test/node.cpp
Labels: unit test

#1994 Apply Blake2b AVX2 changes
  crypto/blake2/blake2b-compress-avx2.h
  crypto/blake2/blake2b-load-avx2-simple.h
  crypto/blake2/blake2b-load-avx2.h
Labels: performance

#1997 Fix RPC secure build
  nano/core_test/difficulty.cpp
  nano/load_test/entry.cpp
  nano/rpc/rpc_connection_secure.cpp
  nano/rpc/rpc_connection_secure.hpp
  nano/rpc/rpc_secure.cpp
Labels: build-error

#1998 Fix load tester for mac with boost 1.69
  nano/load_test/entry.cpp
Labels: bug

#1973 Add severity logging levels, and send errors to syslog/Event Viewer (incl failed rollbacks for confirmed blocks)
  CMakeLists.txt
  nano/core_test/conflicts.cpp
  nano/core_test/logger.cpp
  nano/core_test/network.cpp
  nano/core_test/testutil.hpp
  nano/core_test/websocket.cpp
  nano/lib/CMakeLists.txt
  nano/lib/logger_mt.hpp
  nano/lib/plat/windows/perms.cpp
  nano/lib/plat/windows/registry.cpp
  nano/lib/utility.hpp
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, enhancement

#1990 Bounded active transaction
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/node.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: enhancement, protocol feature

#1999 use correct namespace to fix literal usage in active_transactions
  nano/core_test/active_transactions.cpp
Labels: build-error

#2000 Remove debugging assert from socket
  nano/node/socket.cpp
Labels: networking

#2002 Fix TSAN error with test confirmation_height.conflict_rollback_cemented
  nano/core_test/network.cpp
  nano/core_test/testutil.hpp
  nano/rpc_test/rpc.cpp
Labels: sanitizers, unit test

#1991 Test peer caching on node restart
  nano/core_test/node.cpp
Labels: unit test

#2005 Rename active_difficulty RPC response
  nano/node/json_handler.cpp
Labels: documentation

#2004 active_transactions.prioritize_chains timing fix
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
Labels: unit test

#2003 Decrease logging level for "Reserved sender" message
  nano/node/transport/udp.cpp
Labels: routine

#2008 generate difficulty was passing hash by ref
  nano/node/json_handler.cpp
Labels: bug, unit test

#2009 Join threads in socket tests
  nano/core_test/socket.cpp
Labels: unit test

#2007 WebSocket fixes and improvements
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: websockets

#2011 Update test script
  ci/test.sh
Labels: unit test

#2013 Fix TSAN error for the rpc.database_txn_tracker test
  nano/rpc_test/rpc.cpp
Labels: sanitizers, unit test

#2012 active_transactions test cleanup
  nano/core_test/active_transactions.cpp
Labels: unit test

#2006 Set minimum difficulty for RPC "work_generate"
  nano/lib/errors.cpp
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
Labels: rpc semantics change

#1962 Send live network messages over TCP
  nano/core_test/active_transactions.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/repcrawler.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: enhancement, networking

#2015 remove sleep from test
  nano/core_test/active_transactions.cpp
Labels: unit test

#2016 Update stringstream test sink to bounds check the strings
  nano/core_test/testutil.hpp
Labels: sanitizers, unit test

#2017 Bump protocol version
  nano/secure/common.hpp
Labels: protocol issue

#2024 Factor out network
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/CMakeLists.txt
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: quality improvements

#2001 Websockets: prevent re-sub
  nano/core_test/websocket.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: bug, websockets

#2025 Use a memory pool to reduce block deserialization heap usage
  nano/core_test/core_test_main.cc
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/wallet.cpp
  nano/qt_system/entry.cpp
  nano/qt_test/entry.cpp
  nano/rpc_test/entry.cpp
  nano/slow_test/entry.cpp
Labels: quality improvements

#2022 Increase server timeout to receive TCP header
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement, networking

#2019 Increase tcp_io_timeout for test TSAN/ASAN builds
  nano/core_test/network.cpp
  nano/lib/config.hpp
  nano/node/nodeconfig.hpp
Labels: sanitizers, unit test

#2031 Include ordering fix
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/udp.hpp
Labels: build-error

#2033 Remove node dependency from secure library
  CMakeLists.txt
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/versioning.cpp
  nano/lib/CMakeLists.txt
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/lib/utility.hpp
  nano/nano_node/daemon.cpp
  nano/nano_rpc/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/nano_wallet/entry_com.cpp
  nano/node/CMakeLists.txt
  nano/node/common.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/lmdb.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/wallet.cpp
  nano/secure/CMakeLists.txt
  nano/secure/blockstore.cpp
  nano/secure/common.cpp
  nano/secure/ledger.cpp
  nano/secure/plat/osx/working.mm
  nano/secure/plat/posix/working.cpp
  nano/secure/plat/windows/working.cpp
  nano/secure/utility.cpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
  nano/secure/working.hpp
Labels: non-functional change

#2030 Factor out election
  nano/node/CMakeLists.txt
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: non-functional change

#2034 Support for boost 1.70 in load tester
  nano/load_test/entry.cpp
Labels: build-error

#2028 Add configurable vote generator delay and bundling test
  nano/core_test/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/voting.cpp
Labels: enhancement

#2037 Change gap cache voters to use a vector
  nano/node/node.cpp
  nano/node/node.hpp
Labels: performance

#2040 Add node_constants half_period
  nano/node/transport/tcp.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug

#2041 Factor out vote processor
  nano/node/CMakeLists.txt
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: non-functional change

#2042 Fix initialization order bug in nano::node
  nano/node/active_transactions.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#2036 Update broadcast_confirm_req to use confirm_req by hash
  nano/node/network.cpp
Labels: enhancement, networking

#2044 Remove unused std::expected library
  nano/lib/CMakeLists.txt
  nano/lib/errors.hpp
  nano/lib/expected.hpp
Labels: non-functional change

#2026 Remove unnecessary copies when using lmdb cursors
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/cli.cpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/testing.cpp
  nano/node/vote_processor.cpp
  nano/node/wallet.cpp
  nano/qt/qt.cpp
  nano/secure/ledger.cpp
Labels: non-functional change, performance

#1921 Add more information after a segmentation fault
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
Labels: experiment, functionality quality improvements

#2043 Fix deadlock in tests
  nano/node/bootstrap.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug, unit test

#2029 Move SYN cookies & response channels to separate classes
  nano/core_test/network.cpp
  nano/node/bootstrap.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: quality improvements

#2046 Remove count byte from confirm_req by hash
  nano/node/common.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: networking

#1982 Prioritize frontiers for background confirmation
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: functionality quality improvements
