Repository nanocurrency/nano-node, pull requests merged in 2019-10, with the labels that each got.

#2321 generate sample node and rpc toml after building nano_node target
  CMakeLists.txt
  nano/nano_node/CMakeLists.txt
Labels: toml

#2322 Profile work validation
  nano/nano_node/entry.cpp
Labels: documentation, tool

#2323 CLI command to output the total number of (un)opened account versions
  nano/nano_node/entry.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_iterator.hpp
  nano/secure/epoch.cpp
  nano/secure/epoch.hpp
Labels: bug, documentation, enhancement

#2327 Basic confirmation request loop enhancements
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: blocker, enhancement, networking

#2332 Fix work_pool.opencl test hanging
  nano/core_test/work_pool.cpp
  nano/nano_node/entry.cpp
Labels: unit test

#2330 Secondary list of peers for generating work
  nano/core_test/distributed_work.cpp
  nano/core_test/toml.cpp
  nano/core_test/wallet.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, rpc nonbreaking change

#2334 tsan: fix race in inactive_votes_cache_multiple_votes
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/secure/versioning.cpp
Labels: sanitizers

#2304 RPC epoch_upgrade
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/qt/qt.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: documentation, enhancement, rpc nonbreaking change

#2337 Update from_multiplier () overflow checks
  nano/lib/numbers.cpp
Labels: bug

#2329 Fix UPnP
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/portmapping.cpp
Labels: bug

#2315 Add lazy bootstrap possible links and accounts
  nano/core_test/CMakeLists.txt
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement

#2336 Unchecked cleanup tuning
  nano/node/node.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement

#2339 Attempt to fetch account from block hash in RPC work_generate
  nano/node/distributed_work.hpp
  nano/node/json_handler.cpp
Labels: bug, functionality quality improvements

#2338 Fix active difficulty calculation
  nano/node/active_transactions.cpp
Labels: bug

#2340 Output error message with qt wallet if RocksDB is enabled in config but is unsupported
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/nano_wallet/entry.cpp
  nano/node/node.cpp
Labels: qt

#2341 RPC unchecked json_block option
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#2342 Fix disabled ongoing unchecked cleanup
  nano/node/bootstrap/bootstrap.cpp
  nano/node/node.cpp
Labels: bug

#2344 create build cache for mac qt in external repo and pull in for testing and artifacts.
  .travis.yml
  util/build_prep/macosx/build_qt.sh
Labels: build-error

#2347 Fix bootstrap attempt not stopping
  nano/node/bootstrap/bootstrap.cpp
Labels: bug

#2345 Suppress RocksDB TSAN warnings with Clang
  tsan_suppressions
Labels: documentation, sanitizers

#2348 Fix link ordering issues
  nano/nano_rpc/CMakeLists.txt
  nano/node/CMakeLists.txt
Labels: build-error

#2350 Update beta network bootstrap weights for v20, cutoff 14M
  rep_weights_beta.bin
Labels: routine

#2353 TSAN error in node.peers test
  nano/node/network.cpp
  nano/node/network.hpp
Labels: sanitizers, unit test

#2355 Distributed work test failures under ASAN
  nano/core_test/distributed_work.cpp
Labels: sanitizers, unit test

#2351 TSAN error with block work
  nano/core_test/active_transactions.cpp
Labels: sanitizers, unit test

#2358 Update travis beta-osx job with cached qt
  .travis.yml
Labels: build-error

#2359 Improve sample configuration file
  nano/lib/diagnosticsconfig.cpp
  nano/lib/rocksdbconfig.cpp
  nano/lib/rpcconfig.cpp
  nano/lib/stats.cpp
  nano/node/cli.cpp
  nano/node/ipcconfig.cpp
  nano/node/logging.cpp
  nano/node/node_rpc_config.cpp
  nano/node/nodeconfig.cpp
  nano/node/websocketconfig.cpp
Labels: documentation, toml

#2356 ASAN error in vote_by_hash test
  nano/core_test/node.cpp
Labels: sanitizers, unit test

#2360 ASAN leak when exiting node
  nano/lib/utility.cpp
Labels: sanitizers

#2352 Add support for launch flags passed to nano_wallet
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/cli.hpp
Labels: bug

#2349 Confirm frontiers for bootstrap with multiple failures
  nano/core_test/bootstrap.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/common.cpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/nodeconfig.hpp
  nano/node/repcrawler.hpp
Labels: beta testing wanted, documentation, quality improvements, rpc nonbreaking change

#2361 Docker USER support
  docker/node/Dockerfile
Labels: docker, documentation

#2335 Restart dropped elections for unconfirmed blocks with higher PoW
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/wallet.cpp
Labels: enhancement, networking

#2363 move min bootstrap and traffic to v16
  nano/secure/common.hpp
Labels: networking, routine

#2365 Use std::condition_variable_any with timed locking
  CMakeLists.txt
  nano/lib/CMakeLists.txt
  nano/lib/locks.cpp
  nano/lib/locks.hpp
  util/build_prep/bootstrap_boost.sh
Labels: documentation, quality improvements

#2368 Fix non-restarting timer in vote processor log
  nano/node/vote_processor.cpp
Labels: bug

#2372 allow for updated TARGET usage by updating cmake in nano-env:base
  docker/ci/Dockerfile-base
Labels: build-error

#2369 Improve distributed_work stopping with ongoing worker tasks
  nano/core_test/distributed_work.cpp
  nano/lib/work.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/node.cpp
  nano/node/wallet.cpp
Labels: bug

#2370 Vacuum after upgrade
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_env.cpp
  nano/node/lmdb/lmdb_env.hpp
Labels: quality improvements

#2373 Fix link ordering issue in core_test (ubuntu/boost 1.71)
  nano/core_test/CMakeLists.txt
Labels: build-error

#2366 Do not increase pull attempts counter after network errors
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/json_handler.cpp
Labels: bug, rpc nonbreaking change

#2371 Adjust single-hash confirm requests
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/network.cpp
Labels: networking

#2374 regex check for beginning of string -v allowing --vacuum to fall through
  docker/node/entry.sh
Labels: bug, docker

#2362 Lazy bootstrap retry limit
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/node.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: quality improvements, rpc nonbreaking change

#2375 Stop work generation before stopping threads waiting for work
  nano/node/json_handler.cpp
  nano/node/node.cpp
Labels: bug, rpc nonbreaking change

#2377 Add error handling to RPC process without json_block
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug, rpc nonbreaking change
