Repository nanocurrency/nano-node, pull requests merged in 2019-02, with the labels that each got.

#1653 Make nano_wallet for Windows console
  CMakeLists.txt
  appveyor.yml
  nano/nano_wallet/entry_com.cpp
Labels: enhancement

#1681 tsan: fix rpc shutdown acceptor issue
  nano/node/rpc.cpp
Labels: bug, sanitizers

#1683 update beta weights
  rep_weights_beta.bin
Labels: routine, universe

#1680 Create and use new network helper constants
  nano/lib/config.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/entry.cpp
  nano/node/bootstrap.hpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/portmapping.cpp
  nano/node/portmapping.hpp
  nano/node/voting.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/secure/common.cpp
Labels: quality improvements

#1677 Fix our own compiler warnings
  CMakeLists.txt
  nano/core_test/entry.cpp
  nano/core_test/interface.cpp
  nano/core_test/rpc.cpp
  nano/lib/blocks.cpp
  nano/lib/interface.cpp
  nano/lib/numbers.cpp
  nano/lib/timer.hpp
  nano/lib/work.cpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/ipc.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/openclwork.cpp
  nano/node/openclwork.hpp
  nano/node/peers.cpp
  nano/node/rpc.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/wallet.cpp
  nano/secure/common.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#1684 add CLI switch for adjusting Sideband upgrade batch sizes
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#1686 Info.plist generation, out-of-src build support
  CMakeLists.txt
Labels: qt

#1694 Add alarm operations to memory stats RPC
  nano/node/node.cpp
  nano/node/node.hpp
Labels: functionality quality improvements

#1693 Add missing beta/live network helper constants
  nano/node/common.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.hpp
Labels: quality improvements

#1692 Factor out block processor
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1689 CLI to clear online_weight & peers
  nano/node/cli.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/secure/blockstore.hpp
Labels: enhancement

#1696 Build/debug beta
  appveyor.yml
  ci/build-gitlab.sh
Labels: build-error, routine, universe

#1698 Sign windows
  appveyor.yml
Labels: universe

#1699 Configurable timer clock type
  nano/lib/timer.hpp
Labels: enhancement

#1702 Update .gitmodules to reflect branch change for LMDB
  .gitmodules
Labels: routine, universe

#1700 Factor out signature checker
  nano/node/CMakeLists.txt
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/signatures.cpp
  nano/node/signatures.hpp
Labels: enhancement

#1701 Exclude miniupnpc install ()
  CMakeLists.txt
Labels: build-error, quality improvements, routine

#1584 Convert deserializers to use exceptions
  nano/core_test/network.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/errors.hpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/testing.hpp
  nano/secure/blockstore.cpp
  nano/secure/common.cpp
  nano/secure/versioning.cpp
Labels: quality improvements

#1703 Deserializer changes in unchecked_info
  nano/node/node.cpp
  nano/secure/common.cpp
Labels: build-error

#1518 Request confirmation faster for new blocks
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
Labels: functionality quality improvements

#1704 State blocks subtype check for RPC "process"
  nano/core_test/rpc.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/rpc.cpp
Labels: rpc nonbreaking change

#1705 Data race when upgrading sideband information
  nano/node/lmdb.hpp
Labels: bug

#1706 Use cpack to build zip for win
  appveyor.yml
Labels: enhancement, routine, universe

#1710 Appveyor: fix building PRs during CI
  appveyor.yml
Labels: routine, universe

#1709 Update missed rai:: references to nano::
  nano/node/rpc_secure.cpp
Labels: universe

#1708 ipc: Handle rpc actions doing async ops
  nano/node/ipc.cpp
Labels: bug

#1715 Fix uses of lambdas on GCC < 7.1.0
  nano/node/rpc_secure.cpp
Labels: build-error, universe

#1722 Update appveyor.yml
  appveyor.yml
Labels: build-error

#1719 Support both nano_ and rai_ prefixes for unit conversion RPCs
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: rpc nonbreaking change

#1175 adding support for rpm building
  .gitlab-ci.yml
  ci/build-centos.sh
  etc/systemd/nanocurrency-beta.service
  etc/systemd/nanocurrency.service
  nanocurrency-beta.spec.in
  nanocurrency.spec.in
  util/build_prep/centos/prep.sh.in
Labels: enhancement, medium effort remaining

#1724 Cleanup unchecked table after each bootstrap attempt
  nano/core_test/node.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#1713 Only blacklist the TSAN file when using clang compiler
  CMakeLists.txt
  nano/lib/blocks.hpp
Labels: build-error

#1714 Find pthread in CMakeLists.txt
  CMakeLists.txt
Labels: build-error

#1730 Remove unnecessary cast
  nano/node/wallet.cpp
Labels: quality improvements

#1736 block_store.sideband_height test
  nano/core_test/block_store.cpp
Labels: unit test

#1735 Update CLI --debug_validate_blocks to validate sideband data
  nano/nano_node/entry.cpp
Labels: enhancement

#1738 Initialize peer_information members
  nano/node/peers.cpp
  nano/node/peers.hpp
Labels: bug

#1739 Fix reported by TSAN issues
  crypto/ed25519-donna/ed25519-donna-batchverify.h
  nano/core_test/conflicts.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/rpc.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/secure/common.cpp
  nano/slow_test/node.cpp
Labels: quality improvements, sanitizers, unit test

#1720 Update github issue template bug bounty info
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#1741 Fix some asan issues in tests
  nano/core_test/node.cpp
  nano/core_test/rpc.cpp
Labels: unit test

#1743 [ASAN] don't create more wallets in vote_minimum test
  nano/core_test/wallets.cpp
Labels: sanitizers, unit test

#1744 Cli debug online weight
  nano/nano_node/entry.cpp
Labels: documentation, functionality quality improvements

#1742 Respond to keepalive messages within a TCP socket
  nano/core_test/network.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.cpp
  nano/node/common.hpp
Labels: functionality quality improvements

#1745 [ASAN] replace junk data with 0 for peer_put ()
  nano/node/lmdb.cpp
Labels: sanitizers

#1747 Fix ASAN warning caused by global initialization order using CryptoPP functions
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug

#1754 Make confirm_back () non-recursive
  nano/node/node.cpp
  nano/node/node.hpp
Labels: quality improvements

#1759 Remove expect_death test
  nano/core_test/block.cpp
Labels: unit test

#1757 check for legacy directory
  docker/node/Dockerfile
  docker/node/entry.sh
Labels: build-error

#1758 Use a single synchronised random pool across all threads
  nano/core_test/block_store.cpp
  nano/core_test/wallet.cpp
  nano/core_test/work_pool.cpp
  nano/lib/blocks.cpp
  nano/lib/interface.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/lib/work.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/openclwork.cpp
  nano/node/peers.cpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
  nano/qt_system/entry.cpp
  nano/secure/common.cpp
  nano/slow_test/node.cpp
Labels: sanitizers

#1760 Update Live Weights
  rep_weights_live.bin
Labels: routine, universe

#1668 Check if block processor is full in bulk push server
  nano/node/bootstrap.cpp
Labels: experiment

#1732 Improve QT wallet.seed_work_generation test
  nano/qt_test/qt.cpp
Labels: qt, unit test

#1675 Raw support in Qt wallet
  nano/lib/numbers.hpp
  nano/qt/qt.cpp
  nano/qt/qt.hpp
Labels: qt

#1634 Slight OpenCL improvements
  nano/node/openclwork.cpp
Labels: enhancement

#1751 Remove implicitly converted argument
  nano/lib/numbers.cpp
Labels: quality improvements

#1764 Cleanup unused member functions in secure library and various other cleanups
  nano/lib/blocks.cpp
  nano/lib/numbers.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/rpc.hpp
  nano/node/stats.cpp
  nano/secure/blockstore.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
Labels: quality improvements

#1765 Improve block_exists table lookup order
  nano/node/lmdb.cpp
Labels: performance

#1762 Use optimized Argon2 source for all x86_64 builds
  CMakeLists.txt
Labels: enhancement

#1727 RPC unopened
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: enhancement, rpc nonbreaking change

#1718 Return last account restored in RPC wallet_change_seed
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: rpc nonbreaking change

#1766 Add allow_local_peers option for not_a_peer () & reserved_addresses () functions
  nano/core_test/network.cpp
  nano/core_test/rpc.cpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/peers.cpp
  nano/node/peers.hpp
Labels: bug

#1761 Command to generate input to RNG test suites
  nano/nano_node/entry.cpp
Labels: tool

#1772 Add "seed" option to CLI
  nano/node/cli.cpp
Labels: tool

#1767 Display a warning if TSAN/ASAN used together as CMake options
  CMakeLists.txt
Labels: sanitizers

#1777 RPC: Support json literals as block input
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
Labels: rpc nonbreaking change

#1784 Include all representatives with delegated weight in online representatives list
  nano/node/node.cpp
Labels: functionality quality improvements

#1768 RPC config versioning, remove unused options
  nano/core_test/rpc.cpp
  nano/nano_wallet/entry.cpp
  nano/node/daemonconfig.cpp
  nano/node/rpcconfig.cpp
  nano/node/rpcconfig.hpp
Labels: enhancement

#1773 Deprecate `payments_` RPC calls
  nano/node/rpc.cpp
Labels: routine, rpc nonbreaking change

#1774 Add subtype field for state blocks in RPC block_info, blocks_info
  nano/core_test/rpc.cpp
  nano/node/node.cpp
  nano/node/rpc.cpp
Labels: enhancement, rpc nonbreaking change

#1775 Support difficulty for OpenCL generate_work ()
  nano/core_test/work_pool.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/openclwork.cpp
  nano/node/openclwork.hpp
Labels: enhancement

#1787 Capture buffers in io lambdas
  nano/node/node.cpp
Labels: bug

#1789 Time limited logging
  nano/core_test/CMakeLists.txt
  nano/core_test/logger.cpp
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/cli.cpp
  nano/node/ipc.cpp
  nano/node/lmdb.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/openclwork.cpp
  nano/node/portmapping.cpp
  nano/node/rpc.cpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
Labels: quality improvements, tool

#1788 Merge aliases in RPC process_request ()
  nano/node/rpc.cpp
Labels: routine

#1791 Set CI boost min/default to 1.67
  CMakeLists.txt
  appveyor.yml
  docker/ci/Dockerfile
  util/build_prep/bootstrap_boost.sh
  util/build_prep/centos/prep.sh.in
  util/build_prep/macosx/prep.sh.in
  util/build_prep/ubuntu/prep.sh.in
Labels: routine
