Repository nanocurrency/nano-node, pull requests merged in 2019-12, with the labels that each got.

#2424 Fix RPC secure (TLS)
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_connection.hpp
  nano/rpc/rpc_connection_secure.cpp
  nano/rpc/rpc_secure.cpp
Labels: bug

#2388 Allow simultaneous test runs
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ipc.cpp
  nano/core_test/ledger.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/socket.cpp
  nano/core_test/testutil.hpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/qt_system/entry.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: documentation, enhancement, unit test

#2419 Set wallet representative with RPC receive on unopened accounts
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug, documentation, unit test

#2426 Fix rpc_test build
  nano/rpc_test/rpc.cpp
Labels: build-error, unit test

#2414 Add block and voters count in election information
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change, websockets

#2428 Remove raw new operator used with smart pointers
  nano/core_test/bootstrap.cpp
  nano/lib/blocks.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/wallet.cpp
Labels: non-functional change

#2429 Remove representation table during v15 upgrade
  nano/core_test/block_store.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/secure/blockstore_partial.hpp
Labels: bug, database

#2433 Fix qt wallet build on Windows
  nano/nano_wallet/entry_com.cpp
Labels: build-error

#2430 Improve uses of boost multi_index_container
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/repcrawler.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: quality improvements

#2438 Wallet representative counts consistency
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: bug

#2436 Socket buffer size error code
  nano/node/socket.cpp
Labels: quality improvements

#2435 Add CLI command for better LMDB compaction
  nano/node/cli.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/secure/blockstore.hpp
Labels: database, documentation

#2442 Migrate Travis and Appveyor into actions
  .github/workflows/beta_artifacts.yml
  .github/workflows/develop.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/release_test.yml
  .github/workflows/tests.yml
  .travis.yml
  appveyor.yml
  ci/actions/deploy.sh
  ci/actions/linux/deploy-docker.sh
  ci/actions/linux/install_deps.sh
  ci/actions/osx/install_deps.sh
  ci/actions/windows/build.bat
  ci/actions/windows/build.ps1
  ci/actions/windows/configure.bat
  ci/actions/windows/deploy.ps1
  ci/actions/windows/disable_windows_defender.ps1
  ci/actions/windows/install_deps.ps1
  ci/actions/windows/run.bat
  ci/actions/windows/signing.ps1
  ci/build-deploy.sh
  ci/build-travis.sh
Labels: docker, universe

#2443 updates to README badging to reflect changes to actions
  README.md
Labels: universe

#2445 TRAVIS_TAG set for deploy-docker.sh
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  ci/actions/linux/deploy-docker.sh
Labels: build-error, docker

#2450 use commit hash instead of tag for security
  .github/workflows/beta_artifacts.yml
  .github/workflows/develop.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/release_test.yml
  .github/workflows/tests.yml
Labels: universe
