Repository nanocurrency/nano-node, pull requests merged in 2019-04, with the labels that each got.

#1881 tsan: Fix race in repcrawler and remove redundant weight computation
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: sanitizers

#1882 Reduce work.eco_pow intermittent failure rate
  nano/core_test/work_pool.cpp
Labels: quality improvements

#1880 Use asio strands in udp channels
  nano/node/node.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: sanitizers

#1886 Add copying operation to block builder
  nano/core_test/block.cpp
  nano/lib/blockbuilders.cpp
  nano/lib/blockbuilders.hpp
Labels: enhancement

#1887 Fix ASAN warning in wallet.history
  nano/rpc/rpc_handler.cpp
Labels: sanitizers

#1888 Fix ASAN warning in rpc.account_history
  nano/core_test/rpc.cpp
Labels: sanitizers

#1890 Fix ASAN warning for uint128_union.decode_decimal
  nano/lib/numbers.cpp
Labels: sanitizers

#1891 Port config cleanup, allow running tests alongside beta node
  nano/lib/config.hpp
  nano/node/ipcconfig.hpp
  nano/node/websocketconfig.cpp
  nano/node/websocketconfig.hpp
Labels: enhancement

#1889 Remove vote generator delay
  nano/node/voting.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement

#1897 Delete unused rpc.cpp
  nano/node/rpc.cpp
Labels: enhancement

#1902 build.state().from() set build flags
  nano/lib/blockbuilders.cpp
Labels: bug

#1900 Fix vote::to_json()
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug

#1893 Fix TSAN warning with work.eco_pow
  nano/core_test/work_pool.cpp
Labels: sanitizers

#1898 Add callback for confirmed block in RPC block_confirm
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: rpc nonbreaking change

#1904 Remove delay exiting node in request processor
  nano/node/node.cpp
  nano/node/node.hpp
Labels: quality improvements

#1905 Remove strand assert
  nano/node/transport/udp.cpp
Labels: bug

#1851 Unsafe encoding in IPC
  nano/lib/ipc.hpp
  nano/node/ipc.cpp
  nano/node/ipcconfig.cpp
  nano/node/ipcconfig.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc/rpc_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: ipc, rpc nonbreaking change

#1906 Websockets - check for subscriptions before proceeding
  nano/core_test/websocket.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: enhancement

#1885 Create new node ID on each launch & support keepalive with preferred ports
  nano/core_test/block_store.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/cli.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/portmapping.cpp
  nano/node/portmapping.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
Labels: enhancement

#1771 Emit "nano_" prefixed addresses
  nano/core_test/interface.cpp
  nano/core_test/uint256_union.cpp
  nano/core_test/wallet.cpp
  nano/lib/numbers.cpp
Labels: routine, universe

#1907 Websockets - filtering options
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, enhancement, websockets

#1908 Websockets - subscribe to votes
  nano/core_test/websocket.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, enhancement, websockets

#1909 Immediately stop inactive node active_transactions loop
  nano/node/node.cpp
Labels: enhancement

#1903 Add pulls cache for long bootstraps
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: enhancement

#1892 Fix TSAN warning with nano::logger_mt
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/versioning.cpp
  nano/core_test/work_pool.cpp
  nano/lib/logger_mt.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/logging.hpp
  nano/node/node.cpp
  nano/node/openclwork.cpp
  nano/node/openclwork.hpp
  nano/qt_test/qt.cpp
  nano/slow_test/node.cpp
Labels: sanitizers

#1895 Recalculate work from wallet
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: enhancement, functionality quality improvements

#1916 Support Boost v.1.70
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: build-error

#1877 Update confirmation height in another thread
  nano/core_test/network.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/stats.cpp
  nano/node/stats.hpp
  nano/node/wallet.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: documentation, quality improvements

#1913 Websockets - Fix tests breaking with TSAN
  nano/core_test/websocket.cpp
Labels: unit test

#1918 fix tests and update logic of work_watcher::run()
  nano/node/wallet.cpp
Labels: bug, unit test

#1920 Fix confirmation_height.single test
  nano/core_test/network.cpp
Labels: unit test

#1924 Websocket tests: Use error_code when closing
  nano/core_test/websocket.cpp
Labels: unit test

#1912 [TSAN] Protect local_endpoint value with mutex
  nano/node/transport/udp.cpp
Labels: sanitizers

#1926 Activate confirm_req_hashes for beta network
  nano/node/active_transactions.cpp
Labels: enhancement

#1927 Try to fix some version-specific clangformat formatting issues
  nano/nano_node/daemon.cpp
  nano/node/testing.cpp
Labels: enhancement

#1931 Fix some asan rpc issues
  nano/core_test/ipc.cpp
  nano/node/ipc.hpp
  nano/rpc_test/rpc.cpp
Labels: incomplete, sanitizers

#1894 Fix TSAN warning in node.no_voting & wallet.update_work_action
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: sanitizers

#1933 Fix ASAN warning in wallet.history (again)
  nano/node/json_handler.cpp
Labels: sanitizers

#1932 Update conflicts.adjusted_difficulty test
  nano/core_test/conflicts.cpp
  nano/node/active_transactions.cpp
Labels: unit test

#1930 Protect udp_channel members with a mutex
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/node/json_handler.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/qt/qt.cpp
Labels: sanitizers

#1934 Increase request_interval_ms for TSAN/ASAN build
  nano/lib/config.hpp
  nano/node/active_transactions.cpp
Labels: sanitizers, unit test

#1935 TSAN - Fix websocket tests
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: sanitizers

#1936 [TSAN] prevent warnings for confirmation_height.gap_live test
  nano/core_test/network.cpp
Labels: sanitizers

#1937 update weights for beta network
  rep_weights_beta.bin
Labels: routine

#1945 Add nano_rpc to Docker
  docker/node/Dockerfile
Labels: build-error, rpc nonbreaking change

#1946 Update Dockerfile
  docker/node/Dockerfile
Labels: build-error

#1942 Fix our warnings
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/lib/numbers.cpp
  nano/lib/work.cpp
  nano/node/bootstrap.cpp
  nano/node/logging.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/transport/udp.cpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#1941 TSAN suppressions file
  CMakeLists.txt
  tsan_clang_blacklist
  tsan_suppressions
Labels: quality improvements, sanitizers

#1915 Add CLI command for dumping any frontier-unchecked key matches
  nano/nano_node/entry.cpp
Labels: documentation, quality improvements
