Repository nanocurrency/nano-node, pull requests merged in 2019-08, with the labels that each got.

#2174 Extract confirmation height to its own database
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/versioning.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/cli.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb_txn_tracker.cpp
  nano/node/lmdb_txn_tracker.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
  nano/slow_test/node.cpp
Labels: blocker, database

#2189 Fix building error caused by #2151
  nano/node/json_handler.cpp
Labels: bug, build-error

#2193 In http callback, don't log any http responses indicating success as errors
  nano/node/node.cpp
Labels: enhancement

#2191 Use node_ prefix for node ID
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc semantics change

#2154 Prioritize node wallet frontiers during background confirmations
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/wallet.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2195 Add support for election info in websocket confirmations
  nano/core_test/websocket.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2199 Only use -Werror by default with ci
  CMakeLists.txt
  ci/build-travis.sh
Labels: documentation

#2200 Fix rpc.node_id test
  nano/rpc_test/rpc.cpp
Labels: bug

#2196 Process wallet blocks outside of block processor queue
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
Labels: beta testing wanted, enhancement

#2206 Add test for retrieving non-existing account
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore_partial.hpp
Labels: bug, unit test

#2160 Update entry script
  docker/node/Dockerfile
  docker/node/entry.sh
Labels: docker, documentation, universe

#2207 Beta reset with new genesis and lower work threshold
  nano/core_test/difficulty.cpp
  nano/lib/config.hpp
  nano/node/nodeconfig.cpp
  nano/secure/CMakeLists.txt
  nano/secure/common.cpp
  rep_weights_beta.bin
Labels: beta testing wanted, enhancement

#2183 Fix lazy bootstrap balances insert
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: bug

#2209 Increase lifetime of temporary rep variable
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: bug

#2168 RPC publish optional work_watch flag to add to work_watcher
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap.cpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/wallet.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: beta testing wanted, bug, documentation, rpc semantics change

#2204 Travis/artifacts to s3
  .travis.yml
  CMakeLists.txt
  ci/build-deploy.sh
  ci/build-travis.sh
  ci/deploy-docker.sh
  ci/deploy-travis.sh
  docker/node/Dockerfile
  nano/core_test/CMakeLists.txt
  nano/lib/config.hpp
  nano/nano_node/CMakeLists.txt
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_rpc/CMakeLists.txt
  nano/nano_rpc/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/qt/qt.cpp
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/rpc.cpp
Labels: docker, enhancement, tool, universe

#2203 Simplify vote generator logic with a dual sleep
  nano/core_test/node.cpp
  nano/core_test/wallets.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: performance, toml

#2201 Deprecate nano- and xrb- address support
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#2212 Add mdb database test from v14 to v15
  nano/core_test/block_store.cpp
Labels: unit test

#2213 Make some changes suggested from cppcheck
  nano/core_test/block.cpp
  nano/core_test/difficulty.cpp
  nano/core_test/entry.cpp
  nano/core_test/memory_pool.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/work_pool.cpp
  nano/lib/ipc_client.cpp
  nano/lib/numbers.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/lib/utility.cpp
  nano/load_test/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/cli.cpp
  nano/node/common.cpp
  nano/node/ipc.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/testing.cpp
  nano/node/websocket.cpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: non-functional change

#2198 Provide optional automatic ledger/wallet backups before an upgrade
  nano/core_test/block_store.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: documentation, enhancement, toml

#2214 Config option for single line logging records
  nano/core_test/logger.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/election.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: enhancement, toml

#2215 Add counter in stats for number of incoming blocks dropped
  nano/node/network.cpp
Labels: enhancement

#2216 Throttled received block for bootstrap
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: enhancement

#2219 Fix failing slow_tests
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/slow_test/node.cpp
Labels: unit test

#2223 Remove landing store
  nano/node/testing.cpp
  nano/node/testing.hpp
Labels: non-functional change

#2220 Improve throttled received block for bootstrap
  nano/node/bootstrap.cpp
Labels: bug, enhancement

#2227 Set application/json as header content type for work peer requests
  nano/node/node.cpp
Labels: bug

#2222 Configurable work watcher period
  nano/core_test/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
Labels: documentation, enhancement, toml

#2231 Reduce time holding read transaction in vote processor
  nano/node/vote_processor.cpp
Labels: quality improvements

#2234 Fix TSAN error in adjusted difficulty test
  nano/core_test/active_transactions.cpp
Labels: sanitizers, unit test

#2232 Allow Cmake AVX2 builds for Windows
  CMakeLists.txt
Labels: quality improvements

#2235 Enforce upper case for hashes/signatures string output
  nano/lib/numbers.cpp
Labels: quality improvements

#1264 No write transactions on I/O threads
  nano/core_test/CMakeLists.txt
  nano/core_test/utility.cpp
  nano/core_test/wallet.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.cpp
Labels: quality improvements

#2229 Simplify process_loop log timing by using nano::timer
  nano/node/vote_processor.cpp
Labels: non-functional change

#2230 Distibuted work fixes
  nano/lib/work.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug, quality improvements

#2241 Docker changes for new TOML config
  docker/node/config/beta.json
  docker/node/config/beta_rpc.json
  docker/node/config/config-node.toml
  docker/node/config/config-rpc.toml
  docker/node/config/live.json
  docker/node/config/live_rpc.json
  docker/node/config/test.json
  docker/node/entry.sh
Labels: documentation, routine, toml

#2236 Start frontiers confirmation after initial bootstrap
  nano/node/active_transactions.cpp
Labels: enhancement

#2243 update beta network header_magic_number to finalize beta network reset
  nano/secure/common.cpp
Labels: beta testing wanted, routine

#2245 No required options in TOML parsing
  nano/core_test/toml.cpp
  nano/lib/rpcconfig.cpp
  nano/node/websocketconfig.cpp
Labels: bug, toml

#2218 Use max config difficulty internally
  nano/core_test/toml.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/node_rpc_config.cpp
  nano/node/node_rpc_config.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, toml

#2248 Use defaults for amounts in toml
  nano/node/nodeconfig.cpp
Labels: bug, toml

#2250 Lambda formatting that works across clang-format versions
  nano/node/node.cpp
Labels: build-error

#2244 Fixes account_history RPC to include receive blocks when filtering accounts.
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: api semantics change, bug, documentation

#2251 Fix some time-related configs being overriden with 0
  nano/node/logging.cpp
  nano/node/nodeconfig.cpp
Labels: bug, toml

#2249 Update weights following beta refresh distribution
  ci/record_rep_weights.py
  rep_weights_beta.bin
Labels: routine

#2175 Add frontiers confirmation modes
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/node/active_transactions.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: documentation, enhancement, toml

#2246 Move protocol versions to network_params
  nano/core_test/ledger.cpp
  nano/core_test/message.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/voting.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: non-functional change

#2252 Extend toml default-configs test
  nano/core_test/toml.cpp
  nano/node/nodeconfig.cpp
Labels: toml

#2247 Enhancements to OpenCL work handling
  nano/core_test/work_pool.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/openclwork.cpp
  nano/node/openclwork.hpp
Labels: blocker, quality improvements

#2228 Watch blocks separately in work watcher
  nano/core_test/wallet.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, functionality quality improvements

#2256 Post to worker thread in qt wallet when doing write tx's on io threads
  nano/qt/qt.cpp
Labels: qt

#2197 Adds RocksDB support
  CMakeLists.txt
  ci/build-travis.sh
  ci/test.sh
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
  nano/core_test/CMakeLists.txt
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/rocksdb_test.cpp
  nano/core_test/socket.cpp
  nano/core_test/utility.cpp
  nano/core_test/wallets.cpp
  nano/lib/CMakeLists.txt
  nano/lib/diagnosticsconfig.cpp
  nano/lib/diagnosticsconfig.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/cli.cpp
  nano/node/cli.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_iterator.hpp
  nano/node/rocksdb/rocksdb_txn.cpp
  nano/node/rocksdb/rocksdb_txn.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: database, documentation, enhancement

#2217 Cache rep weights
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/lib/CMakeLists.txt
  nano/lib/rep_weights.cpp
  nano/lib/rep_weights.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/testing.cpp
  nano/node/vote_processor.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: database, performance

#2258 No longer need enable_control when getting the cemented count
  nano/node/json_handler.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#2259 Cache cemented count
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/socket.cpp
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/qt_test/qt.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: performance

#2255 Distributed work refactor
  nano/core_test/CMakeLists.txt
  nano/core_test/distributed_work.cpp
  nano/core_test/wallet.cpp
  nano/node/CMakeLists.txt
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/node_observers.cpp
  nano/node/node_observers.hpp
  nano/node/rocksdb/rocksdb_txn.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#2261 Set USE_RTTI before building RocksDB in docker
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
Labels: build-error

#2257 Prevent dropping of unchecked on restart if node is not synchronized
  nano/core_test/block_store.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/secure/blockstore.hpp
Labels: quality improvements

#2240 Wrap boost::asio::async_write to ensure lifetime of buffers
  ci/build-travis.sh
  nano/core_test/ipc.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/socket.cpp
  nano/lib/CMakeLists.txt
  nano/lib/asio.cpp
  nano/lib/asio.hpp
  nano/lib/ipc_client.cpp
  nano/lib/ipc_client.hpp
  nano/lib/utility.hpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.hpp
  nano/node/ipc.cpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_request_processor.cpp
  nano/rpc/rpc_request_processor.hpp
Labels: quality improvements

#2264 Non-blocking work watcher loop
  nano/core_test/difficulty.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/wallet.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: bug, sanitizers

#2263 Prevent supurious wakeup in active transactions request loop
  nano/core_test/distributed_work.cpp
  nano/core_test/wallet.cpp
  nano/lib/utility.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
  nano/node/network.cpp
  nano/node/vote_processor.cpp
  nano/node/voting.cpp
Labels: bug

#2260 Prevent adjusted difficulty overflow for extremly high or low difficulty
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
Labels: quality improvements
