Repository nanocurrency/nano-node, pull requests merged in 2019-03, with the labels that each got.

#1785 Don't output useless log file entries
  nano/node/bootstrap.cpp
  nano/node/node.cpp
Labels: quality improvements

#1779 Return error message for failed async RPC actions
  nano/node/rpc.cpp
Labels: rpc nonbreaking change

#1796 Replace nested if/else with map for no argument rpc_handler functions
  nano/node/rpc.cpp
Labels: quality improvements

#1797 Fix intermittent select_account test failure
  nano/qt_test/qt.cpp
Labels: unit test

#1770 Add confirmation height
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/rpc.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallets.cpp
  nano/node/blockprocessor.cpp
  nano/node/cli.cpp
  nano/node/common.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/testing.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
Labels: documentation, enhancement, functionality quality improvements, rpc nonbreaking change, tool

#1805 Improve Boost download links in bootstrap_boost.sh
  util/build_prep/bootstrap_boost.sh
Labels: build-error

#1803 Improve representative crawler
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/node/CMakeLists.txt
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/rpc.cpp
Labels: enhancement

#1800 Improve CLI --wallet_import
  nano/node/cli.cpp
Labels: quality improvements

#1798 Support difficulty for RPC "work_generate"
  nano/core_test/rpc.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/node.cpp
  nano/node/rpc.cpp
Labels: enhancement, rpc nonbreaking change

#1802 Make wallet.multithreaded_send slow test async
  nano/slow_test/node.cpp
Labels: unit test

#1806 Require standard layout in mdb_val
  nano/node/lmdb.cpp
Labels: enhancement

#1807 Use to_bytes in bootstrap as well
  nano/node/bootstrap.cpp
Labels: enhancement

#1811 Output error if lmdb env cannot be opened
  nano/node/lmdb.cpp
Labels: enhancement

#1812 Add optional difficulty in RPC "work_validate"
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: rpc nonbreaking change

#1801 Confirmation height enhancement
  nano/core_test/node.cpp
  nano/core_test/rpc.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/wallet.cpp
Labels: enhancement

#1748 RPC pending - sort by amount
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: enhancement, rpc nonbreaking change

#1729 Network selector
  gtest/src/gtest_main.cc
  nano/core_test/block_store.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/testutil.hpp
  nano/core_test/uint256_union.cpp
  nano/core_test/work_pool.cpp
  nano/lib/CMakeLists.txt
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/errors.hpp
  nano/lib/interface.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/cli.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
  nano/node/portmapping.cpp
  nano/node/portmapping.hpp
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/rpcconfig.cpp
  nano/node/rpcconfig.hpp
  nano/node/testing.cpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/qt_system/entry.cpp
  nano/qt_test/entry.cpp
  nano/secure/CMakeLists.txt
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/secure/utility.cpp
  nano/secure/utility.hpp
  nano/slow_test/node.cpp
Labels: enhancement

#1818 missed instances of nano::work_pool::publish_threshold
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: build-error

#1817 Log wallet lock/unlock
  nano/node/rpc.cpp
  nano/node/wallet.cpp
  nano/qt/qt.cpp
Labels: enhancement

#1816 Add required stake to confirmation_quorum
  nano/node/rpc.cpp
Labels: rpc nonbreaking change

#1790 Add TCP server timeout
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#1819 RPC 100-continue and max request size
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/rpcconfig.cpp
  nano/node/rpcconfig.hpp
Labels: rpc nonbreaking change

#1815 Start elections for all forks of unconfirmed blocks
  nano/node/blockprocessor.cpp
Labels: enhancement

#1814 Valgrind fixes & suppressions
  nano/core_test/logger.cpp
  nano/core_test/network.cpp
  nano/core_test/rpc.cpp
  nano/core_test/wallets.cpp
  nano/node/logging.hpp
  nano/node/node.cpp
  nano/secure/ledger.hpp
  valgrind.supp
Labels: sanitizers

#1355 RPC Account history filter
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: awaiting response, enhancement

#1828 Externally connect to the tcp socket
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: enhancement

#1829 Clean up and simplify calls to get buffers to messages.
  nano/core_test/network.cpp
  nano/node/bootstrap.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1804 RPC accounts_pending - sort by amount
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: documentation, enhancement, rpc nonbreaking change

#1834 Renaming udp_buffer to message_buffer
  nano/core_test/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1835 Separating the concepts of:
  nano/core_test/peer_container.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
  nano/qt_test/qt.cpp
Labels: enhancement

#1836 Moving network sizing functions
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/rpc.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.hpp
  nano/node/testing.cpp
  nano/qt/qt.cpp
Labels: enhancement

#1841 Fix assert assignment for Debug builds
  nano/node/lmdb.cpp
Labels: bug

#1822 RPC account_history add block height and optional reverse
  nano/core_test/rpc.cpp
  nano/node/rpc.cpp
Labels: documentation, enhancement

#1837 Add the concept of message channels to the node.
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/rpc.cpp
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/peers.cpp
  nano/node/peers.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/rpc.cpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/voting.cpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/slow_test/node.cpp
Labels: enhancement

#1830 Add difficulty limit for RPC "work_generate" in config.json
  nano/core_test/rpc.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/rpc.cpp
  nano/node/rpcconfig.cpp
  nano/node/rpcconfig.hpp
Labels: documentation, enhancement, rpc nonbreaking change

#1810 Use adjusted difficulty for trees in active transactions
  nano/core_test/conflicts.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: functionality quality improvements

#1848 rpc.online_reps test udpate
  nano/core_test/rpc.cpp
Labels: incomplete, unit test

#1842 Allow block_processor variables tuning with launch flags
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#1821 Periodically check for unconfirmed frontiers and start elections
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/rpc.cpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement

#1852 Fix active_transactions/signature checker initialization order
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#1840 Websocket support
  nano/core_test/CMakeLists.txt
  nano/core_test/websocket.cpp
  nano/node/CMakeLists.txt
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/node/websocketconfig.cpp
  nano/node/websocketconfig.hpp
Labels: enhancement

#1850 Fix race in tcp_listener_timeout_keepalive
  nano/core_test/network.cpp
Labels: unit test

#1854 Reinstate preconfigured keepalives
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/repcrawler.cpp
Labels: enhancement

#1849 qualified_root type alias
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/numbers.hpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: non-functional change

#1859 Extend lifetime of size response in rpc handler
  nano/node/ipc.cpp
Labels: bug

#1786 Use the error code overloads for socket shutdown/close
  nano/node/bootstrap.cpp
  nano/node/stats.hpp
Labels: functionality quality improvements

#1855 Generalize installer path
  CMakeLists.txt
Labels: build-error

#1846 clang for travis
  .travis.yml
  ci/deploy-docker.sh
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
Labels: build-error, enhancement

#1863 Various minor coding style updates
  nano/lib/numbers.hpp
  nano/lib/plat/darwin/thread_role.cpp
  nano/lib/plat/freebsd/thread_role.cpp
  nano/lib/plat/linux/thread_role.cpp
  nano/lib/plat/windows/priority.cpp
  nano/lib/plat/windows/thread_role.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/lib/work.hpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/stats.cpp
  nano/node/stats.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/transport/udp.hpp
  nano/node/voting.hpp
  nano/node/wallet.hpp
  nano/node/websocketconfig.hpp
  nano/node/xorshift.hpp
  nano/secure/blockstore.hpp
  nano/secure/common.hpp
  nano/secure/ledger.hpp
  nano/secure/versioning.hpp
Labels: quality improvements

#1861 Some improvements to load tester script
  load-tester/src/main.rs
Labels: tool

#1864 Fix missed enum in switch
  nano/node/stats.cpp
Labels: build-error

#1734 Ability to limit CPU rate for POW
  nano/core_test/node.cpp
  nano/core_test/work_pool.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/testing.cpp
Labels: functionality quality improvements, tool

#1843 Support sending decimals from QT wallet
  nano/core_test/uint256_union.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
Labels: enhancement

#1866 Replace assert with null-check during nodeid handshake
  nano/node/transport/udp.cpp
Labels: bug

#1867 Remove circular dependency between secure <-> lib libraries
  nano/core_test/core_test_main.cc
  nano/core_test/rpc.cpp
  nano/core_test/work_pool.cpp
  nano/lib/blockbuilders.cpp
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/interface.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/portmapping.cpp
  nano/node/rpc.cpp
  nano/node/rpcconfig.cpp
  nano/node/rpcconfig.hpp
  nano/node/transport/udp.cpp
  nano/node/wallet.cpp
  nano/qt/qt.cpp
  nano/qt_system/entry.cpp
  nano/qt_test/entry.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/utility.cpp
Labels: quality improvements

#1870 Remove ed25519 and lib library circular dependency
  CMakeLists.txt
  nano/core_test/block_store.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/core_test/work_pool.cpp
  nano/crypto_lib/CMakeLists.txt
  nano/crypto_lib/interface.cpp
  nano/crypto_lib/random_pool.cpp
  nano/crypto_lib/random_pool.hpp
  nano/lib/CMakeLists.txt
  nano/lib/blocks.cpp
  nano/lib/interface.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/lib/work.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/openclwork.cpp
  nano/node/testing.cpp
  nano/node/transport/udp.cpp
  nano/node/wallet.cpp
  nano/qt_system/entry.cpp
  nano/secure/CMakeLists.txt
  nano/secure/common.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#1868 Fix secure rpc build
  nano/node/rpc.cpp
  nano/node/rpc.hpp
  nano/node/rpc_secure.cpp
  nano/node/rpc_secure.hpp
Labels: build-error

#1873 TSAN: fix races in udp channels
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: sanitizers

#1876 Fix lock ordering issue in udp_channels
  nano/node/transport/udp.cpp
Labels: bug

#1858 Trending active_transactions difficulty for an average
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/rpc.cpp
  nano/rpc/rpc_handler.hpp
Labels: enhancement, quality improvements, rpc nonbreaking change, unit test
