Repository nanocurrency/nano-node, pull requests merged in 2019-06, with the labels that each got.

#2050 Fix deadlock in tests (Continued)
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
Labels: unit test

#2047 Use a pool allocator for shared_ptrs with blocks, elections and votes
  nano/core_test/CMakeLists.txt
  nano/core_test/core_test_main.cc
  nano/core_test/memory_pool.cpp
  nano/core_test/message.cpp
  nano/core_test/node.cpp
  nano/lib/CMakeLists.txt
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/memory.cpp
  nano/lib/memory.hpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/logging.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/qt_system/entry.cpp
  nano/qt_test/entry.cpp
  nano/rpc_test/entry.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/entry.cpp
Labels: performance

#2048 Don't escalate confirmed previous/source for elections
  nano/node/active_transactions.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/node.cpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#2053 Handle accounts which have the same number of uncemented blocks when prioritizing frontiers
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: bug

#2045 Attempt to start TCP connections to known UDP peers
  nano/node/network.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/secure/common.hpp
Labels: enhancement

#2052 Ledger tests related to epoch conflicts
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
Labels: unit test

#2057 Reduce lock time in UDP ongoing keepalive
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
Labels: performance

#2049 Configurable confirmation history container
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, enhancement

#2014 Add threshold optional to RPC unopened and ledger
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#1950 Add blocks_not_found in RPC blocks_info response rather than an error
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc nonbreaking change

#2059 Use a convenient global instead of passing use_memory_pools explicitly
  nano/core_test/memory_pool.cpp
  nano/core_test/message.cpp
  nano/core_test/node.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/memory.cpp
  nano/lib/memory.hpp
  nano/load_test/entry.cpp
  nano/nano_node/daemon.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/rpc_test/entry.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug, quality improvements

#2058 Add active container observer
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/lmdb.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/node_observers.cpp
  nano/node/node_observers.hpp
  nano/node/payment_observer_processor.cpp
  nano/qt/qt.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
Labels: enhancement

#2060 TSAN error for send_node_id_handshake test
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: sanitizers

#2064 Consistently send TCP keepalives
  nano/node/network.cpp
  nano/node/network.hpp
Labels: networking

#2062 Limit socket queue_size
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
Labels: networking

#1953 Print info about network and path, when running daemon
  nano/nano_node/daemon.cpp
  nano/node/node.cpp
  nano/qt/qt.cpp
Labels: documentation

#2051 active_transaction.roots bounding by config instead of confirmation rate
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, functionality quality improvements

#2056 Make announcement_long delay 2 rounds
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: enhancement

#2063 Add launch flag --disable_udp
  nano/nano_node/entry.cpp
  nano/node/network.cpp
  nano/node/nodeconfig.hpp
  nano/node/transport/tcp.cpp
Labels: enhancement

#2066 Websocket/extended confirmation support
  nano/core_test/websocket.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2070 Factor out online_reps and gap_cache
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
Labels: non-functional change

#2055 Check if existing block is already confirmed in active_transactions add
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: unit test

#2069 Use correct index when iterating prioritized frontiers
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/slow_test/node.cpp
Labels: bug, quality improvements

#2071 Fix assorted compiler warnings
  nano/core_test/websocket.cpp
  nano/nano_rpc/entry.cpp
  nano/node/daemonconfig.cpp
  nano/node/election.cpp
  nano/node/logging.cpp
  nano/node/node.cpp
Labels: non-functional change

#2061 Fix TSAN error with work_watcher
  nano/node/wallet.cpp
Labels: sanitizers

#2067 Disable memory pools when running on Mac
  nano/core_test/memory_pool.cpp
  nano/lib/memory.cpp
  nano/lib/memory.hpp
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
  nano/rpc_test/entry.cpp
Labels: help wanted, sanitizers

#2073 [Valgrind] Increase deadline timer in the rpc.simultaneous_calls test to account for valgrind slowness
  nano/rpc_test/rpc.cpp
Labels: sanitizers

#2018 Capture SIGINT and SIGTERM to clean up sockets
  nano/load_test/entry.cpp
  nano/nano_node/daemon.cpp
  nano/nano_rpc/entry.cpp
  nano/secure/utility.cpp
  nano/secure/utility.hpp
Labels: functionality quality improvements

#2074 Fix ASAN issue in ws unit tests
  nano/core_test/websocket.cpp
Labels: sanitizers, unit test

#2035 Bandwidth limiting
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/bootstrap.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/vote_processor.cpp
Labels: documentation, networking, protocol feature

#2079 Move WebSocket confirmation_type into message
  nano/node/websocket.cpp
Labels: documentation, websockets

#2081 Provide test for WS topic election_stopped and fix bad topic/content
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
Labels: bug, unit test, websockets

#2082 Prevent multiple observer calls for confirmed block
  nano/core_test/network.cpp
  nano/node/confirmation_height_processor.cpp
Labels: bug

#2076 Don't start confirm_frontiers () if elections count > active_elections_size
  nano/node/active_transactions.cpp
Labels: quality improvements

#2085 Use node_flags for delay_frontier_confirmation_height_updating
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: unit test

#2075 Remove copies of blocks container from network::flood_block_batch
  nano/node/active_transactions.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
Labels: performance

#2086 Update slow_test
  nano/node/blockprocessor.cpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: unit test

#2088 Fix duplicate iterating in conf height processor with self and circular sends
  nano/core_test/network.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/node.cpp
Labels: bug

#2090 Optional include_trend for RPC active_difficulty
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: rpc nonbreaking change

#2094 Formatting issues on master
  nano/node/bootstrap.cpp
Labels: build-error

#2097 TCP: Don't connect to or log invalid peers
  nano/node/socket.cpp
  nano/node/transport/tcp.cpp
Labels: networking

#2099 Add ability to clear stats from Qt wallet
  nano/qt/qt.cpp
  nano/qt/qt.hpp
Labels: qt

#2089 Add optional cemented count to block_count RPC command
  nano/core_test/block_store.cpp
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/testing.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc/rpc_handler.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
Labels: rpc nonbreaking change

#2100 Add observer stats for confirmations
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/node.cpp
Labels: enhancement

#2102 Fix locking issue and intermittent failure in rpc.active_difficulty
  nano/rpc_test/rpc.cpp
Labels: unit test

#2077 Use the MDB_NOMEMINIT flag with the ledger db environment
  nano/node/lmdb.cpp
  nano/node/lmdb.hpp
  nano/node/wallet.cpp
  valgrind/valgrind.h
Labels: performance

#2103 Flag to disable TCP realtime network
  nano/core_test/node.cpp
  nano/nano_node/entry.cpp
  nano/node/bootstrap.cpp
  nano/node/network.cpp
  nano/node/nodeconfig.hpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
Labels: networking

#2105 Improve batching multiple blocks pending confirmation height processing
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/write_database_queue.cpp
  nano/node/write_database_queue.hpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, quality improvements

#2107 Minor Readme file updates
  README.md
Labels: documentation

#2108 Fix intermittent test issue and cleanup unused vars
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
Labels: enhancement

#2095 Fix vote_generator loop inconsistency during high load
  nano/core_test/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: performance

#2091 Web socket subscription for active difficulty
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/node.cpp
  nano/node/node_observers.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2109 Always notify on active difficulty updates
  nano/node/active_transactions.cpp
Labels: websockets

#2087 Bidirectional TCP sockets
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap.cpp
  nano/node/bootstrap.hpp
  nano/node/json_handler.cpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/qt/qt.cpp
Labels: enhancement, networking
