Repository nanocurrency/nano-node, pull requests merged in 2019-11, with the labels that each got.

#2380 RPC block_create fixes
  nano/node/json_handler.cpp
Labels: bug

#2381 Target osx 10.12 deployment
  CMakeLists.txt
Labels: build-error

#2382 Fix lazy mutex unlock via mutex
  nano/node/bootstrap/bootstrap.cpp
Labels: bug

#2383 Add mutex lock to RPC bootstrap_status
  nano/node/json_handler.cpp
Labels: bug

#2378 [ASAN] memory leak between tcp channels and sockets
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/socket.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: sanitizers

#2384 [Valgrind] Uninitialized memory in distributed_work.no_peers test
  nano/core_test/distributed_work.cpp
Labels: sanitizers, unit test

#2387 Fix early return preventing mutex lock in attempt_restart_check
  nano/node/bootstrap/bootstrap.cpp
Labels: bug

#2390 Incorrect total memtable size used with RocksDB
  nano/node/rocksdb/rocksdb.cpp
Labels: bug, database

#2386 Prevent concurrent bootstrap populate_connections ()
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
Labels: bug

#2393 [TSAN] Data race in active_difficulty.recalculate_work test
  nano/core_test/node.cpp
Labels: unit test

#2391 use cached build artifacts
  .travis.yml
  ci/build-deploy.sh
  ci/build-travis.sh
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-gcc
  util/build_prep/fetch_boost.sh
  util/build_prep/fetch_rocksdb.sh
  util/build_prep/macosx/build_qt.sh
Labels: docker, universe

#2389 [Valgrind] Various uninitialized data accesses
  nano/core_test/websocket.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
Labels: sanitizers

#2392 Fix occasional failures for core_test.distributed_work* tests
  nano/core_test/distributed_work.cpp
Labels: unit test

#2394 Improve bootstrap frontiers confirmation
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/repcrawler.cpp
Labels: enhancement, rpc nonbreaking change, unit test

#2395 update dockerfile to use cached rocksdb
  docker/node/Dockerfile
Labels: build-error, docker

#2396 Updates to TOML generated docs
  nano/lib/rpcconfig.cpp
  nano/node/cli.cpp
Labels: non-functional change

#2401 Warn if control is enabled with non-local bind address
  nano/rpc/rpc.cpp
Labels: non-functional change

#2397 [ASAN] UPNP url memory leak
  nano/node/portmapping.cpp
Labels: sanitizers

#2400 Improve bootstrap for accounts with public key = existing block hash
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
Labels: enhancement

#2402 Node id handshake container not protected during push
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: bug

#2404 Update live bootstrap_weights
  rep_weights_live.bin
Labels: routine

#2405 Fix jumping peer stake total
  nano/node/common.cpp
  nano/node/common.hpp
Labels: bug

#2411 Fix active_transactions not doing any confirmation request in tests
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
Labels: unit test

#2398 Improve block deletion and RocksDB deletion in general
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: database, performance

#2412 Fix work_cache_blocking logging bug
  nano/node/wallet.cpp
Labels: bug

#2413 Fix distributed_work segfault when local work generation fails
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
Labels: bug

#2420 Add database vendor string to RPC version
  nano/nano_node/daemon.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
Labels: documentation, rpc nonbreaking change
