Repository nanocurrency/nano-node, pull requests merged in 2020-07, with the labels that each got.

#2832 Set default bootstrap initiator threads to 1
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: configuration default change, documentation

#2831 Fix TCP message manager not notifying producers
  nano/core_test/network.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: bug

#2833 Unresolved forks during initial bootstrap
  nano/core_test/bootstrap.cpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug

#2828 Invoke callbacks even during socket closures
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.cpp
Labels: bug

#2838 Fix secure RPC build on msvc
  nano/rpc/rpc_connection_secure.cpp
  nano/rpc/rpc_secure.cpp
Labels: build-error

#2837 UPnP existing lease and other misc enhancements
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/portmapping.cpp
  nano/node/portmapping.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug, enhancement

#2839 UPnP basic logging messages are more frequent than intended
  nano/node/portmapping.cpp
Labels: logging

#2843 Change node_id from hash to account in telemetry RPC/websocket
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/node/common.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc, semantic

#2840 Different log when the OpenCL library cannot be loaded
  nano/core_test/work_pool.cpp
  nano/node/openclwork.cpp
  nano/node/openclwork.hpp
  nano/node/plat/posix/openclapi.cpp
  nano/node/plat/windows/openclapi.cpp
Labels: logging

#2842 Specify OpenCL clCreateBuffer() flags
  nano/node/openclwork.cpp
Labels: quality improvements

#2685 Improve mutex handling when generating stacktraces with NANO_TIMED_LOCKS/txn tracker
  CMakeLists.txt
  nano/lib/locks.cpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/rpc_test/rpc.cpp
Labels: cli, documentation, quality improvements

#2756 Use block cache from unbounded processor when checking if block is processing
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
Labels: quality improvements

#2681 Add ASIO completion handler tracking
  CMakeLists.txt
  nano/lib/threading.cpp
  nano/node/testing.cpp
Labels: debug, documentation, tool

#2844 Add time retrieval latency profile to CLI diagnostics
  nano/node/cli.cpp
Labels: debug

#2835 Allow unescaped quoted strings with --config CLI
  nano/core_test/cli.cpp
  nano/lib/CMakeLists.txt
  nano/lib/cli.cpp
  nano/lib/cli.hpp
  nano/nano_node/entry.cpp
  nano/nano_rpc/entry.cpp
  nano/node/cli.cpp
Labels: cli, documentation, enhancement

#2855 Simplify RocksDB config options
  nano/core_test/toml.cpp
  nano/lib/rocksdbconfig.cpp
  nano/lib/rocksdbconfig.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
Labels: removal, toml

#2829 Merge block databases
  nano/core_test/block_store.cpp
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/testing.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: blocker, database, documentation, nanodb structure, performance, removal, rpc

#2679 Make std::condition_variable::wait* compatible with NANO_TIMED_LOCKS
  ci/build-travis.sh
  nano/core_test/locks.cpp
  nano/lib/locks.cpp
  nano/lib/locks.hpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/state_block_signature_verification.cpp
Labels: quality improvements

#2859 extend test retry deadline 12/31/2020 23:59:59 UTC
  ci/test.sh
Labels: routine, unit test, universe

#2827 Local votes history to replace votes cache
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/voting.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: blocker, quality improvements

#2862 Don't crash using read-only CLI command with no ledger
  nano/core_test/node.cpp
  nano/node/node.cpp
Labels: bug
