Repository nanocurrency/nano-node, pull requests merged in 2020-10, with the labels that each got.

#2978 [Pruning] Support pruned blocks in confirmation height processor & active transactions
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_unbounded.cpp
Labels: enhancement

#2977 [Pruning] Support pruned chains in RPC & QT wallet
  nano/node/json_handler.cpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
Labels: breaking, documentation, enhancement, rpc

#2974 [Pruning] Accept pruned-related blocks in blocks processing & rollback
  nano/core_test/ledger.cpp
  nano/secure/ledger.cpp
Labels: blocker, enhancement

#2969 Fix link to contributors guide
  README.md
Labels: documentation, routine

#2992 [Pruning] Wallet receive action & search pending for pruned blocks
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/active_transactions.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
Labels: enhancement

#2997 Fix repcrawler loopback channel guard
  nano/node/repcrawler.cpp
Labels: bug

#2998 Rollback messages config
  nano/node/blockprocessor.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: logging

#2995 Make entry.sh more portable by removing all bashisms
  docker/node/Dockerfile
  docker/node/entry.sh
Labels: docker, tool

#2991 Avoid locking the work_watcher mutex in the request_confirm loop
  nano/core_test/CMakeLists.txt
  nano/core_test/wallet.cpp
  nano/core_test/work_watcher.cpp
  nano/node/active_transactions.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: performance

#2976 [Pruning] Support pruned blocks in bootstrap actions
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/gap_cache.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement

#2820 Using post-processing events for all operations
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
Labels: performance

#3006 Remove Guilherme's pubkey from security policy
  SECURITY.md
Labels: routine

#3000 add test network to build artifacts for non DB tags
  .github/workflows/test_network_artifacts.yml
  CMakeLists.txt
  Info.plist.in
  ci/actions/deploy.sh
  ci/actions/linux/deploy-docker.sh
  ci/actions/windows/build.ps1
  ci/build-deploy.sh
  debian-control/postinst.in
  debian-control/postrm.in
  etc/systemd/nanocurrency-beta.service
  etc/systemd/nanocurrency-test.service
  etc/systemd/nanocurrency.service
  nano/ipc_flatbuffers_lib/CMakeLists.txt
Labels: docker, routine, universe

#3013 Add pruned node to maker
  nano/core_test/telemetry.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/test_common/telemetry.cpp
Labels: telemetry

#2979 Migrate LMDB database to RocksDB with new CLI command
  nano/core_test/ledger.cpp
  nano/node/cli.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_txn.cpp
  nano/node/rocksdb/rocksdb_txn.hpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: cli, documentation, enhancement

#3015 Remove payment RPC
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/CMakeLists.txt
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/json_payment_observer.cpp
  nano/node/json_payment_observer.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/payment_observer_processor.cpp
  nano/node/payment_observer_processor.hpp
  nano/rpc_test/rpc.cpp
Labels: breaking, documentation, rpc

#3020 Properly initialize array of atomics in ws server
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: bug

#3019 Enable OpenCL on macOS
  nano/node/openclwork.cpp
Labels: bug

#3005 Adding plist files to ignore filter.
  .gitignore
Labels: routine

#2925 Election mutexes to remove heavy active mutex contention
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/frontiers_confirmation.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
Labels: performance, quality improvements

#2879 Packed timestamp
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/timestamp.cpp
  nano/core_test/vote_processor.cpp
  nano/lib/CMakeLists.txt
  nano/lib/timestamp.cpp
  nano/lib/timestamp.hpp
  nano/lib/timestamp_fwd.hpp
  nano/lib/utility.hpp
  nano/node/active_transactions.cpp
  nano/node/cli.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/repcrawler.cpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/vote_processor.cpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: documentation, enhancement

#2996 Erase dropped forks from the duplicate filter
  nano/core_test/active_transactions.cpp
  nano/node/election.cpp
Labels: functionality quality improvements

#3022 Add include_only_confirmed to account_balance & account_info
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: documentation, rpc
