Repository nanocurrency/nano-node, pull requests merged in 2020-03, with the labels that each got.

#2617 update url for sourceforge
  util/build_prep/bootstrap_boost.sh
Labels: routine, universe

#2535 Election state refactor
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: enhancement

#2594 Allow CLI --config values for inactive node tests
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
Labels: cli nonbreaking change, enhancement

#2596 Attach sideband to block
  nano/core_test/block_store.cpp
  nano/core_test/epochs.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/versioning.cpp
  nano/lib/CMakeLists.txt
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/epoch.cpp
  nano/lib/epoch.hpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/secure/CMakeLists.txt
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: blocker, quality improvements

#2609 [RocksDB] Only delete from unchecked when existence is guaranteed
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: database

#2622 Host qt assets on s3
  ci/actions/windows/install_deps.ps1
Labels: routine, universe

#2623 [RocksDB] Tests not reading account count from store correctly
  nano/core_test/node_telemetry.cpp
  nano/nano_node/entry.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: unit test

#2621 Fix confirmation_height.gap_live intermittent test failure
  nano/core_test/confirmation_height.cpp
Labels: unit test

#2614 Simplify request aggregator mutex lock behavior
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
Labels: performance

#2620 Use the sideband when available in ledger.is_send
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/secure/ledger.cpp
Labels: enhancement

#2624 confirmation_height.modified_chain test fails on a non-debug build
  nano/core_test/confirmation_height.cpp
Labels: unit test

#2615 tsan fix: rpc.wallet_destroy
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: unit test

#2626 Improve --debug_profile_bootstrap performance
  nano/nano_node/entry.cpp
Labels: enhancement

#2619 Election refactor follow up
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/node.hpp
  nano/node/repcrawler.hpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.hpp
Labels: documentation, quality improvements, rpc nonbreaking change, unit test

#2588 LMDB sync options and new config settings
  nano/core_test/block_store.cpp
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/core_test/wallets.cpp
  nano/lib/CMakeLists.txt
  nano/lib/lmdbconfig.cpp
  nano/lib/lmdbconfig.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_env.cpp
  nano/node/lmdb/lmdb_env.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/secure/blockstore.hpp
Labels: beta testing wanted, database, documentation, toml

#2628 Make confirmation_solicitor.batches more robust under tsan
  nano/core_test/confirmation_solicitor.cpp
Labels: unit test

#2630 Make network.replace_port more robust under tsan
  nano/core_test/network.cpp
Labels: unit test

#2633 Add ASSERT_TIMELY
  nano/core_test/testutil.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
Labels: unit test

#2636 split docker artifacts to separate job
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
Labels: build-error, universe

#2640 Read transaction scope in active
  nano/node/active_transactions.cpp
Labels: quality improvements

#2632 Fix request_aggregator unit tests
  nano/core_test/request_aggregator.cpp
Labels: unit test

#2647 gather sha256 hashes of artifacts and upload to s3 with artifacts
  ci/actions/deploy.sh
  ci/actions/windows/build.ps1
  ci/actions/windows/deploy.ps1
Labels: routine

#2637 Read config file for CLI commands
  nano/core_test/node.cpp
  nano/core_test/socket.cpp
  nano/core_test/wallets.cpp
  nano/lib/utility.cpp
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: tool

#2581 Use attempts list for TCP channels
  nano/core_test/network.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/nodeconfig.hpp
  nano/node/testing.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2648 Fix wrong number of representatives in confirmation solicitor
  nano/node/active_transactions.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: bug

#2646 Bandwidth considerations following election refactor
  nano/node/election.cpp
  nano/node/election.hpp
Labels: performance

#2650 Telemetry results not correctly utilising cache timeouts
  nano/core_test/node_telemetry.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/slow_test/node.cpp
Labels: bug, telemetry

#2641 Increase active elections capacity with periodic full checks
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/nodeconfig.hpp
Labels: blocker, performance, quality improvements

#2643 Network duplicate filter for publish messages
  nano/core_test/active_transactions.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/lib/numbers.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/transport/udp.cpp
  nano/secure/network_filter.cpp
  nano/secure/network_filter.hpp
Labels: enhancement, performance

#2649 Erase representatives with full queues when adding to confirmation solicitor
  nano/node/confirmation_solicitor.cpp
Labels: performance

#2653 Include requesting telemetry metrics from temporary channels
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/telemetry.cpp
Labels: telemetry

#2570 Parallelize state block signature verification with block processor
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/signatures.cpp
  nano/node/signatures.hpp
  nano/node/state_block_signature_verification.cpp
  nano/node/state_block_signature_verification.hpp
Labels: performance, quality improvements

#2655 Update tick count in timer::update
  nano/core_test/timer.cpp
  nano/lib/timer.cpp
  nano/lib/timer.hpp
Labels: tool

#2631 Delay inactive/gap cache bootstrap start for 30 seconds
  nano/node/active_transactions.cpp
  nano/node/gap_cache.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: functionality quality improvements

#2659 Signature checker blocking fix
  nano/core_test/signing.cpp
  nano/node/signatures.cpp
  nano/node/signatures.hpp
  nano/node/state_block_signature_verification.cpp
  nano/slow_test/node.cpp
Labels: bug

#2656 Fix node.aggressive_flooding
  nano/core_test/node.cpp
Labels: sanitizers, unit test

#2625 Improve confirmation consistency
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#2660 typo on windows sha256 Out-File
  ci/actions/deploy.sh
  ci/actions/windows/deploy.ps1
Labels: build-error, routine, universe

#2661 Increase minimum time to log block processing
  nano/node/blockprocessor.cpp
Labels: non-functional change

#2665 Output current function in assert diagnostics
  nano/lib/utility.cpp
  nano/lib/utility.hpp
Labels: quality improvements

#2618 Sign telemetry messages
  nano/core_test/node_telemetry.cpp
  nano/core_test/testutil.hpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/load_test/entry.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/testing.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
Labels: telemetry

#2638 Definitions for work thresholds with epoch_2
  nano/core_test/difficulty.cpp
  nano/lib/config.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/blockprocessor.cpp
Labels: blocker, quality improvements

#2663 Check if a vote is for a recently confirmed block
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
Labels: performance

#2670 clang included now
  .github/workflows/tests.yml
Labels: routine, universe

#2662 Move all request aggregator operations out of the mutex hold scope
  nano/core_test/request_aggregator.cpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
Labels: performance

#2610 Remove telemetry message versions
  nano/core_test/node_telemetry.cpp
  nano/core_test/testutil.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/telemetry.cpp
  nano/slow_test/node.cpp
Labels: quality improvements, telemetry

#2634 Add telemetry response websocket callbacks
  nano/core_test/CMakeLists.txt
  nano/core_test/common.hpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/websocket.cpp
  nano/node/node.cpp
  nano/node/node_observers.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/slow_test/node.cpp
Labels: documentation, telemetry, websockets

#2505 Directed block broadcasting for long elections
  nano/core_test/active_transactions.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: networking, performance

#2603 Remove peers with different genesis block or invalid telemetry signature
  nano/core_test/network.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/websocket.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.cpp
  nano/slow_test/node.cpp
Labels: quality improvements, telemetry

#2676 Optimize mutex access when adding blocks to block processor
  nano/node/blockprocessor.cpp
Labels: quality improvements

#2666 Delay voting for non-priority elections under saturation
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/node.cpp
Labels: experiment, performance

#2675 Prevent getting stuck in block processor flush
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/state_block_signature_verification.cpp
  nano/node/state_block_signature_verification.hpp
Labels: bug

#2672 Refactor work thresholds as nano::work_thresholds
  nano/core_test/active_transactions.cpp
  nano/core_test/difficulty.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/work.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/rpc_test/rpc.cpp
Labels: non-functional change

#2667 Validate work difficulty during ledger processing
  nano/core_test/ledger.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/blockprocessor.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: protocol change

#2674 Modify inactive cache to prevent multiple insertions for confirmed
  nano/node/active_transactions.cpp
Labels: bug

#2677 Fix intermittent wallet.work_watcher_update failure
  nano/core_test/wallet.cpp
Labels: unit test

#2671 Handle epoch_2 work thresholds in the wallet and most RPCs
  nano/core_test/active_transactions.cpp
  nano/core_test/difficulty.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/fakes/work_peer.hpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/core_test/work_pool.cpp
  nano/lib/config.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/common.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work_factory.cpp
  nano/node/distributed_work_factory.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/node/websocket.cpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
Labels: breaking, documentation, rpc, websockets

#2682 Fix intermittent failure in active_transactions.confirmation_consistency
  nano/core_test/active_transactions.cpp
Labels: unit test

#2652 Consistently add conflicting block to election
  nano/core_test/node.cpp
  nano/node/node.cpp
Labels: bug

#2627 Optimize vote post-processing operations
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: enhancement

#2684 Epoch 2 started flag in ledger cache
  nano/core_test/ledger.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: functionality quality improvements, rpc, websockets

#2683 Increase minimum supported protocol version to 17
  nano/node/active_transactions.cpp
  nano/node/network.cpp
  nano/node/transport/tcp.cpp
  nano/secure/common.hpp
Labels: functionality quality improvements

#2686 Improve automatic frontiers confirmation
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: quality improvements

#2687 set timeout to 1hr to catch tests that hang
  .github/workflows/analyzers.yml
  .github/workflows/release_test.yml
  .github/workflows/tests.yml
Labels: universe

#2680 Delay wallet work caching to allow using lower difficulty on demand
  nano/core_test/wallet.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: functionality quality improvements

#2690 Work version parameter in default_difficulty and use it in more places
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: non-functional change

#2693 Move excluded_peers to network
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/peer_exclusion.cpp
  nano/node/peer_exclusion.hpp
Labels: non-functional change, unit test

#2692 Wrapper for RPC worker tasks
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements
