Repository nanocurrency/nano-node, pull requests merged in 2020-08, with the labels that each got.

#2830 Beta reset for V22 development
  nano/core_test/difficulty.cpp
  nano/lib/config.cpp
  nano/node/nodeconfig.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  rep_weights_beta.bin
Labels: routine

#2861 Fix CLI test --debug_profile_bootstrap
  nano/nano_node/entry.cpp
Labels: bug, cli

#2849 Cleanup nano::process_return
  nano/core_test/ledger.cpp
  nano/node/blockprocessor.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: quality improvements, routine

#2868 Increment major version to 22
  CMakeLists.txt
Labels: routine

#2845 Display hardcoded and ledger block height in compare_rep_weights
  nano/nano_node/entry.cpp
Labels: cli

#2873 Add source block epoch to sideband information
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/nano_node/entry.cpp
  nano/node/lmdb/lmdb.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
Labels: database, quality improvements

#2847 Changelog generator grab pull from commit message
  util/changelog.py
Labels: tool, universe

#2878 Enforce Cxx17
  .github/workflows/release_test.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  ci/actions/linux/deploy-docker.sh
  ci/actions/linux/install_deps.sh
  ci/build-centos.sh
  docker/ci/Dockerfile-clang-6
  nano/core_test/node.cpp
  nanocurrency-beta.spec.in
  nanocurrency.spec.in
  util/build_prep/centos/prep.sh.in
  util/build_prep/macosx/prep.sh.in
  util/build_prep/ubuntu/prep.sh.in
Labels: docker, documentation, unit test, universe

#2795 Write database queue functions should be NoOps with RocksDB
  nano/core_test/confirmation_height.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/write_database_queue.cpp
  nano/node/write_database_queue.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: database, quality improvements

#2852 Stats RPC to print out rocksdb memory stats
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
Labels: database, documentation, rpc

#2850 Epoch 1 legacy blocks work validation before processing
  nano/core_test/difficulty.cpp
  nano/core_test/network.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
Labels: functionality quality improvements

#2887 Avoid potential deadlock in work watcher
  nano/core_test/wallet.cpp
  nano/node/wallet.cpp
Labels: bug

#2889 Modify CLI --debug_account_versions for epoch upgrade tracking
  nano/nano_node/entry.cpp
Labels: cli, semantic

#2880 Logging exception handler and fix for stable_log_filename on windows
  nano/core_test/logger.cpp
  nano/node/logging.cpp
Labels: bug, logging

#2886 Inactive votes election hint
  nano/core_test/active_transactions.cpp
  nano/core_test/toml.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: beta testing wanted, quality improvements

#2891 Remove election fallback behaviors and adjusted multiplier calculations
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: performance

#2888 Make logging election tally an optional config
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: logging

#2892 Add random id to RPC send via IPC if not included
  nano/node/json_handler.cpp
  nano/node/node_rpc_config.cpp
  nano/node/node_rpc_config.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: ipc

#2894 Extracting votes cache bootstrap start function
  nano/node/active_transactions.cpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
Labels: non-functional change

#2895 Constrained successor and destination block activation
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/node.cpp
Labels: blocker, performance, quality improvements

#2897 Increase confirmation solicitor single-round caps
  nano/core_test/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
Labels: bug, functionality quality improvements

#2898 Docker base update
  .github/workflows/release_test.yml
  .github/workflows/tests.yml
  docker/ci/Dockerfile-base
  docker/node/Dockerfile
  util/build_prep/fetch_boost.sh
  util/build_prep/fetch_rocksdb.sh
Labels: docker
