Repository nanocurrency/nano-node, pull requests merged in 2020-09, with the labels that each got.

#2900 Temporarily pause the request loop in extreme situations
  nano/node/active_transactions.cpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: performance

#2904 Increase default bootstrap interval
  nano/node/node.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: performance

#2905 Lower request loop min_sleep for tests
  nano/node/active_transactions.cpp
Labels: unit test

#2901 Relax mutex requirement for retrieving active difficulty
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: performance

#2903 Provide network_receive_minimum in RPC/WS active_difficulty
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc, websockets

#2902 Use improved OpenCL kernel
  nano/node/openclwork.cpp
Labels: documentation, performance

#2788 Use Boost.Coroutine with asio/beast async calls in tests
  CMakeLists.txt
  nano/boost/asio/spawn.hpp
  nano/load_test/CMakeLists.txt
  nano/load_test/entry.cpp
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/rpc.cpp
Labels: documentation, quality improvements, unit test

#2907 Renaming ledger::can_vote to ledger::dependents_confirmed
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/request_aggregator.cpp
  nano/node/voting.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: quality improvements

#2908 Frontier confirmation cleanup
  nano/core_test/CMakeLists.txt
  nano/core_test/confirmation_height.cpp
  nano/core_test/frontiers_confirmation.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/secure/blockstore_partial.hpp
Labels: unit test

#2909 Add support for defer_lock in nano::unique_lock
  nano/core_test/locks.cpp
  nano/lib/locks.cpp
  nano/lib/locks.hpp
Labels: build-error, debug

#2885 Add cemented frontier successor confirmation in request loop
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/frontiers_confirmation.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_processor.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: enhancement, functionality quality improvements

#2911 Add Boost.Coroutine to bootstrap_boost.sh script
  util/build_prep/bootstrap_boost.sh
Labels: build-error

#2914 Removing channel::callback
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: quality improvements

#2860 [RocksDB] Manually flush memtables if there are a large number of tombstones
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/qt_test/qt.cpp
  nano/secure/blockstore.hpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, database

#2912 Recognize IPv4-mapped loopback addresses
  nano/rpc/rpc.cpp
Labels: logging

#2919 [TSAN] minor race in rpc.send test
  nano/rpc_test/rpc.cpp
Labels: sanitizers, unit test

#2915 Don't delete crash dump files with --debug_generate_crash_report
  nano/nano_node/entry.cpp
Labels: cli, debug

#2874 Fix inconsistent online representatives list from RPC
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/repcrawler.cpp
Labels: bug, rpc

#2896 Atomic representation weight changes
  nano/lib/rep_weights.cpp
  nano/lib/rep_weights.hpp
  nano/secure/ledger.cpp
Labels: quality improvements

#2761 Require explicit conversion from root/link to block hash or account
  nano/core_test/node.cpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/nano_node/entry.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/node.cpp
  nano/node/request_aggregator.cpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: non-functional change

#2836 RocksDB tests
  .github/workflows/release_tests.yml
  .github/workflows/rocksdb_release_tests.yml
  .github/workflows/rocksdb_tests.yml
  ci/test.sh
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: database, debug, unit test, universe

#2777 Add uncemented frontier output CLI command
  nano/nano_node/entry.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: debug, documentation

#2876 Improve ledger cache initialization with multiple threads
  nano/core_test/ledger.cpp
  nano/lib/rep_weights.cpp
  nano/lib/rep_weights.hpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: performance

#2927 Fix build error when using NANO_TIMED_LOCKS_IGNORE_BLOCKED
  nano/lib/locks.cpp
Labels: build-error

#2934 Retrieve copy of wallets in scan_receivable
  nano/node/node.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: quality improvements

#2935 Update beta V22 bootstrap weights following reset
  rep_weights_beta.bin
Labels: routine

#2928 Move forward rocksdb minimum
  ci/actions/windows/install_deps.ps1
  util/build_prep/fetch_rocksdb.sh
Labels: build-error, documentation, universe

#2930 [RocksDB] Set max_write_buffer_size_to_maintain explicitly
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
Labels: documentation

#2933 Fix core_test build with Boost 1.74
  nano/core_test/fakes/work_peer.hpp
Labels: build-error, unit test

#2932 Fix nano::timer tick update after stopping
  nano/core_test/timer.cpp
  nano/lib/timer.cpp
Labels: bug, logging

#2865 Move all vote generation to the voting thread
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/voting.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/secure/blockstore_partial.hpp
Labels: beta testing wanted, documentation, quality improvements

#2940 [RocksDB] assert compare data and not the address on iterator operator==
  nano/node/rocksdb/rocksdb_iterator.hpp
Labels: bug, database

#2941 Avoid duplicate workflows for local pulls
  .github/workflows/analyzers.yml
  .github/workflows/rocksdb_tests.yml
  .github/workflows/tests.yml
Labels: universe

#2939 Convert nano::network periodic functions to use a steady timer instead of callbacks
  CMakeLists.txt
  nano/node/CMakeLists.txt
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.hpp
Labels: quality improvements

#2937 Use node::receive_confirmed synchronously
  nano/core_test/wallet.cpp
  nano/node/active_transactions.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
Labels: functionality quality improvements, unit test

#2948 Use 1 thread to service I/O operations to allow TSAN runs.
  CMakeLists.txt
  nano/lib/threading.cpp
  nano/node/CMakeLists.txt
  util/build_prep/bootstrap_boost.sh
Labels: sanitizers, unit test

#2955 Directly use socket shared_ptr in bootstrap_client
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
Labels: quality improvements

#2956 Don't null out telemetry object
  nano/node/node.cpp
Labels: bug

#2944 Use empty uint8_t peer data
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: nanodb structure

#2961 Election encapsulation
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: blocker, quality improvements

#2918 Move channel drop policy off of nano::socket and remove channel concurrency value as redundant
  nano/core_test/socket.cpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.hpp
Labels: quality improvements

#2966 Check if awaiting collection is empty before waiting on condition in conf height processor
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
Labels: bug

#2946 [Pruning] Basic pruning blocks storage & database upgrade
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/write_database_queue.hpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: blocker, nanodb structure

#2957 Prevent immediate cleanup of new channels
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
Labels: bug

#2947 [Pruning] Pruning configuration settings
  nano/core_test/toml.cpp
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/cli.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/secure/ledger.hpp
Labels: blocker, documentation, enhancement, toml

#2967 [Pruning] Pruned blocks slow test
  nano/slow_test/node.cpp
Labels: unit test

#2971 This fixes a race condition in node.node_receive_quorum.
  nano/core_test/node.cpp
Labels: unit test

#2970 Transport loopback channel
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/nano_node/entry.cpp
  nano/node/network.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/vote_processor.cpp
  nano/node/voting.cpp
  nano/slow_test/node.cpp
Labels: networking

#2968 [Pruning] Ledger pruning functions
  nano/core_test/ledger.cpp
  nano/nano_node/entry.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: blocker, enhancement

#2964 update LD_LIBRARY_PATH for building
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  docker/node/Dockerfile
  docker/node/entry.sh
Labels: build-error

#2973 Beta reset in prep for rocksdb heavy testing
  nano/secure/common.cpp
  rep_weights_beta.bin
Labels: beta testing wanted

#2863 Resolve data type conversion warnings
  nano/core_test/active_transactions.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/signing.cpp
  nano/core_test/socket.cpp
  nano/core_test/utility.cpp
  nano/core_test/websocket.cpp
  nano/lib/rate_limiting.cpp
  nano/nano_node/entry.cpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/common.cpp
  nano/node/node.cpp
  nano/node/peer_exclusion.cpp
  nano/node/transport/transport.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2938 [RocksDB] Modify some table/column family settings
  CMakeLists.txt
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_iterator.hpp
Labels: database, performance, quality improvements

#2950 Use multiple threads in CLI debug_account_versions and debug_unconfirmed_frontiers
  nano/lib/locks.hpp
  nano/nano_node/entry.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: cli, performance

#2980 Fix intermittent failure of node.local_votes_cache_generate_new_vote
  nano/core_test/node.cpp
Labels: unit test

#2982 Add timing_logging check before conf height timing output
  nano/core_test/confirmation_height.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/node.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2981 Change usage of latest to accounts for consistency
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/testing.cpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: non-functional change

#2983 Wallets search pending deadlock
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
Labels: bug

#2987 Set thread names in db parallel traversal
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/secure/blockstore_partial.hpp
Labels: quality improvements

#2988 build bootstrap artifacts to be compatible with rpath linking
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/release_tests.yml
  .github/workflows/rocksdb_release_tests.yml
  .github/workflows/rocksdb_tests.yml
  .github/workflows/tests.yml
  docker/node/Dockerfile
  util/build_prep/bootstrap_boost.sh
  util/build_prep/fetch_boost.sh
Labels: build-error

#2975 [Pruning] Use pruned blocks in rep crawler
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/repcrawler.cpp
Labels: enhancement
