Repository nanocurrency/nano-node, pull requests merged in 2020-11, with the labels that each got.

#2994 Include block to fork confirm_req response
  nano/core_test/node.cpp
  nano/node/request_aggregator.cpp
Labels: functionality quality improvements

#2972 Translate some tests with UDP functionality to TCP
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/transport/tcp.cpp
  nano/slow_test/node.cpp
  nano/test_common/CMakeLists.txt
  nano/test_common/network.cpp
  nano/test_common/network.hpp
Labels: unit test

#3024 use $GITHUB_ENV instead of set-env
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
Labels: universe

#2883 Remove conf height put during ledger processing on a newly opened account
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/lib/config.hpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/cli.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/json_handler.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: performance

#3033 Allow [[deprecated]] attribute
  CMakeLists.txt
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: build-error

#3034 github container repo
  .github/workflows/beta_artifacts.yml
  .github/workflows/develop.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
  ci/actions/linux/deploy-docker.sh
  ci/actions/linux/ghcr_push.sh
  ci/build-docker-image.sh
  docker/ci/Dockerfile-base
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-clang-6
  docker/ci/Dockerfile-gcc
  docker/node/Dockerfile
Labels: docker, universe

#3031 Remove debug_assert which is hit calling block_confirm on already confirmed block.
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_unbounded.cpp
Labels: debug

#2884 Confirm delta
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/gap_cache.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/repcrawler.cpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: functionality quality improvements

#2881 Experimental ledger pruning
  nano/core_test/block.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
Labels: cli, documentation, enhancement, major, rpc

#3035 Renew UPNP port lease
  nano/node/portmapping.cpp
Labels: bug

#3049 Fixing boost to 1.70 on windows via artifact cache
  ci/actions/windows/build.ps1
  ci/actions/windows/install_deps.ps1
Labels: routine, universe

#3043 Fix rpc online_reps unit test
  nano/rpc_test/rpc.cpp
Labels: unit test

#3037 Customizing Test Network Parameters
  CMakeLists.txt
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/node/nodeconfig.cpp
  nano/rpc_test/CMakeLists.txt
  nano/secure/common.cpp
Labels: tool, unit test

#3054 Allow for manual triggering of artifact runs
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
Labels: universe

#3056 Fix copy pasta error with test network variables
  nano/lib/config.cpp
Labels: build-error

#3044 Fix intermittent rpc.receive_work_disabled segfaults
  nano/node/ipc/action_handler.cpp
  nano/node/ipc/ipc_broker.cpp
  nano/node/ipc/ipc_broker.hpp
  nano/node/ipc/ipc_server.cpp
  nano/node/ipc/ipc_server.hpp
Labels: unit test

#3057 follow lib naming convention of pre-compiled boost on windows
  ci/actions/windows/build.ps1
Labels: build-error
