Repository nanocurrency/nano-node, pull requests merged in 2020-04, with the labels that each got.

#2696 Remove assert if a delayed work cache request is not found
  nano/node/wallet.cpp
Labels: bug

#2695 Fix qt test wallet.seed_work_generation
  nano/qt_test/qt.cpp
Labels: unit test

#2673 Epoch open blocks should have corresponding pending entries
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: enhancement

#2688 Move vote generator calls into election code
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
Labels: functionality quality improvements

#2697 updates for fuzzer
  nano/fuzzer_test/CMakeLists.txt
  nano/fuzzer_test/fuzz_buffer.cpp
Labels: static-analysis

#2699 Fix qt tests failing to click radio buttons
  nano/qt_test/qt.cpp
Labels: unit test

#2645 Rate limiting using token buckets
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/core_test/utility.cpp
  nano/lib/CMakeLists.txt
  nano/lib/rate_limiting.cpp
  nano/lib/rate_limiting.hpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
Labels: beta testing wanted, enhancement, networking

#2651 Using relaxed atomics for counts not involved in control flow in conf height processor
  nano/core_test/confirmation_height.cpp
  nano/core_test/utility.cpp
  nano/lib/threading.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
Labels: bug, performance

#2706 Prevent more rare deadlocks due to races for condition variables
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
Labels: bug

#2694 Prevent reconnecting to excluded peers with sufficient score
  nano/core_test/network.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/toml.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/peer_exclusion.cpp
  nano/node/peer_exclusion.hpp
  nano/node/telemetry.cpp
  nano/node/transport/tcp.cpp
Labels: beta testing wanted, documentation, functionality quality improvements, networking

#2664 Incorrect cemented count during conf height algo transition
  nano/core_test/confirmation_height.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.hpp
  nano/slow_test/node.cpp
Labels: bug

#2691 Active difficulty normalization
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: beta testing wanted, documentation, enhancement

#2703 Difficulty calculation for RPC block_create
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, quality improvements, rpc

#2705 Ensure max_work_generate_difficulty is updated when changing the default difficulty
  nano/core_test/distributed_work.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: functionality quality improvements

#2711 [TSAN] lock order inversion in active transactions / wallet
  nano/node/active_transactions.cpp
Labels: sanitizers

#2712 Add node sequence for tests
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: unit test

#2689 Change response for RPC work_validate with implicit difficulty
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc, semantic

#2708 Fix failure in ledger.work_validation due to random work being above threshold
  nano/core_test/ledger.cpp
Labels: unit test

#2669 Improve telemetry request/response under load
  nano/core_test/socket.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/socket.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/testing.hpp
  nano/node/transport/transport.cpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, quality improvements, telemetry

#2700 Add Security Policy file
  SECURITY.md
  etc/gpg/clemahieu.asc
  etc/gpg/guilhermelawless.asc
  etc/gpg/sergiysw.asc
  etc/gpg/wezrule.asc
  etc/gpg/zhyatt.asc
Labels: documentation

#2704 Asynchronous epoch upgrade RPC
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: documentation, performance, rpc

#2702 Vote generator session for batch insertions
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: functionality quality improvements

#2701 Dont peer with v20 and earlier after epoch 2 block is seen
  nano/core_test/block.cpp
  nano/core_test/ledger.cpp
  nano/core_test/message.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/network_filter.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: quality improvements

#2698 [TSAN] start_time data race in bootstrap_client
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_connections.hpp
Labels: sanitizers

#2709 Ensure propagation and removal for the work watcher
  nano/core_test/wallet.cpp
  nano/node/blockprocessor.cpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: functionality quality improvements

#2710 Difficulty updates for elections with multiple blocks
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/ledger.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
  nano/node/wallet.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: quality improvements

#2714 Improve batching of writes in unbounded conf height processor
  nano/node/confirmation_height_unbounded.cpp
Labels: quality improvements

#2718 Epoch upgrader as an async task
  nano/lib/locks.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: bug, rpc

#2613 Move TCP messages processing to network threads
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: beta testing wanted, experiment, networking

#2707 Add difficulty and multiplier to CLI work generation commands
  nano/nano_node/entry.cpp
Labels: cli, documentation

#2611 Preparation for building with shared boost
  CMakeLists.txt
  util/build_prep/bootstrap_boost.sh
Labels: routine, universe

#2717 Fix logic in active_transactions.prioritize_chains test
  nano/core_test/active_transactions.cpp
Labels: unit test

#2644 Add Flatbuffers schema evolution rules to IDL
  api/flatbuffers/nanoapi.fbs
Labels: ipc

#2722 changelog_generator refactored as changelog.py
  util/changelog.py
Labels: tool

#2720 Separate election state for the broadcasting block fallback
  nano/node/election.cpp
  nano/node/election.hpp
Labels: quality improvements

#2721 Remove confirmation requests for a new representative
  nano/core_test/active_transactions.cpp
  nano/node/repcrawler.cpp
Labels: functionality quality improvements

#2724 Clarify nano_pow_server configs are not in use
  nano/nano_node/daemon.cpp
  nano/node/node_pow_server_config.cpp
Labels: enhancement

#2716 Release write_guard lock when no longer required
  nano/node/active_transactions.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/write_database_queue.cpp
  nano/node/write_database_queue.hpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2715 Allow restarting elections with higher work
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
Labels: enhancement

#2723 Some confirmed block observer callbacks being missed
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/vote_processor.cpp
  nano/slow_test/node.cpp
Labels: bug

#2728 Add active difficulty to node telemetry
  nano/core_test/node_telemetry.cpp
  nano/core_test/testutil.hpp
  nano/core_test/websocket.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, telemetry

#2730 Use a multi-index container to allow fifo queue for pending confirmations
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2727 Safely read override values when no config file is present
  nano/core_test/toml.cpp
  nano/lib/rpcconfig.cpp
  nano/lib/tomlconfig.cpp
  nano/lib/tomlconfig.hpp
  nano/node/daemonconfig.cpp
Labels: bug, toml

#2731 New stats for elections
  nano/core_test/active_transactions.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: debug, documentation

#2732 record_rep_weights to py3
  ci/record_rep_weights.py
Labels: tool, universe

#2735 Allow starting more that max_peers_per_ip test nodes
  nano/node/testing.cpp
Labels: unit test

#2729 Websocket new_unconfirmed_block
  nano/core_test/common.hpp
  nano/core_test/testutil.hpp
  nano/core_test/websocket.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2734 Websocket notification for RPC work_generate without peers
  nano/node/json_handler.cpp
Labels: bug, websockets

#2719 CLI compare_rep_weights to compare ledger and hardcoded weights
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/nano_node/entry.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: cli, documentation, tool

#2733 Remove invalid uses of epoch_1 work threshold
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/node.cpp
  nano/rpc_test/rpc.cpp
Labels: bug

#2737 Fix intermittently failing rpc.confirmation_height_currently_processing test
  nano/rpc_test/rpc.cpp
Labels: unit test

#2738 Fix intermittent node_telemetry.remove_peer_different_genesis test
  nano/core_test/node_telemetry.cpp
Labels: unit test

#2739 Fix rpc.wallet_history failures
  nano/rpc_test/rpc.cpp
Labels: unit test

#2725 CLI command for a frontier confirmation speed test
  nano/nano_node/entry.cpp
Labels: cli, documentation

#2742 Fix system.generate_send_new intermittent failures
  nano/core_test/ledger.cpp
Labels: unit test

#2744 Tally votes on conflicting block with no inactive votes
  nano/core_test/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
Labels: bug

#2745 Fix intermittently failing conflicts.adjusted_multiplier test
  nano/core_test/conflicts.cpp
Labels: unit test

#2743 Fix node.fork_invalid_block_signature intermittent failures, re-enable on windows CI
  nano/core_test/node.cpp
Labels: unit test

#2748 Fix minor test-specific intermittent failures
  nano/core_test/active_transactions.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/slow_test/node.cpp
Labels: unit test

#2750 Fix network.tcp_no_connect_excluded_peers test failure
  nano/core_test/network.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: unit test

#2752 Result difficulty in RPC block_create
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc
