Repository nanocurrency/nano-node, pull requests merged in 2020-06, with the labels that each got.

#2796 Retrieve block when activating dependencies
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: bug

#2797 Check executable paths in load_test
  nano/load_test/entry.cpp
Labels: quality improvements

#2792 update bundled FindBoost.cmake
  CMakeLists.txt
  cmake/legacyModules/FindBoost.cmake
Labels: universe

#2794 CLI commands incorrect ledger cache setup
  nano/nano_node/entry.cpp
  nano/node/node.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: bug, cli

#2785 Sequential voting
  ci/test.sh
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/wallet.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/load_test/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2799 Slow test fixes
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/write_database_queue.cpp
  nano/node/write_database_queue.hpp
  nano/slow_test/node.cpp
Labels: bug, unit test

#2800 Fix open blocks not getting activated through dependencies
  nano/core_test/election.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.hpp
Labels: bug

#2793 Add logging section to rpc config to optionally disable logging
  nano/core_test/toml.cpp
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_handler.cpp
Labels: enhancement

#2802 Clarify election difficulty update log message
  nano/node/active_transactions.cpp
Labels: logging

#2801 Sequential elections
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/rpc_test/rpc.cpp
Labels: performance, quality improvements

#2789 Epoch2 signer
  nano/secure/common.cpp
Labels: documentation, routine

#2803 add label "logging" to Developer/Debug Options Sections
  util/changelog.py
Labels: universe

#2804 Make RPC name consistent with stats, websocket & protocol naming for telemetry
  nano/core_test/CMakeLists.txt
  nano/core_test/telemetry.cpp
  nano/node/CMakeLists.txt
  nano/node/json_handler.cpp
  nano/node/peer_exclusion.hpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: documentation, rpc, semantic, telemetry

#2809 Process old does not need to queue unchecked
  nano/node/blockprocessor.cpp
Labels: bug

#2805 update changelog logic
  util/changelog.py
Labels: tool, universe

#2814 Updating copyright holders and license to BSD 3-clause
  LICENSE
Labels: non-functional change, universe

#2815 Update live bootstrap weights for V21
  rep_weights_live.bin
Labels: routine

#2819 correct rpath for libs in tar.bz2 archive
  CMakeLists.txt
Labels: build-error

#2808 Block builders build_shared and use in more tests
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/lib/blockbuilders.cpp
  nano/lib/blockbuilders.hpp
Labels: unit test

#2780 Use ASSERT_TIMELY in tests where possible
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ipc.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: unit test

#2770 Remove node v18 and earlier upgrade support
  nano/core_test/CMakeLists.txt
  nano/core_test/block_store.cpp
  nano/core_test/ipc.cpp
  nano/core_test/logger.cpp
  nano/core_test/node.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/lib/rpcconfig.cpp
  nano/node/cli.cpp
  nano/node/daemonconfig.cpp
  nano/node/ipc/ipc_config.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/logging.cpp
  nano/node/node.cpp
  nano/node/node_rpc_config.cpp
  nano/node/node_rpc_config.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/versioning.cpp
  nano/secure/versioning.hpp
Labels: blocker, documentation, non-functional change

#2775 Refactor shared testing code from core_test
  CMakeLists.txt
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/block.cpp
  nano/core_test/block_store.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/cli.cpp
  nano/core_test/common.hpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/difficulty.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/election.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ipc.cpp
  nano/core_test/ledger.cpp
  nano/core_test/locks.cpp
  nano/core_test/logger.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/network_filter.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/socket.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/timer.cpp
  nano/core_test/toml.cpp
  nano/core_test/uint256_union.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/lib/config.hpp
  nano/load_test/CMakeLists.txt
  nano/load_test/entry.cpp
  nano/nano_node/entry.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/vote_processor.hpp
  nano/qt_system/entry.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/slow_test/CMakeLists.txt
  nano/slow_test/node.cpp
  nano/test_common/CMakeLists.txt
  nano/test_common/telemetry.cpp
  nano/test_common/telemetry.hpp
  nano/test_common/testutil.cpp
  nano/test_common/testutil.hpp
Labels: documentation, non-functional change, unit test

#2736 Improve distributed_work_factory item management
  nano/core_test/distributed_work.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/wallet.cpp
  nano/node/distributed_work_factory.cpp
  nano/node/distributed_work_factory.hpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#2823 Pre-sample block rate for bootstrap connections
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_connections.hpp
Labels: bug

#2821 node config spelling errors
  nano/node/nodeconfig.cpp
Labels: non-functional change

#2822 Prevent CPU usage in --debug_opencl
  nano/nano_node/entry.cpp
Labels: bug, cli

#2825 Fix requeue pull for lazy bootstrap
  nano/node/bootstrap/bootstrap_connections.cpp
Labels: bug
