Repository nanocurrency/nano-node, pull requests merged in 2020-05, with the labels that each got.

#2746 Fix Xcode warnings
  nano/core_test/active_transactions.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/wallet.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/election.cpp
  nano/node/ipc/ipc_access_config.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/write_database_queue.cpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#2751 Serialize telemetry as big endian
  nano/core_test/node_telemetry.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/slow_test/node.cpp
Labels: networking, telemetry

#2757 [TSAN] race for system in test websocket.bootstrap_exited
  nano/core_test/websocket.cpp
Labels: sanitizers, unit test

#2759 Perform wallet representative action without holding any mutex
  nano/core_test/wallet.cpp
  nano/node/voting.cpp
  nano/node/wallet.cpp
Labels: quality improvements

#2749 Multithreaded --validate_blocks
  nano/nano_node/entry.cpp
Labels: cli, documentation

#2760 Fix intermittent failure in test wallet.work_cache_delayed
  nano/core_test/wallet.cpp
Labels: unit test

#2762 Add cemented block log timings
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
Labels: quality improvements

#2766 Votes from local representatives should not be flooded on processing
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/daemon.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/request_aggregator.cpp
  nano/node/voting.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: bug, quality improvements

#2767 Fix previous balance in active_transaction::insert ()
  nano/node/active_transactions.cpp
Labels: bug

#2754 Optional "block" given to RPC "work_generate" to infer difficulty
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/testing.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc

#2772 Republishing a vote to principal representatives
  nano/node/network.cpp
Labels: networking

#2769 Deprecate --batch_size/debug_mass_acitvity CLI options
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
Labels: cli, deprecation, documentation

#2768 Force node exit if ledger inconsistency in the conf height processor is found
  nano/core_test/confirmation_height.cpp
  nano/core_test/difficulty.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/secure/blockstore_partial.hpp
Labels: quality improvements

#2774 Enable WebSocket server by default in Docker image
  docker/node/config/config-node.toml
Labels: docker

#2783 enable shared boost for tests
  ci/actions/windows/build.ps1
  ci/actions/windows/configure.bat
  ci/build-travis.sh
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-clang-6
  docker/ci/Dockerfile-gcc
Labels: universe

#2565 Push front blocks from unchecked
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
Labels: beta testing wanted, experiment, quality improvements

#2781 Union std::hash coverage
  nano/core_test/uint256_union.cpp
  nano/lib/numbers.hpp
  nano/slow_test/node.cpp
Labels: bug

#2784 Confirmation requests and broadcasts if available vote is for a conflicting block
  nano/core_test/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.cpp
Labels: quality improvements

#2782 Stuck uncemented blocks after heavy load
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/online_reps.cpp
  nano/slow_test/node.cpp
Labels: bug

#2786 [TSAN] Fix off-by-one in socket.drop_policy test
  nano/core_test/socket.cpp
Labels: sanitizers, unit test

#2787 Double default bandwidth limit config
  nano/core_test/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: configuration default change

#2790 use full cache for PR's requesting modules not currently specified in…
  docker/ci/Dockerfile-gcc
  util/build_prep/fetch_boost.sh
Labels: build-error, universe

#2791 Fix insufficient work logging
  nano/node/blockprocessor.cpp
Labels: bug

#2778 Bisected election backtracking
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: quality improvements
