Repository nanocurrency/nano-node, pull requests merged in 2020-02, with the labels that each got.

#2528 Improve initial TCP server keepalive
  nano/node/network.cpp
Labels: networking

#2527 Allow rep crawler targets with ephemeral ports
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/repcrawler.cpp
  nano/node/telemetry.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: bug, networking

#2512 Cache genesis block hash in ledger constants
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/memory_pool.cpp
  nano/core_test/node.cpp
  nano/core_test/testutil.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: performance

#2537 Update beta network bootstrap weights for v21, cutoff 7M
  rep_weights_beta.bin
Labels: routine

#2536 Cache hash for multiple block->hash () calls
  nano/core_test/block.cpp
  nano/core_test/bootstrap.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/node/active_transactions.cpp
Labels: performance

#2530 Remove representatives with closed channels
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: bug

#2538 ASAN error with database transaction tracker json serialization
  nano/node/lmdb/lmdb_txn.cpp
Labels: sanitizers

#2540 Lower beta network work threshold to 1/64x base
  nano/core_test/difficulty.cpp
  nano/lib/config.hpp
Labels: documentation

#2531 Bounded memory and redesign in the confirmation height processor
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/cli.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/election.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: functionality quality improvements, performance

#2545 Sideband upgrade using epoch byte for is_send/receive/epoch
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/versioning.cpp
  nano/nano_node/entry.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/secure/blockstore.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: database, documentation, nanodb structure

#2541 Handle legacy confirm_req using the aggregator
  nano/core_test/node.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: networking

#2521 Poll all nodes, remove outliers, ddos protection & amend RPC response with endpoint
  nano/core_test/node_telemetry.cpp
  nano/lib/utility.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, documentation, quality improvements, telemetry

#2547 BOOST_1.69
  CMakeLists.txt
  ci/actions/windows/build.ps1
  ci/actions/windows/configure.bat
  cmake/Modules/FindBoost.cmake
Labels: build-error, universe

#2543 Probabilistic network packet filter
  nano/core_test/CMakeLists.txt
  nano/core_test/network_filter.cpp
  nano/lib/CMakeLists.txt
  nano/lib/blocks.hpp
  nano/lib/stream.hpp
  nano/node/common.hpp
  nano/secure/CMakeLists.txt
  nano/secure/network_filter.cpp
  nano/secure/network_filter.hpp
Labels: enhancement

#2518 Active_transactions updates blocks when updating difficulty.
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/wallet.cpp
Labels: functionality quality improvements

#2548 Add wallet-processed block to work watcher via the block processor
  nano/core_test/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/wallet.cpp
Labels: quality improvements, unit test

#2550 guard policy setting by version checks
  CMakeLists.txt
Labels: build-error, universe

#2546 Restore max block processor signature verification batch size
  nano/node/blockprocessor.cpp
Labels: bug

#2554 [ASAN] Access node through a weak_ptr on distributed_work dtor
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements, sanitizers, unit test

#2542 Separate inactive votes cache from gap cache
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
Labels: blocker, quality improvements

#2553 Inactive votes cache confirmation status
  nano/core_test/bootstrap.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: bug

#2557 Add launch flag --disable_block_processor_unchecked_deletion
  nano/node/blockprocessor.cpp
  nano/node/cli.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, enhancement

#2561 Disable node.fork_open_flip test on Windows actions
  nano/core_test/node.cpp
Labels: unit test

#2562 Fake websocket client to test the node websocket server
  nano/core_test/CMakeLists.txt
  nano/core_test/fakes/websocket_client.hpp
  nano/core_test/websocket.cpp
  nano/node/websocket.hpp
Labels: unit test, websockets

#2566 Incremental options for ws confirmation subscription
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#2563 Fix election calling confirm_if_quorum after destruction
  nano/node/election.cpp
Labels: bug

#2564 Update --debug_profile_process CLI test
  nano/nano_node/entry.cpp
Labels: tool

#2560 Request telemetry data for local node
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/rpc_test/rpc.cpp
Labels: documentation, enhancement, rpc nonbreaking change, telemetry

#2555 Disable UDP by default
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/peer_container.cpp
  nano/node/cli.cpp
  nano/node/cli.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, networking

#2571 Use only the necessary protocols in UPnP
  nano/nano_node/entry.cpp
  nano/node/portmapping.cpp
  nano/node/portmapping.hpp
Labels: functionality quality improvements

#2559 Buffer drop policies
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/core_test/socket.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/election.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/telemetry.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/wallet.cpp
Labels: networking

#2567 Add GSL-style narrow_cast
  nano/lib/utility.hpp
  nano/node/election.cpp
  nano/node/telemetry.cpp
Labels: non-functional change

#2572 Move back timer comments to header
  nano/lib/timer.cpp
  nano/lib/timer.hpp
  nano/node/socket.hpp
Labels: non-functional change

#2544 Use a different confirmation height algorithm when ledger is almost fully cemented
  nano/core_test/confirmation_height.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: documentation, enhancement, performance

#2556 Update --debug_profile_bootstrap CLI test
  nano/nano_node/entry.cpp
Labels: tool

#2574 Add tests for vote_processor
  nano/core_test/CMakeLists.txt
  nano/core_test/vote_processor.cpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: quality improvements, unit test

#2576 Fix intermittent node telemetry tests with tsan/valgrind
  nano/core_test/node_telemetry.cpp
  nano/node/common.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/slow_test/node.cpp
Labels: unit test

#2534 Log stable filename
  nano/core_test/toml.cpp
  nano/node/logging.cpp
  nano/node/logging.hpp
Labels: documentation, enhancement

#2584 tsan: race in telemetry::ongoing_single_request_cleanup
  nano/node/telemetry.cpp
Labels: sanitizers

#2582 Check against op aborted on secure rpc acceptor shutdown
  nano/rpc/rpc_secure.cpp
Labels: bug

#2586 [TSAN] confirmation_height.cemented_gap_below_receive test
  nano/core_test/confirmation_height.cpp
Labels: sanitizers, unit test

#2587 [TSAN] vote_processor.flush test
  nano/core_test/vote_processor.cpp
Labels: sanitizers, unit test

#2591 friendly backtraces in actions
  CMakeLists.txt
  ci/actions/windows/build.ps1
  ci/actions/windows/deploy.ps1
  ci/actions/windows/disable_windows_defender.ps1
  ci/actions/windows/install_deps.ps1
  ci/actions/windows/signing.ps1
  ci/build-travis.sh
  docker/ci/Dockerfile-clang
Labels: debug

#2585 Remove vote cache & generate new vote if election winner is changed
  nano/node/election.cpp
Labels: enhancement

#2580 Improve confirmation_solicitor.batches test
  nano/core_test/confirmation_solicitor.cpp
Labels: unit test

#2573 Add peer timestamp to telemetry responses
  nano/core_test/node_telemetry.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.hpp
  nano/slow_test/node.cpp
Labels: documentation, quality improvements, telemetry

#2592 [RocksDB] Limit write locks to necessary tables
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/online_reps.cpp
Labels: database

#2589 Reworking confirmation_height.dependent_election test
  nano/core_test/confirmation_height.cpp
Labels: quality improvements

#2590 Remove dropped_election_cache in preparation for election refactor.
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
Labels: quality improvements

#2595 Fix rpc telemetry test timestamps
  nano/rpc_test/rpc.cpp
Labels: unit test

#2579 Configurable inactive votes cache size
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/cli.cpp
  nano/node/nodeconfig.hpp
Labels: documentation, enhancement

#2599 Block work version
  nano/core_test/block.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/fakes/work_peer.hpp
  nano/core_test/wallet.cpp
  nano/core_test/work_pool.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/common.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
Labels: blocker, enhancement

#2577 Minimize work validation calls
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/qt/qt.cpp
Labels: blocker, performance, quality improvements

#2593 Start vote generator for changed winner only if voting is enabled
  nano/node/election.cpp
Labels: bug

#2600 Reduce active mutex locking with election winner details
  nano/core_test/confirmation_height.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/secure/ledger.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#2575 Add flag for vote_processor capacity and tests
  nano/core_test/vote_processor.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: documentation, quality improvements, unit test

#2602 Don't use active mutex lock during confirmation solicitor.prepare ()
  nano/node/active_transactions.cpp
Labels: enhancement

#2549 Aggressive flooding for local blocks
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
Labels: networking

#2601 Block difficulty and work validation cleanup
  nano/core_test/active_transactions.cpp
  nano/core_test/block.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/fakes/work_peer.hpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/core_test/work_pool.cpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/node/active_transactions.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/openclwork.cpp
  nano/node/wallet.cpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement

#2499 Bootstrap attempts and connections/pulls separation
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_bulk_push.hpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_connections.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: beta testing wanted, documentation, functionality quality improvements, rpc semantics change

#2607 CMakeLists backwards compatibility
  CMakeLists.txt
  cmake/legacyModules/FindBoost.cmake
Labels: universe

#2608 Lock before stopping when notifying other threads
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/portmapping.hpp
  nano/node/write_database_queue.cpp
  nano/node/write_database_queue.hpp
Labels: quality improvements, sanitizers

#2598 Simplify telemetry data processing
  nano/core_test/network.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/testutil.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: beta testing wanted, quality improvements, telemetry

#2606 Launch flag --allow_bootstrap_peers_duplicates
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/cli.cpp
  nano/node/nodeconfig.hpp
Labels: cli nonbreaking change, documentation, enhancement

#2612 Fix intermittent send_node_id_handshake unit test failures
  nano/core_test/network.cpp
Labels: unit test
