Repository nanocurrency/nano-node, pull requests merged in 2020-01, with the labels that each got.

#2457 Allow core_test retries until 7-1-2020 00:00(gmt)
  ci/test.sh
Labels: build-error, universe

#2454 Global bandwidth limiter
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/lib/plat/linux/debugging.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
Labels: functionality quality improvements, networking

#2427 qt dev wallet deserialization fix
  nano/nano_wallet/entry.cpp
Labels: qt

#2455 New CLI command to generate a crash report
  nano/lib/utility.cpp
  nano/nano_node/entry.cpp
Labels: documentation, quality improvements

#2447 Remove rolled back blocks list
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
Labels: functionality quality improvements

#2448 Erase inactive votes cache after election stop / finish
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/node.cpp
Labels: quality improvements

#2399 Add HOST header to distributed work request
  nano/node/distributed_work.cpp
Labels: networking

#2458 Cache unchecked count
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/vote_processor.cpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: database, performance

#2449 Some code cleanup
  nano/core_test/locks.cpp
  nano/lib/alarm.cpp
  nano/lib/alarm.hpp
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/config.hpp
  nano/lib/rep_weights.cpp
  nano/lib/rep_weights.hpp
  nano/lib/threading.cpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/lib/work.cpp
  nano/lib/work.hpp
  nano/lib/worker.cpp
  nano/lib/worker.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/daemonconfig.cpp
  nano/node/distributed_work_factory.cpp
  nano/node/distributed_work_factory.hpp
  nano/node/gap_cache.cpp
  nano/node/gap_cache.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/node_observers.cpp
  nano/node/node_observers.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/repcrawler.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: non-functional change

#2451 Avoid replying to confirm_req with repeated votes
  nano/core_test/node.cpp
  nano/node/network.cpp
Labels: bug, performance

#2452 Confirmation solicitor
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
  nano/node/election.hpp
Labels: quality improvements

#2444 Indeterminate vote status and enhanced websocket vote sub
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/node.cpp
  nano/node/node_observers.hpp
  nano/node/vote_processor.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/secure/common.hpp
Labels: bug, documentation, quality improvements, websockets

#2474 Use a strand in distributed_work
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/distributed_work_factory.cpp
  nano/node/distributed_work_factory.hpp
  nano/rpc_test/rpc.cpp
Labels: functionality quality improvements

#2470 Use node reference instead of system.nodes[n] in unit tests more often
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/rpc_test/rpc.cpp
Labels: non-functional change, unit test

#2462 Process RPC incorrect enable_control checking when using watch_work
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug

#2465 Fixing some intermittent failures in unit tests, and some cleanup
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/node/transport/udp.cpp
Labels: sanitizers, unit test

#2479 Fix thread worker unit test so it handles repeat runs
  nano/core_test/utility.cpp
Labels: unit test

#2480 Fix some formatting issues on develop
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
  nano/node/node.cpp
  nano/secure/ledger.hpp
Labels: build-error

#2478 Add clang-format test back in
  .github/workflows/tests.yml
  ci/check-commit-format.sh
Labels: unit test, universe

#2432 Generated votes cache size increase and upper bound
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/node/wallet.cpp
  nano/secure/common.cpp
Labels: networking, performance

#2475 Remove unnecessary lock requirement in active_transactions::lock.
  nano/core_test/active_transactions.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/node.cpp
  nano/node/vote_processor.cpp
Labels: non-functional change

#2472 Confirmation solicitor revamp
  nano/core_test/CMakeLists.txt
  nano/core_test/confirmation_solicitor.cpp
  nano/lib/config.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
  nano/node/election.hpp
  nano/node/nodeconfig.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: blocker, bug, functionality quality improvements

#2476 Beta network reset #2
  nano/secure/common.cpp
  rep_weights_beta.bin
Labels: routine

#2486 use v1.1 for actions-aws-cli
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
Labels: build-error

#2403 The start of CLI tests
  nano/core_test/CMakeLists.txt
  nano/core_test/cli.cpp
  nano/node/cli.cpp
  nano/node/cli.hpp
Labels: unit test

#2437 Change processed blocks factor for requeued pulls
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
Labels: enhancement

#2481 Upgrade confirmation height table to include cemented frontier
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/core_test/versioning.cpp
  nano/core_test/wallets.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/cli.cpp
  nano/node/confirmation_height_processor.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/slow_test/node.cpp
Labels: blocker, documentation, nanodb structure, rpc nonbreaking change

#2485 Request aggregator
  nano/core_test/CMakeLists.txt
  nano/core_test/message.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/CMakeLists.txt
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/voting.cpp
Labels: documentation, enhancement, performance

#2490 use clang-format-8
  .github/workflows/tests.yml
Labels: build-error

#2491 Formatting fix so clang-format v8 applies cleanly
  nano/core_test/websocket.cpp
Labels: build-error

#2477 Support multiple work peers in the same host
  nano/core_test/CMakeLists.txt
  nano/core_test/distributed_work.cpp
  nano/core_test/fakes/work_peer.hpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
  nano/node/distributed_work_factory.cpp
Labels: bug, functionality quality improvements, unit test

#2488 Unchecked cache not handling duplicate entries or unchecked_clear
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: bug

#2498 Emplacing wherever possible and other misc enhancements
  nano/lib/stats.cpp
  nano/lib/threading.cpp
  nano/lib/work.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/network.cpp
  nano/node/nodeconfig.cpp
  nano/node/online_reps.cpp
  nano/node/repcrawler.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/node/vote_processor.cpp
  nano/node/wallet.cpp
  nano/node/websocket.cpp
  nano/qt_system/entry.cpp
Labels: quality improvements

#2492 remove clang-format guards as not needed on 8 or prior
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/lib/ipc_client.cpp
  nano/lib/work.cpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/distributed_work.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb_env.hpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/request_aggregator.cpp
  nano/node/signatures.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/node/voting.cpp
  nano/node/wallet.cpp
  nano/node/websocket.cpp
  nano/node/write_database_queue.cpp
  nano/rpc/rpc_request_processor.cpp
  nano/rpc_test/rpc.cpp
Labels: universe

#2489 Log when voting and warn if voting with more than one account
  nano/nano_node/daemon.cpp
  nano/node/node.cpp
Labels: non-functional change

#2500 Extend distributed_work.peer_malicious test to fix intermittent failure
  nano/core_test/distributed_work.cpp
Labels: unit test

#2464 Don't bind to UDP socket with --disable_udp flag
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: beta testing wanted, networking

#2501 Bounded request aggregator
  nano/core_test/request_aggregator.cpp
  nano/core_test/toml.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
Labels: beta testing wanted, documentation, functionality quality improvements, performance

#2503 update vc_redist url
  ci/actions/windows/build.ps1
Labels: universe

#2504 Reinstate election request limit on the confirmation solicitor
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
Labels: networking

#2502 Prevent possible issues with ledger contaning pending records only for burn account
  nano/node/json_handler.cpp
  nano/node/wallet.cpp
  nano/rpc_test/rpc.cpp
Labels: bug

#2508 Update bootstrap tests to disable frontiers confirmation
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
Labels: unit test

#2510 Fix bootstrap_exited segfault on macos
  nano/core_test/websocket.cpp
Labels: unit test

#2509 Refresh mutex lock after some consecutive requests without generation
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
Labels: performance

#2446 Node telemetry
  nano/core_test/CMakeLists.txt
  nano/core_test/message_parser.cpp
  nano/core_test/node.cpp
  nano/core_test/node_telemetry.cpp
  nano/core_test/toml.cpp
  nano/lib/CMakeLists.txt
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: beta testing wanted, documentation, enhancement, protocol feature, telemetry

#2506 Clear peers and online weight after 1 week of inactivity
  nano/node/node.cpp
  nano/node/node.hpp
Labels: database, enhancement

#2497 Vote replay in crawler
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: performance, quality improvements

#2507 Adjust request aggregator stats
  nano/core_test/request_aggregator.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
Labels: documentation, functionality quality improvements

#2513 Avoid long read transactions for bootstrap
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_bulk_push.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
Labels: quality improvements

#2515 Additional ledger stats
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/blockprocessor.cpp
Labels: documentation

#2517 unstable tests on actions for windows
  .github/workflows/tests.yml
  CMakeLists.txt
  ci/actions/windows/build.ps1
  ci/build-travis.sh
  nano/core_test/CMakeLists.txt
  nano/core_test/node.cpp
Labels: unit test

#2496 Buffer parser fuzzing
  CMakeLists.txt
  docker/ci/Dockerfile-clang-6
  nano/fuzzer_test/CMakeLists.txt
  nano/fuzzer_test/fuzz_buffer.cpp
  nano/lib/blocks.cpp
  nano/lib/work.cpp
Labels: sanitizers

#2520 update fuzz_buffer
  nano/fuzzer_test/fuzz_buffer.cpp
Labels: build-error

#2511 Cache account count
  nano/core_test/ledger.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: database, performance

#2519 Resolving hostnames in distributed_work
  nano/core_test/distributed_work.cpp
  nano/node/distributed_work.cpp
  nano/node/distributed_work.hpp
Labels: bug, documentation, functionality quality improvements

#2523 Fuzz account, hex, dec and endpoint parsing
  nano/fuzzer_test/CMakeLists.txt
  nano/fuzzer_test/fuzz_bignum.cpp
  nano/fuzzer_test/fuzz_endpoint_parsing.cpp
Labels: sanitizers

#2468 Publish prototype
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/node/active_transactions.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/voting.cpp
  nano/node/wallet.hpp
Labels: functionality quality improvements, performance

#2525 Define GCC sanitizers builds
  nano/lib/config.hpp
Labels: sanitizers, unit test

#2522 Optionally disable data in responses to telemetry requests with CLI option
  nano/core_test/node_telemetry.cpp
  nano/node/cli.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/network.cpp
  nano/node/nodeconfig.hpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
Labels: documentation, quality improvements, telemetry

#2524 Extend telemetry data with more node versioning details
  CMakeLists.txt
  nano/core_test/node_telemetry.cpp
  nano/lib/CMakeLists.txt
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/network.cpp
  nano/rpc_test/rpc.cpp
Labels: beta testing wanted, documentation, quality improvements, telemetry
