Repository nanocurrency/nano-node, pull requests merged in 2021-05, with the labels that each got.

#3256 Bugfix: signal handlers called twice for each signal received
  nano/lib/signal_manager.cpp
Labels: bug

#3236 Qt test wallet status with peer
  nano/qt_test/qt.cpp
Labels: unit test

#3259 Update active_transaction.inactive_votes_cache_fork with election scheduler changes
  nano/core_test/active_transactions.cpp
Labels: unit test

#3246 Remove frontiers confirmation start only after reaching cemented > hardcoded
  nano/node/active_transactions.cpp
Labels: functionality quality improvements

#3258 Prevent blocks conflict in RPC pruned tests & improve confirmation in RPC pending tests
  nano/rpc_test/rpc.cpp
Labels: unit test

#3251 Change default active elections size
  nano/node/nodeconfig.hpp
Labels: quality improvements

#3260 Remove elections difficulty sorting
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/node.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/toml.cpp
  nano/core_test/wallet.cpp
  nano/core_test/websocket.cpp
  nano/core_test/work_watcher.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/node_observers.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/state_block_signature_verification.cpp
  nano/node/state_block_signature_verification.hpp
  nano/node/testing.cpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: breaking, documentation, removal, rpc refactor, websockets

#3257 Sighup reload bandwidth params
  nano/core_test/network.cpp
  nano/core_test/utility.cpp
  nano/lib/rate_limiting.cpp
  nano/lib/rate_limiting.hpp
  nano/nano_node/daemon.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  systest/set_bandwidth_params.sh
Labels: enhancement

#3237 Change return details for "bootstrap_lazy" RPC
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/node/json_handler.cpp
Labels: documentation, rpc refactor

#3127 Limit peers per subnetwork
  nano/core_test/network.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: networking

#3265 Election flush
  nano/core_test/election_scheduler.cpp
  nano/node/election_scheduler.cpp
  nano/node/election_scheduler.hpp
  nano/node/node.cpp
Labels: bug

#3134 Final votes
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/request_aggregator.cpp
  nano/node/request_aggregator.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
  nano/node/websocket.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: enhancement

#3267 Deprecate RPC active_difficulty instead of removing it
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc

#3270 Adjust active_transactions.pessimistic_elections & network.last_contacted
  nano/core_test/active_transactions.cpp
  nano/core_test/network.cpp
Labels: unit test

#3273 Fix active transactions pruning regression
  nano/node/active_transactions.cpp
Labels: bug

#3272 Adjust node.aggressive_flooding test
  nano/core_test/node.cpp
Labels: unit test

#3276 Default include only confirmed data for RPC supporting it
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc, semantic

#3254 New Rep weights live file (#3238)
  ci/record_rep_weights.py
  rep_weights_live.bin
Labels: routine

#3279 Improve confirmation_height.gap_live core test
  nano/core_test/confirmation_height.cpp
Labels: unit test

#3281 Prevent not processed blocks addition to confirmed elections list
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/node/election.cpp
  nano/node/node.cpp
Labels: enhancement

#3282 specify ip notation for preconfigured peers
  nano/node/nodeconfig.cpp
Labels: documentation, non-functional change, toml

#3283 Simplify inactive_votes_cache_election_start test
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
Labels: unit test

#3278 Update deploy-docker.sh
  ci/actions/linux/deploy-docker.sh
Labels: docker

#3277 Extend 'wallet_info' RPC command
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc

#3311 Remove election blocks () debug assert
  nano/node/election.cpp
Labels: bug
