Repository nanocurrency/nano-node, pull requests merged in 2021-01, with the labels that each got.

#3018 Fix qt wallet hitting a debug_assert when creating blocks
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
Labels: bug

#3068 Limit failures for confirmed lazy bootstrap bulk pull
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/secure/common.cpp
Labels: functionality quality improvements

#3065 Improve message logging for bulk pull requests
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
Labels: logging

#3052 Update online_weight_quorum default to 67
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/node/json_handler.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
Labels: beta test cases, configuration default change, quality improvements

#3027 Republish only winners for forked elections
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
Labels: beta test cases, functionality quality improvements

#3026 Storing blocks according to tally in elections with forks
  nano/core_test/active_transactions.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
Labels: beta test cases, functionality quality improvements

#3062 Fix intermittent node.bootstrap_bulk_push failure
  nano/core_test/node.cpp
Labels: unit test

#3082 Increment retry date string
  ci/test.sh
Labels: routine, universe

#3078 Fix wallet_republish crash during bootstrap
  nano/node/network.cpp
Labels: bug

#3048 Update online weight before checking quorum
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/online_reps.cpp
  nano/node/online_reps.hpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: quality improvements

#3060 Pending RPC to sort by absolute amounts when returning a subset
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: breaking, documentation, quality improvements, rpc

#3014 Remove telemetry signature partitions
  nano/core_test/telemetry.cpp
  nano/lib/stream.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/telemetry.cpp
  nano/test_common/telemetry.cpp
Labels: functionality quality improvements, telemetry

#2763 Vote spacing
  nano/core_test/voting.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/voting.cpp
  nano/node/voting.hpp
Labels: quality improvements

#3088 more changes regarding github actions security hardening
  .github/workflows/analyzers.yml
  .github/workflows/beta_artifacts.yml
  .github/workflows/develop.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/release_tests.yml
  .github/workflows/rocksdb_release_tests.yml
  .github/workflows/rocksdb_tests.yml
  .github/workflows/test_network_artifacts.yml
  .github/workflows/tests.yml
Labels: universe

#3028 Persistent TCP channel endpoint value
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: bug

#3063 Fix intermittent work_watcher.confirm_while_generating failure
  nano/core_test/work_watcher.cpp
Labels: unit test

#3069 Add --rpcconfig option and fix wallet config bug
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/nodeconfig.hpp
Labels: bug, documentation, enhancement

#3080 Optional async for process RPC
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/state_block_signature_verification.cpp
  nano/node/state_block_signature_verification.hpp
  nano/rpc_test/rpc.cpp
Labels: documentation, enhancement, rpc

#3090 Add recent constref change to rpc secure as well
  nano/rpc/rpc_connection.cpp
  nano/rpc/rpc_connection_secure.cpp
  nano/rpc/rpc_connection_secure.hpp
Labels: build-error

#3085 Wallet store adhoc keys inconsistency with reps container
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/lmdb/lmdb_txn.hpp
  nano/node/rocksdb/rocksdb_txn.cpp
  nano/node/rocksdb/rocksdb_txn.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
Labels: bug

#3059 Improve inactive votes cache memory allocation
  nano/core_test/memory_pool.cpp
  nano/lib/blocks.cpp
  nano/lib/memory.cpp
  nano/lib/memory.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/common.cpp
Labels: quality improvements

#3084 Fix online reps live votes update
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/repcrawler.hpp
  nano/node/vote_processor.cpp
Labels: bug

#3086 Remove boost process code
  CMakeLists.txt
  nano/core_test/CMakeLists.txt
  nano/load_test/CMakeLists.txt
  nano/load_test/entry.cpp
  nano/nano_node/CMakeLists.txt
  nano/nano_node/daemon.cpp
  nano/nano_wallet/entry.cpp
Labels: non-functional change

#3051 Wallet create causing crash when confirming blocks
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/node/active_transactions.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/slow_test/node.cpp
Labels: bug
