Repository nanocurrency/nano-node, pull requests merged in 2021-04, with the labels that each got.

#3174 Election start encapsulation
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: quality improvements

#3158 Fix FreeBSD build error: "Cannot find source file: plat/plat/default/debugging.cpp"
  nano/lib/CMakeLists.txt
Labels: bug

#3147 Limit frontier request block count by default
  nano/core_test/toml.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/bootstrap/bootstrap_legacy.hpp
  nano/node/json_handler.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/secure/common.cpp
Labels: documentation, functionality quality improvements, rpc

#3190 Prioritization
  nano/core_test/CMakeLists.txt
  nano/core_test/prioritization.cpp
  nano/node/CMakeLists.txt
  nano/node/prioritization.cpp
  nano/node/prioritization.hpp
Labels: enhancement

#3164 Resolve issue with inactive votes cache not triggering elections to start
  nano/node/active_transactions.cpp
Labels: quality improvements

#3231 Check bulk push availability
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
Labels: functionality quality improvements

#3208 Election scheduler
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/election_scheduler.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/wallet.cpp
  nano/core_test/work_watcher.cpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election_scheduler.cpp
  nano/node/election_scheduler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
  nano/slow_test/node.cpp
Labels: enhancement

#3211 fixes sha256 sum file generation
  ci/actions/deploy.sh
  ci/actions/windows/deploy.ps1
Labels: non-functional change, routine

#3144 The build info shows following description: \
  CMakeLists.txt
  cmake/legacyModules/FindBoost.cmake
  util/build_prep/bootstrap_boost.sh
  util/build_prep/centos/prep.sh.in
  util/build_prep/macosx/prep.sh.in
  util/build_prep/ubuntu/prep.sh.in
Labels: logging, non-functional change

#3183 stop deploying live on latest
  ci/actions/linux/deploy-docker.sh
Labels: docker, documentation, routine

#3240 Remove printing of log to stderr (file descriptor limit too low)
  nano/nano_node/daemon.cpp
Labels: quality improvements

#3250 Do not repeat core_test in CI
  ci/test.sh
Labels: non-functional change, tool

#3252 Fix block processor add issue
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
Labels: bug
