Repository nanocurrency/nano-node, pull requests merged in 2021-12, with the labels that each got.

#3572 Unlocking lock in all branch cases.
  nano/node/election_scheduler.cpp
Labels: bug

#3555 Use OS picked ports in `core_test`
  nano/core_test/fakes/work_peer.hpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/socket.cpp
  nano/core_test/websocket.cpp
Labels: unit test

#3585 Remove short election expiration time for dev network
  nano/node/election.cpp
Labels: unit test

#3587 Fixes the early drops of not yet timed out connections
  nano/node/socket.cpp
  nano/node/socket.hpp
Labels: bug

#3591 Specifying macos toolchain explicitly to 10.15 rather than tracking latest.
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
  .github/workflows/tests.yml
Labels: bug

#3590 Check and track request underflows in bootstrap/realtime message processing.
  nano/lib/stats.hpp
  nano/node/bootstrap/bootstrap_server.cpp
Labels: bug

#3593 Adding detail string for request_underflow.
  nano/lib/stats.cpp
Labels: bug

#3597 Fix foreach representative deadlock
  nano/core_test/wallet.cpp
Labels: unit test

#3594 Initializes receive and completion times to always hold a valid value…
  nano/node/socket.cpp
  nano/node/socket.hpp
Labels: bug

#3554 Introduce support for binding sockets to ports picked by the OS
  nano/core_test/fakes/work_peer.hpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/socket.cpp
  nano/core_test/websocket.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/distributed_work.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/socket.hpp
  nano/node/transport/udp.cpp
  nano/node/websocket.hpp
Labels: websockets, networking

#3576 Introduce support for and use automatic port binding in `rpc_test` unit tests
  nano/node/ipc/ipc_server.cpp
  nano/node/ipc/ipc_server.hpp
  nano/rpc/rpc.cpp
  nano/rpc/rpc.hpp
  nano/rpc/rpc_request_processor.cpp
  nano/rpc/rpc_request_processor.hpp
  nano/rpc_test/rpc.cpp
Labels: unit test, networking

#3610 Fixing slow_test compile error.
  nano/slow_test/node.cpp
Labels: bug

#3611 Disable intermittently failing UTs
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
Labels: bug, unit test

#3607 Disable intermittently failing UT `confirmation_height.election_winner_details_clearing`
  nano/core_test/confirmation_height.cpp
Labels: bug, unit test

#3604 Disable intermittently failing UT `active_transactions.inactive_votes_cache_fork`
  nano/core_test/active_transactions.cpp
Labels: bug, unit test

#3602 Disable intermittently failing UT `ledger_walker.ladder_geometry`
  nano/core_test/ledger_walker.cpp
Labels: bug, unit test

#3586 Update images for README and QT wallet to be new symbol
  Nano.icns
  Nano.ico
  images/logo.svg
  logo.png
Labels: qt wallet, non-functional change

#3623 Modifies the silent connection checker to inspect sever-side incoming messages only
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/core_test/socket.cpp
  nano/lib/config.hpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
Labels: bug
