Repository nanocurrency/nano-node, pull requests merged in 2021-07, with the labels that each got.

#3359 Moving socket type entirely in to nano::socket class.
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/network.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: non-functional change

#3364 Message sink interface
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/websocket.cpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: enhancement

#3370 Remove tautology: send_buffer was called on channel so it must be non-null.
  nano/node/transport/tcp.cpp
Labels: non-functional change

#3372 Disable compilation/usage of diskhash on Windows
  CMakeLists.txt
  nano/core_test/ledger_walker.cpp
  nano/node/CMakeLists.txt
  nano/node/ledger_walker.cpp
  nano/node/ledger_walker.hpp
  nano/test_common/system.cpp
  nano/test_common/system.hpp
Labels: build-error

#3373 Remove load_test from github CI
  ci/test.sh
Labels: unit test

#3368 Convert static network id code to instance code
  nano/core_test/message.cpp
  nano/core_test/network.cpp
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/nano_node/entry.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/nodeconfig.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/utility.cpp
  nano/test_common/system.cpp
  nano/test_common/testutil.cpp
Labels: quality improvements

#3377 Removing deprecated lmdb_max_dbs config option
  nano/core_test/node.cpp
  nano/core_test/toml.cpp
  nano/core_test/wallets.cpp
  nano/lib/lmdbconfig.cpp
  nano/lib/lmdbconfig.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: database, deprecation, toml

#3380 Adding 'explicit' specifier to uint256_constructor for strings.
  nano/lib/numbers.hpp
  nano/node/cli.cpp
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug, enhancement

#3055 Weekly Coverage Runs to coveralls.io
  .github/workflows/beta_artifacts.yml
  .github/workflows/coverage.yml
  .github/workflows/develop.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/release_tests.yml
  .github/workflows/rocksdb_release_tests.yml
  .github/workflows/rocksdb_tests.yml
  .github/workflows/test_network_artifacts.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  README.md
  ci/actions/deploy.sh
  ci/actions/linux/install_deps.sh
  ci/actions/windows/build.ps1
  ci/build-centos.sh
  ci/build-travis.sh
  ci/check-cmake-format.sh
  ci/cmake-format-all.sh
  ci/test.sh
  cmake/Modules/CoverageTest.cmake
  coverage/CMakeLists.txt
  docker/ci/Dockerfile-gcc
Labels: static-analysis, tool, universe

#3383 Cleaning up genesis_dev constants
  nano/core_test/active_transactions.cpp
  nano/core_test/block_store.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/election_scheduler.cpp
  nano/core_test/frontiers_confirmation.cpp
  nano/core_test/gap_cache.cpp
  nano/core_test/ledger.cpp
  nano/core_test/ledger_walker.cpp
  nano/core_test/network.cpp
  nano/core_test/network_filter.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/system.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/uint256_union.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/voting.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/core_test/websocket.cpp
  nano/load_test/entry.cpp
  nano/nano_node/entry.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/store_partial.hpp
  nano/slow_test/node.cpp
  nano/test_common/system.cpp
  nano/test_common/testutil.cpp
  nano/test_common/testutil.hpp
Labels: enhancement

#3384 Update CMakeLists.txt
  coverage/CMakeLists.txt
Labels: static-analysis, tool, universe

#3387 wallet_pending and accounts_pending handle empty results differently
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: bug, rpc

#3396 Remove wezrule from security policy
  SECURITY.md
Labels: non-functional change, routine

#3395 update clang-format checks for full history
  .github/workflows/analyzers.yml
  ci/check-commit-format.sh
  nano/core_test/telemetry.cpp
Labels: tool, universe

#3392 Update RPC & QT Wallet to the new units #3386
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/qt/qt.cpp
  nano/qt/qt.hpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
Labels: deprecation, qt wallet, rpc, semantic

#3405 Fix typo on CLI online_weight_clear success message
  nano/node/cli.cpp
Labels: non-functional change

#3403 Changing nano::block_store_partial to hold nano::ledger_constants by reference
  nano/core_test/block_store.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/qt_test/qt.cpp
  nano/secure/ledger.cpp
  nano/secure/store.hpp
  nano/secure/store_partial.hpp
  nano/slow_test/node.cpp
Labels: quality improvements

#3407 remove errexit ghcr.io has some edgecase rules, and isnt required for…
  ci/build-docker-image.sh
Labels: universe

#3406 Converting sever static initializations of nano::network_params to references
  nano/core_test/wallet.cpp
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: quality improvements
