Repository nanocurrency/nano-node, pull requests merged in 2021-03, with the labels that each got.

#3106 TSAN error in confirmation height unbounded
  nano/node/confirmation_height_unbounded.cpp
Labels: bug, sanitizers

#2629 Make bootstrap_processor.process_state more robust under tsan
  nano/core_test/bootstrap.cpp
Labels: unit test

#3110 Replace private_key uses with raw_key
  nano/core_test/block.cpp
  nano/core_test/block_store.cpp
  nano/core_test/cli.cpp
  nano/core_test/uint256_union.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/crypto_lib/CMakeLists.txt
  nano/crypto_lib/secure_memory.cpp
  nano/crypto_lib/secure_memory.hpp
  nano/lib/numbers.cpp
  nano/lib/numbers.hpp
  nano/load_test/entry.cpp
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/wallet_value.cpp
  nano/node/lmdb/wallet_value.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/slow_test/node.cpp
Labels: non-functional change

#3116 Move related blockstore functions together
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: non-functional change

#3050 Update CLI commands missing checks for reading config and overrides
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: cli

#2532 Add histogram support to stats
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
Labels: enhancement

#3117 Remove lazy destinations check
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
Labels: quality improvements

#3123 Update missing nano::mutex changes
  nano/lib/stats.cpp
  nano/lib/stats.hpp
Labels: build-error

#3120 Increase default max LMDB size
  nano/lib/lmdbconfig.hpp
Labels: configuration default change

#3042 Make fuzz_buffer compile again after message_parser changes
  nano/fuzzer_test/fuzz_buffer.cpp
Labels: build-error

#3103 Bootstrap tests improvements
  nano/core_test/bootstrap.cpp
  nano/core_test/node.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: quality improvements, unit test

#3016 Add option to include votes in confirmation websocket
  nano/core_test/confirmation_height.cpp
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/ipc/ipc_broker.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node_observers.hpp
  nano/node/wallet.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/qt/qt.cpp
Labels: documentation, websockets

#3079 Republish difficulty updates to elections
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/blockprocessor.cpp
  nano/node/election.cpp
  nano/node/wallet.cpp
Labels: functionality quality improvements

#3125 Inactive votes cache timestamp
  nano/core_test/active_transactions.cpp
  nano/core_test/memory_pool.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/election.cpp
  nano/node/voting.cpp
Labels: quality improvements

#3130 Database final votes support
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/node/cli.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
  nano/secure/ledger.cpp
Labels: database, documentation

#3129 Improve elections related tests
  nano/core_test/active_transactions.cpp
  nano/core_test/election.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
Labels: unit test

#3118 Disable peers banning after frontiers confirmation
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap_legacy.cpp
Labels: beta testing wanted, quality improvements

#3098 Use frontiers age option for frontier_req client
  nano/core_test/node.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/bootstrap/bootstrap_legacy.hpp
  nano/node/node.cpp
  nano/node/nodeconfig.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: beta testing wanted, functionality quality improvements, networking

#3148 This decreases the confirm_req_batches_max from 20 to 2
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/toml.cpp
  nano/node/active_transactions.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/confirmation_solicitor.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: performance, toml

#3135 Update beta genesis and magic number from V22.0DB10 reset
  nano/secure/common.cpp
Labels: routine

#3107 Check open file descriptor limit, warn if low
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_node/daemon.cpp
Labels: quality improvements

#3146 clear_send_ids in vacuum/snapshot is using wrong txn object
  nano/node/cli.cpp
Labels: bug

#3152 Optionally send confirmed frontiers
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/common.cpp
  nano/node/common.hpp
Labels: enhancement, networking

#3154 Throttled removal of rep crawler targets
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
  nano/node/vote_processor.cpp
  nano/node/vote_processor.hpp
Labels: functionality quality improvements

#3157 Update live bootstrap weights.
  rep_weights_live.bin
Labels: routine

#3149 Remove bootstrap restarting code
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/bootstrap/bootstrap_legacy.hpp
  nano/node/json_handler.cpp
Labels: performance

#3100 Reverse store iterator and selector for last record
  nano/core_test/block_store.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_iterator.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_iterator.hpp
  nano/secure/blockstore.hpp
  nano/secure/blockstore_partial.hpp
Labels: enhancement

#3155 Limit bulk pull processing for possible existing blocks
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
Labels: quality improvements

#3108 Add gap pending epoch open blocks to unchecked
  nano/core_test/ledger.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/json_handler.cpp
  nano/secure/blockstore_partial.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: performance
