Repository nanocurrency/nano-node, pull requests merged in 2021-08, with the labels that each got.

#3410 Network selector
  nano/node/cli.cpp
  nano/node/nodeconfig.cpp
Labels: bug, cli

#3414 Removing legacy path from nano::working_path
  nano/secure/utility.cpp
  nano/secure/utility.hpp
Labels: quality improvements

#3415 test_common not required for qt only for qt_test
  CMakeLists.txt
Labels: build-error

#3418 Remove qt_system target we dont need it or use it
  CMakeLists.txt
Labels: build-error

#3422 Fix daemon_config active_network.
  nano/core_test/toml.cpp
  nano/load_test/entry.cpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/cli.cpp
  nano/node/daemonconfig.cpp
  nano/node/daemonconfig.hpp
  nano/node/node.cpp
Labels: bug

#3416 Update major version to 23 and add pre release version 99
  CMakeLists.txt
Labels: routine

#3428 Fixing QT ratio selection
  nano/qt/qt.cpp
Labels: bug
