Repository nanocurrency/nano-node, pull requests merged in 2021-11, with the labels that each got.

#3032 Secure Websocket support and certificate config improvements
  nano/core_test/toml.cpp
  nano/lib/CMakeLists.txt
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/lib/tlsconfig.cpp
  nano/lib/tlsconfig.hpp
  nano/nano_node/daemon.cpp
  nano/nano_rpc/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
  nano/node/websocket_stream.cpp
  nano/node/websocket_stream.hpp
  nano/node/websocketconfig.hpp
  nano/rpc/rpc.cpp
  nano/rpc/rpc_secure.cpp
  nano/rpc/rpc_secure.hpp
Labels: documentation, websockets, toml

#3540 Remove election limiter from call site in confirmation height processor
  nano/node/active_transactions.cpp
Labels: enhancement

#3412 Implement "accounts_representatives" RPC (#3409)
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, documentation, rpc

#3546 Fix crash in nano_wallet when ran with --config option
  nano/nano_wallet/entry.cpp
Labels: bug, qt wallet

#3545 Fix conflicts.add_two unit test
  nano/core_test/conflicts.cpp
  nano/rpc_test/rpc.cpp
Labels: unit test

#3550 Fixes/splits vote_processor.no_broadcast_local
  nano/core_test/vote_processor.cpp
Labels: bug

#2921 Deadline timer cleanup
  nano/core_test/socket.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
Labels: quality improvements

#3548 Adding duration to vote timestamps.
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/message.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/websocket.cpp
  nano/nano_node/entry.cpp
  nano/node/vote_processor.cpp
  nano/node/voting.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: enhancement

#3560 Disable intermittently failing UT `rpc.send_epoch_2`
  nano/rpc_test/rpc.cpp
Labels: bug, unit test

#3558 Disable intermittently failing UT `bootstrap_processor.push_diamond`
  nano/core_test/bootstrap.cpp
Labels: bug, unit test

#3556 Disable intermittently failing UT `node.vote_by_hash_republish`
  nano/core_test/node.cpp
Labels: bug, unit test

#3563 Fix a couple issues found with TSAN and add a suppression for Crypto++
  nano/core_test/bootstrap.cpp
  nano/core_test/uint256_union.cpp
  tsan_suppressions
Labels: bug

#3564 Improve and simplify a number of network limiters
  nano/boost/asio/ip/network_v6.hpp
  nano/core_test/network.cpp
  nano/core_test/socket.cpp
  nano/lib/config.hpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/nodeconfig.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.cpp
  nano/node/transport/transport.hpp
  nano/node/transport/udp.cpp
  nano/node/transport/udp.hpp
Labels: enhancement

#3565 Update live rep weights file for V23
  rep_weights_live.bin
Labels: routine

#3566 Update beta rep weights file for V23.0
  rep_weights_beta.bin
Labels: routine

#3569 Refine election scheduler lock.
  nano/node/election_scheduler.cpp
Labels: quality improvements
