Repository nanocurrency/nano-node, pull requests merged in 2021-09, with the labels that each got.

#3442 Remove node_id_handshake_sockets as unneeded.
  nano/core_test/node.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: bug

#3445 Fix fill_keepalive_self so the low index entries aren't clobbered.
  nano/core_test/network.cpp
  nano/node/network.cpp
Labels: bug

#3446 Have CMake copy Flatbuffers schema files to output dir to simplify dev
  nano/ipc_flatbuffers_lib/CMakeLists.txt
  nano/node/ipc/flatbuffers_handler.cpp
Labels: ipc

#3459 Fix a crash that would sometimes happen in debug builds at handshakes
  nano/node/transport/tcp.cpp
Labels: bug

#3438 Replace "pending" with "receivable"/"ready to receive" in node logs (#3411)
  nano/node/wallet.cpp
Labels: semantic, logging

#3460 Make code formatting compliant with clang-format 12
  nano/core_test/work_pool.cpp
  nano/crypto_lib/secure_memory.cpp
  nano/lib/config.hpp
  nano/lib/rpcconfig.hpp
  nano/lib/threading.hpp
  nano/lib/utility.cpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/active_transactions.cpp
  nano/node/common.cpp
  nano/node/repcrawler.cpp
  nano/node/websocket.cpp
  nano/secure/common.cpp
  nano/secure/ledger.cpp
Labels: non-functional change

#3465 Fix broken cli commands: wallet_create, wallet_list (issue #3447), diagnostics (issue #3452) and other CLI commands
  nano/nano_node/entry.cpp
  nano/node/cli.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  systest/.gitignore
  systest/RUNALL
  systest/cli_wallet_create.sh
  systest/node_initialize.sh
  systest/set_bandwidth_params.sh
Labels: bug, documentation, cli

#3462 Improve clang-format detection & enforcement
  .clang-format
  .gitignore
  ci/check-commit-format.sh
  ci/clang-format-all.sh
  ci/detect-clang-format.sh
  ci/git-clang-format.py
  ci/update-clang-format
  nano/node/transport/tcp.cpp
Labels: non-functional change

#3469 Fix Windows build
  nano/lib/utility.cpp
Labels: build-error

#3477 Fix for unit test rpc.epoch_upgrade #3476
  nano/rpc_test/rpc.cpp
Labels: unit test

#3479 Fix unit test case node.search_pending_pruned
  nano/core_test/node.cpp
Labels: unit test

#3468 Add systests to CI and fix for rocksdb mode (issue #3447) (issue #3452)
  ci/test.sh
  systest/RUNALL
  systest/cli_wallet_create.sh
  systest/node_initialize.sh
  systest/set_bandwidth_params.sh
Labels: unit test

#3437 Replace "pending" with "receivable"/"ready to receive" in QT wallet (#3411)
  nano/qt/qt.cpp
Labels: qt wallet, semantic

#3470 Fix cmake-format-all.sh script + friendlier xargs usage
  ci/check-cmake-format.sh
  ci/clang-format-all.sh
  ci/cmake-format-all.sh
  ci/detect-cmake-format.sh
Labels: non-functional change

#3486 Redesign CI format check/update scripts according to review
  .github/workflows/analyzers.yml
  ci/check-cmake-format.sh
  ci/check-commit-format.sh
  ci/clang-format-all.sh
  ci/clang-format-check.sh
  ci/clang-format-do.sh
  ci/cmake-format-all.sh
  ci/cmake-format-check.sh
  ci/cmake-format-do.sh
  ci/common.sh
  ci/detect-clang-format.sh
  ci/detect-cmake-format.sh
  ci/impl/clang-format.sh
  ci/impl/cmake-format.sh
  ci/impl/common.sh
Labels: non-functional change
