Repository nanocurrency/nano-node, pull requests merged in 2021-02, with the labels that each got.

#2871 Combine alarm and worker threads into a pool
  nano/boost/asio/steady_timer.hpp
  nano/core_test/bootstrap.cpp
  nano/core_test/locks.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/processor_service.cpp
  nano/core_test/telemetry.cpp
  nano/core_test/utility.cpp
  nano/core_test/voting.cpp
  nano/core_test/wallets.cpp
  nano/lib/CMakeLists.txt
  nano/lib/alarm.cpp
  nano/lib/alarm.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/lib/worker.cpp
  nano/lib/worker.hpp
  nano/nano_node/daemon.cpp
  nano/nano_node/entry.cpp
  nano/nano_wallet/entry.cpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/distributed_work.cpp
  nano/node/gap_cache.cpp
  nano/node/ipc/ipc_server.cpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/portmapping.cpp
  nano/node/repcrawler.cpp
  nano/node/signatures.cpp
  nano/node/signatures.hpp
  nano/node/socket.cpp
  nano/node/telemetry.cpp
  nano/node/telemetry.hpp
  nano/node/testing.cpp
  nano/node/testing.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/udp.cpp
  nano/node/wallet.cpp
  nano/qt/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#3093 Process async test should use state block
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: unit test

#3081 Revert coroutine changes for core & rpc_test
  CMakeLists.txt
  ci/cmake-format-all.sh
  nano/load_test/CMakeLists.txt
  nano/node/CMakeLists.txt
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.hpp
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/rpc.cpp
Labels: non-functional change

#3077 Add debug/release_assert overloads which output error message strings
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_txn.cpp
  nano/secure/blockstore_partial.hpp
Labels: debug

#3038 Remove epoch2 started code
  nano/core_test/block.cpp
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/message.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/network_filter.cpp
  nano/core_test/node.cpp
  nano/core_test/peer_container.cpp
  nano/core_test/websocket.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/repcrawler.cpp
  nano/node/telemetry.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.cpp
  nano/node/transport/udp.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
  nano/test_common/telemetry.cpp
Labels: non-functional change

#3096 Add missing include(msvc2017)
  nano/lib/utility.cpp
Labels: build-error

#2758 Store whole block in confirmation height processor queue
  nano/core_test/confirmation_height.cpp
  nano/lib/numbers.hpp
  nano/nano_node/entry.cpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/node.cpp
  nano/slow_test/node.cpp
Labels: quality improvements

#3102 Fix test rpc.confirmation_active
  nano/node/testing.cpp
Labels: unit test

#3101 Add worker task queue count to the stats
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/node.cpp
Labels: quality improvements
