Repository nanocurrency/nano-node, pull requests merged in 2022-08, with the labels that each got.

#3881 Fix setting the tag in the beta workflow
  .github/workflows/beta_artifacts.yml
Labels: exclude from changelog

#3882 Increase the macOS version for GitHub hosted runners
  .github/workflows/beta_artifacts.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
  .github/workflows/tests.yml
Labels: exclude from changelog

#3884 Enable setting the pre-release version at build time
  .github/workflows/beta_artifacts.yml
  CMakeLists.txt
  ci/actions/linux/docker-impl/docker-common.sh
  ci/actions/windows/build.ps1
  ci/build-deploy.sh
Labels: ci/cd, exclude from changelog

#3861 Fix & refactor `bootstrap_server`
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/bootstrap/message_deserializer.cpp
  nano/node/bootstrap/message_deserializer.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/transport.cpp
Labels: bug, quality improvements

#3921 Helper function to create a node out of the network
  nano/test_common/network.cpp
  nano/test_common/network.hpp
Labels: exclude from changelog

#3920 Remove UDP support from request_aggregator tests
  nano/core_test/request_aggregator.cpp
Labels: exclude from changelog

#3913 Remove UDP support from confirmation_solicitor tests
  nano/core_test/confirmation_solicitor.cpp
Labels: exclude from changelog

#3917 Remove UDP support from a qt test
  nano/qt_test/qt.cpp
Labels: exclude from changelog

#3918 Remove UDP support from the RPC tests
  nano/rpc_test/rpc.cpp
Labels: exclude from changelog

#3907 Improved `inactive_vote_cache`
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/memory_pool.cpp
  nano/core_test/vote_cache.cpp
  nano/core_test/voting.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/common.cpp
  nano/node/election.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/vote_cache.cpp
  nano/node/vote_cache.hpp
  nano/slow_test/vote_cache.cpp
Labels: enhancement

#3916 Remove UDP support from telemetry tests
  nano/core_test/telemetry.cpp
Labels: unit test, removal, exclude from changelog

#3919 Remove UDP support from node and websocket tests
  nano/core_test/node.cpp
  nano/core_test/websocket.cpp
  nano/slow_test/node.cpp
Labels: unit test, removal, exclude from changelog

#3905 Fix `confirm_election_by_request` test
  nano/core_test/active_transactions.cpp
  nano/test_common/system.cpp
  nano/test_common/testutil.hpp
Labels: unit test

#3906 Fix `epoch_conflict_confirm` test
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/test_common/testutil.cpp
  nano/test_common/testutil.hpp
Labels: unit test

#3930 Fix the tag numbering by using the correct sorting format
  ci/actions/dev-build-tag-gen.sh
Labels: ci/cd, exclude from changelog
