Repository nanocurrency/nano-node, pull requests merged in 2022-02, with the labels that each got.

#3679 Investigate and fix some of the disabled unit tests
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/node.cpp
  nano/node/online_reps.hpp
  nano/node/repcrawler.hpp
Labels: bug, unit test

#3643 Fix telemetry rpc getting stuck if all nodes have bandwidth set to 0
  nano/core_test/telemetry.cpp
  nano/node/telemetry.cpp
Labels: bug

#3696 Fix `ipc_client::async_resolve` when given invalid endpoint
  nano/core_test/ipc.cpp
  nano/lib/ipc_client.cpp
Labels: bug

#3700 Add optional offset parameter for the receivable RPC
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, documentation, rpc

#3717 Encapsulate detail_to_string with uint32_t overload.
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/transport/transport.cpp
Labels: enhancement

#3698 Add option to include sideband info of confirmed blocks in websocket messages
  nano/core_test/websocket.cpp
  nano/node/websocket.cpp
  nano/node/websocket.hpp
Labels: documentation, websockets

#3719 Removes the nano::unchecked_info::confirmed member.
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement

#3723 Fix unchecked_map destructor.
  nano/node/unchecked_map.cpp
  nano/node/unchecked_map.hpp
Labels: bug

#3725 Add class description to mostly of bootstrap classes
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_bulk_push.hpp
  nano/node/bootstrap/bootstrap_connections.hpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/node/bootstrap/bootstrap_legacy.hpp
  nano/node/bootstrap/bootstrap_server.hpp
Labels: documentation

#3730 Inactive cache information to string (easy review)
  nano/node/CMakeLists.txt
  nano/node/active_transactions.hpp
  nano/node/inactive_cache_information.cpp
  nano/node/inactive_cache_information.hpp
  nano/node/inactive_cache_status.cpp
  nano/node/inactive_cache_status.hpp
Labels: quality improvements, non-functional change

#3733 Comment and warning about epoch blocks
  nano/lib/epoch.hpp
Labels: quality improvements

#3691 Fix unit tests `election.quorum_minimum_flip_*`
  nano/core_test/election.cpp
Labels: bug, unit test

#3732 Fix unit test `election_scheduler.no_vacancy`
  nano/core_test/election_scheduler.cpp
Labels: bug, unit test

#3738 Fix for unit test unchecked.multiple_get, do not use store.count()
  nano/core_test/block_store.cpp
Labels: unit test

#3741 Fix confirmation_height.election_winner_details_clearing
  nano/core_test/confirmation_height.cpp
Labels: unit test

#3728 Remove coupling of block processor and unchecked_map on unchecked_info::modified.
  nano/core_test/gap_cache.cpp
  nano/core_test/node.cpp
  nano/core_test/unchecked_map.cpp
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/unchecked_map.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: enhancement

#3742 Add comments to class nano::prioritization
  nano/node/prioritization.cpp
  nano/node/prioritization.hpp
Labels: documentation, non-functional change

#3729 Remove coupling between nano::state_block_signature_verification and nano::unchecked_info.
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/state_block_signature_verification.cpp
  nano/node/state_block_signature_verification.hpp
Labels: enhancement
