Repository nanocurrency/nano-node, pull requests merged in 2022-01, with the labels that each got.

#3601 Display node startup time for easy access to up time without RPC access
  nano/nano_node/daemon.cpp
Labels: enhancement

#3649 Modifies the silent connection checker to inspect sever-side incoming messages only (develop branch version)
  nano/core_test/bootstrap.cpp
  nano/core_test/network.cpp
  nano/core_test/socket.cpp
  nano/lib/config.hpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/socket.cpp
  nano/node/socket.hpp
  nano/node/transport/tcp.cpp
Labels: bug

#3650 Add basic contributing file with links to docs for details
  CONTRIBUTING.md
Labels: non-functional change

#3656 Allow overriding initial peering DNS by environment variable
  nano/node/nodeconfig.cpp
Labels: documentation

#3660 Update some sections, fix headers and adjust PR finding approach to i…
  util/changelog.py
Labels: routine

#3655 Remove json config code
  nano/core_test/logger.cpp
  nano/core_test/node.cpp
  nano/core_test/work_pool.cpp
  nano/lib/config.cpp
  nano/lib/config.hpp
  nano/lib/diagnosticsconfig.cpp
  nano/lib/diagnosticsconfig.hpp
  nano/lib/jsonconfig.hpp
  nano/lib/rpcconfig.cpp
  nano/lib/rpcconfig.hpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/daemonconfig.cpp
  nano/node/daemonconfig.hpp
  nano/node/ipc/ipc_config.cpp
  nano/node/ipc/ipc_config.hpp
  nano/node/logging.cpp
  nano/node/logging.hpp
  nano/node/node_rpc_config.cpp
  nano/node/node_rpc_config.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/openclconfig.cpp
  nano/node/openclconfig.hpp
  nano/node/websocketconfig.cpp
  nano/node/websocketconfig.hpp
  nano/rpc_test/rpc.cpp
Labels: removal

#3663 Fixing slow_test store.pruned_load.
  nano/slow_test/node.cpp
Labels: unit test

#3671 Setting version for release.
  CMakeLists.txt
Labels: routine

#3670 Update live rep weights file for V23
  rep_weights_live.bin
Labels: routine

#3667 Fix confirmation_height slow_test cases
  nano/slow_test/node.cpp
Labels: unit test

#3675 Adds the code-inspector script
  .github/workflows/analyzers.yml
  ci/build-travis.sh
  ci/code-inspector-check.sh
  ci/impl/code-inspector.sh
Labels: tool

#3677 Fix slow test telemetry.all_peers_use_single_request_cache
  nano/slow_test/node.cpp
Labels: unit test

#3654 Move semantics fix in the asio header
  nano/lib/asio.hpp
Labels: non-functional change

#3662 Use the default peering port for daemon start up
  nano/nano_node/daemon.cpp
  nano/node/node.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: networking

#3629 Disable batch of intermittently failing unit tests
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/distributed_work.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/qt_test/qt.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.hpp
Labels: bug, unit test

#3620 Fix --rpcconfig cli option
  nano/nano_node/entry.cpp
Labels: needs unit tests

#3687 Fix `node.pruning_*` unit tests
  nano/core_test/node.cpp
Labels: bug, unit test

#3694 Do not ignore socket errors
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/socket.cpp
Labels: bug
