Repository nanocurrency/nano-node, pull requests merged in 2022-05, with the labels that each got.

#3806 `open_burn_account` errors and comments
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/secure/common.hpp
Labels: enhancement, logging

#3809 Bootstrap cleanup
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_bulk_push.hpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_frontier.hpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_lazy.hpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/bootstrap/bootstrap_legacy.hpp
Labels: enhancement

#3811 Adding unhandled case for message_visitor
  nano/node/common.hpp
  nano/node/transport/inproc.cpp
Labels: enhancement

#3813 Remove vote-by-block support from vote class
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/message.cpp
  nano/core_test/message_parser.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/voting.cpp
  nano/core_test/websocket.cpp
  nano/node/active_transactions.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/gap_cache.cpp
  nano/node/network.cpp
  nano/node/repcrawler.cpp
  nano/node/voting.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
  nano/slow_test/node.cpp
Labels: enhancement

#3816 Node ID persistence
  nano/core_test/node.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: functionality quality improvements

#3828 V23.1 Cumulative patch
  nano/core_test/node.cpp
  nano/node/active_transactions.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/bootstrap/bootstrap_server.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/secure/store/unchecked_store_partial.hpp
Labels: bug
