Repository nanocurrency/nano-node, pull requests merged in 2022-04, with the labels that each got.

#3746 Introduce `ledger.rollback_failed` stat counter
  nano/core_test/confirmation_height.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/blockprocessor.cpp
Labels: quality improvements

#3745 Fix unit test `confirmation_height.conflict_rollback_cemented`
  nano/core_test/confirmation_height.cpp
  nano/lib/stats.cpp
  nano/lib/stats.hpp
  nano/node/blockprocessor.cpp
  nano/secure/ledger.hpp
  nano/test_common/system.hpp
Labels: bug, unit test

#3784 Add db backend namespaces
  nano/node/lmdb/account_store.cpp
  nano/node/lmdb/account_store.hpp
  nano/node/lmdb/block_store.cpp
  nano/node/lmdb/block_store.hpp
  nano/node/lmdb/confirmation_height_store.cpp
  nano/node/lmdb/confirmation_height_store.hpp
  nano/node/lmdb/final_vote_store.cpp
  nano/node/lmdb/final_vote_store.hpp
  nano/node/lmdb/frontier_store.cpp
  nano/node/lmdb/frontier_store.hpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/online_weight_store.cpp
  nano/node/lmdb/online_weight_store.hpp
  nano/node/lmdb/peer_store.cpp
  nano/node/lmdb/peer_store.hpp
  nano/node/lmdb/pending_store.cpp
  nano/node/lmdb/pending_store.hpp
  nano/node/lmdb/pruned_store.cpp
  nano/node/lmdb/pruned_store.hpp
  nano/node/lmdb/unchecked_store.cpp
  nano/node/lmdb/unchecked_store.hpp
  nano/node/lmdb/version_store.cpp
  nano/node/lmdb/version_store.hpp
  nano/node/node.hpp
  nano/node/rocksdb/account_store.cpp
  nano/node/rocksdb/account_store.hpp
  nano/node/rocksdb/block_store.cpp
  nano/node/rocksdb/block_store.hpp
  nano/node/rocksdb/confirmation_height_store.cpp
  nano/node/rocksdb/confirmation_height_store.hpp
  nano/node/rocksdb/final_vote_store.cpp
  nano/node/rocksdb/final_vote_store.hpp
  nano/node/rocksdb/frontier_store.cpp
  nano/node/rocksdb/frontier_store.hpp
  nano/node/rocksdb/online_weight_store.cpp
  nano/node/rocksdb/online_weight_store.hpp
  nano/node/rocksdb/peer_store.cpp
  nano/node/rocksdb/peer_store.hpp
  nano/node/rocksdb/pending_store.cpp
  nano/node/rocksdb/pending_store.hpp
  nano/node/rocksdb/pruned_store.cpp
  nano/node/rocksdb/pruned_store.hpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/rocksdb_iterator.hpp
  nano/node/rocksdb/rocksdb_txn.hpp
  nano/node/rocksdb/unchecked_store.cpp
  nano/node/rocksdb/unchecked_store.hpp
  nano/node/rocksdb/version_store.cpp
  nano/node/rocksdb/version_store.hpp
Labels: enhancement

#3787 Moves the LDMB table handles to their respective type of store class
  nano/core_test/block_store.cpp
  nano/node/lmdb/account_store.hpp
  nano/node/lmdb/block_store.hpp
  nano/node/lmdb/confirmation_height_store.hpp
  nano/node/lmdb/final_vote_store.hpp
  nano/node/lmdb/frontier_store.hpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/online_weight_store.hpp
  nano/node/lmdb/peer_store.hpp
  nano/node/lmdb/pending_store.hpp
  nano/node/lmdb/pruned_store.hpp
  nano/node/lmdb/unchecked_store.hpp
Labels: enhancement

#3786 Adding details to the DB commit () release_asserts
  nano/node/lmdb/lmdb_txn.cpp
  nano/node/rocksdb/rocksdb_txn.cpp
Labels: quality improvements

#3776 Simplify unit test node.bootstrap_confirm_frontiers
  nano/core_test/node.cpp
Labels: unit test

#3788 Adds the quick_tests target to CMake
  CMakeLists.txt
Labels: enhancement, unit test, tool

#3789 Changes the accounts_representatives RPC to return per account response
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: rpc

#3791 Changes the accounts_frontiers RPC to return per account results
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: rpc

#3790 Changes the accounts_balances RPC to return per account results
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: rpc

#3644 This demonstrates a speedup in confirmation rate during initial boots…
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/toml.cpp
  nano/node/confirmation_solicitor.cpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/transport/tcp.hpp
  nano/node/transport/transport.hpp
Labels: enhancement
