Repository nanocurrency/nano-node, pull requests merged in 2022-09, with the labels that each got.

#3898 Fix bootstrap serving threads regression
  nano/node/bootstrap/bootstrap_server.cpp
Labels: bug

#3941 Convert a couple of placeholder inproc channels to fake channels
  nano/core_test/node.cpp
Labels: exclude from changelog

#3936 Change TCP channels to fake type (core_test/websocket.cpp)
  nano/core_test/websocket.cpp
Labels: unit test, exclude from changelog

#3935 Change TCP channels to fake type (core_test/node.cpp)
  nano/core_test/node.cpp
Labels: unit test, exclude from changelog

#3937 Adding comments to test local_votes_cache_fork and documenting a race
  nano/core_test/node.cpp
Labels: unit test, exclude from changelog

#3955 Replace random_access with sequenced in `vote_cache`
  nano/node/vote_cache.cpp
  nano/node/vote_cache.hpp
Labels: enhancement

#3959 Bugfix: properly handle refused bootstrap connection
  nano/node/bootstrap/bootstrap_server.cpp
Labels: bug

#3956 Replace random_access with sequenced in `unchecked_map`
  nano/node/unchecked_map.cpp
  nano/node/unchecked_map.hpp
Labels: enhancement

#3957 Replace random_access with sequenced in `active_transactions`
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
Labels: enhancement

#3896 Fetch dependencies from APT repository when building Linux version of the node
  .github/workflows/tests.yml
  ci/actions/linux/docker-impl/docker-common.sh
  ci/actions/linux/ghcr_push.sh
  ci/actions/linux/install_deps.sh
  docker/ci/Dockerfile-base
  docker/ci/Dockerfile-clang
  docker/ci/Dockerfile-clang-6
  docker/ci/Dockerfile-gcc
  docker/node/Dockerfile
Labels: ci/cd, exclude from changelog
