Repository nanocurrency/nano-node, pull requests merged in 2022-03, with the labels that each got.

#3749 Fix Issue #3748
  nano/lib/CMakeLists.txt
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_node/entry.cpp
  nano/nano_rpc/entry.cpp
Labels: cli

#3718 Sort results of the receivable RPC by block hash in case of equal amounts
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: quality improvements

#3753 Pending to receivable renames
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/wallet.cpp
  nano/core_test/wallets.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
  nano/node/wallet.hpp
  nano/qt/qt.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: documentation

#3702 Add receive_hash option for the blocks_info RPC
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/secure/store.hpp
Labels: enhancement, rpc

#3680 Enable and fix `node.unconfirmed_send` unit test
  nano/core_test/node.cpp
Labels: bug, unit test

#3772 Add function comment for function nano::upgrade_epoch.
  nano/test_common/system.cpp
Labels: non-functional change
