Repository nanocurrency/nano-node, pull requests merged in 2022-07, with the labels that each got.

#3848 Adds a ledger_context class
  nano/core_test/ledger.cpp
  nano/test_common/CMakeLists.txt
  nano/test_common/ledger.cpp
  nano/test_common/ledger.hpp
Labels: enhancement, unit test, exclude from changelog

#3853 Fix `server_socket` close method override
  nano/node/socket.hpp
Labels: bug

#3849 Fix intermittently failing test gap_cache.two_dependencies
  nano/core_test/gap_cache.cpp
Labels: bug

#3850 Fix rocksdb_block_store.tombstone_count
  nano/core_test/block_store.cpp
  nano/secure/store.hpp
Labels: bug

#3852 Expands ability for ledger::is_send to accept any block type
  nano/core_test/ledger.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/test_common/ledger.cpp
  nano/test_common/ledger.hpp
Labels: enhancement

#3812 Extracting nano::bootstrap::block_deserializer class
  nano/core_test/bootstrap.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/block_deserializer.cpp
  nano/node/bootstrap/block_deserializer.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
Labels: enhancement

#3862 Add a build auto setup job for weekly develop builds
  .github/workflows/beta_artifacts.yml
  ci/actions/dev-build-tag-gen.sh
Labels: ci/cd, exclude from changelog

#3864 Add an observer to block_processor that notifies with the output from block processing.
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap.cpp
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
Labels: enhancement

#3866 Add hashing specializations for nano::hash_or_account.
  nano/lib/numbers.hpp
  nano/secure/common.hpp
Labels: enhancement

#3867 Bulk pull ascending flag
  nano/core_test/bootstrap.cpp
  nano/core_test/message.cpp
  nano/lib/config.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.hpp
  nano/node/common.cpp
  nano/node/common.hpp
  nano/node/node.hpp
Labels: protocol change

#3860 Add `populate_backlog` rpc command
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/CMakeLists.txt
  nano/node/backlog_population.cpp
  nano/node/backlog_population.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, documentation, rpc

#3869 Simplifying bootstrap_attempt::mode_text
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
Labels: enhancement

#3865 Bootstrap serving on dedicated thread pool
  nano/core_test/toml.cpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_server.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: quality improvements

#3815 Fix compatibility with Boost 1.78
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/lib/numbers.hpp
Labels: build-error

#3879 Fix the beta build workflow
  .github/workflows/beta_artifacts.yml
  ci/actions/dev-build-tag-gen.sh
Labels: exclude from changelog
