Repository nanocurrency/nano-node, pull requests merged in 2022-11, with the labels that each got.

#3983 Login to ghcr.io using GITHUB_TOKEN
  .github/workflows/develop.yml
Labels: exclude from changelog

#3997 Fix slow_test compilation
  nano/node/active_transactions.hpp
  nano/slow_test/node.cpp
Labels: exclude from changelog

#4003 Fix missing return on non-void function
  nano/node/bandwidth_limiter.cpp
Labels: bug

#4004 Set to use correct backtrace.h directory on newer docker builds
  docker/ci/Dockerfile-clang
Labels: ci/cd, exclude from changelog

#4005 Fix the compiler name set for docker build on install_deps.sh
  ci/actions/linux/install_deps.sh
Labels: ci/cd, exclude from changelog

#3980 Rebalancing buckets the reflect natural transaction ranges.
  nano/core_test/prioritization.cpp
  nano/node/prioritization.cpp
  nano/node/prioritization.hpp
  nano/rpc_test/rpc.cpp
Labels: enhancement
