Repository nanocurrency/nano-node, pull requests merged in 2023-06, with the labels that each got.

#4242 Bump Qt version to 5.15.2 for Windows builds
  ci/actions/windows/configure.bat
  ci/actions/windows/install_deps.ps1
Labels: routine, ci/cd

#4245 Remove the call for signing.ps1 on Windows builds
  ci/actions/windows/build.ps1
Labels: ci/cd

#4252 Extract rollback_competitor function and simplify proces_batch.
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
Labels: enhancement
