Repository nanocurrency/nano-node, pull requests merged in 2023-02, with the labels that each got.

#4093 Fix race condition in unchecked_map
  nano/node/unchecked_map.cpp
Labels: bug

#4097 Fix and document test node.rollback_vote_self
  nano/core_test/node.cpp
Labels: unit test, exclude from changelog

#4099 Increase windows unit test timeout to 150 min
  .github/workflows/unit_tests.yml
Labels: exclude from changelog

#4098 Do not use expose election dummy vote in non election related unit tests
  nano/core_test/node.cpp
Labels: unit test, exclude from changelog

#4103 Fixes an issue where token_bucket::last_refill would update even if there were no tokens to add.
  nano/core_test/utility.cpp
  nano/lib/rate_limiting.cpp
  nano/lib/rate_limiting.hpp
Labels: bug

#4109 Updating unit tests
  nano/core_test/bootstrap.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/election.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
Labels: enhancement, exclude from changelog

#4091 Fix fork publish inactive
  nano/core_test/node.cpp
Labels: unit test

#4110 Bugfix: max counting had reversed polarity, it counted successes not fails
  nano/node/transport/udp.cpp
Labels: bug

#4115 Increase core test timeout to half an hour
  ci/test.sh
Labels: exclude from changelog

#4117 Fix nano::test::blocks_confirm
  nano/core_test/active_transactions.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/rpc_test/rpc.cpp
  nano/test_common/system.cpp
  nano/test_common/system.hpp
  nano/test_common/testutil.cpp
  nano/test_common/testutil.hpp
Labels: exclude from changelog

#4121 Add ledger::head_block query which returns the head block for a given account.
  nano/core_test/ledger.cpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
Labels: enhancement

#4123 Fix missing peering port doc when running --generate_config node
  nano/node/cli.cpp
Labels: bug

#4124 Adding election::behavior getter method, updating references, and adding direct unit test.
  nano/core_test/election.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
Labels: enhancement, exclude from changelog

#3923 Remove UDP support from the peer_container tests
  nano/core_test/peer_container.cpp
  nano/test_common/network.cpp
  nano/test_common/network.hpp
Labels: unit test, removal, exclude from changelog

#4129 Remove wrong and needless code from test system.block_sequence
  nano/slow_test/node.cpp
Labels: unit test, exclude from changelog

#4096 Reenable and fix active_transactions.inactive_votes_cache_multiple_votes
  nano/core_test/active_transactions.cpp
Labels: unit test, exclude from changelog

#4134 Simplify and reduce the nodes needed for test peer_container.list_fanout
  nano/core_test/peer_container.cpp
Labels: unit test, exclude from changelog

#4136 Fix election quorum minimum flip fail
  nano/core_test/election.cpp
Labels: unit test, exclude from changelog

#4135 Fix and improve test channels.fill_random_full
  nano/core_test/peer_container.cpp
Labels: unit test, exclude from changelog

#4138 Fix node deferred dependent elections
  nano/core_test/node.cpp
Labels: unit test, exclude from changelog

#4137 Fix test election.quorum_minimum_confirm_fail
  nano/core_test/election.cpp
Labels: unit test, exclude from changelog

#4139 Convert some election unit test cases to use nano::test::make_final_vote
  nano/core_test/election.cpp
Labels: unit test, exclude from changelog

#4141 Remove message buffer class and its manager class
  nano/core_test/network.cpp
  nano/node/network.cpp
  nano/node/network.hpp
Labels: removal

#4142 Remove the stat types related to the removed UDP functionalities
  nano/lib/stats_enums.hpp
Labels: removal

#4146 Refactor nano::rate_observer.
  nano/test_common/rate_observer.cpp
  nano/test_common/rate_observer.hpp
Labels: enhancement, exclude from changelog

#4147 Converting thread entrypoint from lamda to nano::thread_runner::run.
  nano/lib/threading.cpp
  nano/lib/threading.hpp
Labels: enhancement, exclude from changelog

#4148 Add unchecked_map stats
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/unchecked_map.cpp
  nano/lib/stats_enums.hpp
  nano/node/node.cpp
  nano/node/unchecked_map.cpp
  nano/node/unchecked_map.hpp
Labels: enhancement, documentation

#4149 Cleaning up stat counters for active_transactions.
  nano/core_test/active_transactions.cpp
  nano/lib/stats_enums.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election.cpp
  nano/node/election.hpp
Labels: enhancement

#4152 Generalise active_transaction functions for each election_behavior
  nano/core_test/active_transactions.cpp
  nano/lib/stats_enums.hpp
  nano/lib/utility.hpp
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election_scheduler.cpp
  nano/node/hinted_scheduler.cpp
Labels: enhancement, exclude from changelog

#4111 Optimistic elections
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/optimistic_scheduler.cpp
  nano/core_test/toml.cpp
  nano/lib/config.hpp
  nano/lib/stats_enums.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/lib/utility.hpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/node/election_scheduler.cpp
  nano/node/hinted_scheduler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/optimistic_scheduler.cpp
  nano/node/optimistic_scheduler.hpp
  nano/test_common/chains.cpp
  nano/test_common/chains.hpp
Labels: documentation, major

#4153 Fixing missing break.
  nano/lib/threading.cpp
Labels: exclude from changelog

#4162 Add typedefs for timer units.
  nano/lib/blocks.cpp
  nano/lib/blocks.hpp
  nano/lib/timer.hpp
  nano/node/transport/socket.cpp
  nano/node/transport/socket.hpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.cpp
  nano/secure/common.hpp
Labels: enhancement, exclude from changelog

#4161 Internally check if the block processor needs to drop blocks.
  nano/node/blockprocessor.cpp
Labels: documentation
