Repository nanocurrency/nano-node, pull requests merged in 2023-01, with the labels that each got.

#3646 Fix a shutdown problem in block_processor
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
Labels: bug, exclude from changelog

#4071 Fix submodule names
  .gitmodules
Labels: exclude from changelog

#4074 Add include_only_confirmed option to rpc accounts_balances
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, documentation

#4077 Removing nano::process_return::previous_balance which is assigned but unused.
  nano/secure/common.hpp
  nano/secure/ledger.cpp
Labels: exclude from changelog

#4069 Fix broken minor release counter for beta build tag gen on latest release branch
  ci/actions/dev-build-tag-gen.sh
Labels: ci/cd, exclude from changelog

#4085 Increase core test timeout to 20 minutes
  ci/test.sh
Labels: exclude from changelog

#4084 Pair of commits for setting version to V24.1RC1
  CMakeLists.txt
Labels: exclude from changelog

#4086 Increase the timeout of Windows unit test workflow
  .github/workflows/unit_tests.yml
Labels: exclude from changelog

#4089 Fix unit test rpc history pruning
  nano/rpc_test/rpc.cpp
  nano/test_common/testutil.cpp
Labels: unit test, exclude from changelog

#4092 Add to_string function to nano::stats class for convenience
  nano/lib/stats.cpp
  nano/lib/stats.hpp
Labels: exclude from changelog
