Repository nanocurrency/nano-node, pull requests merged in 2023-04, with the labels that each got.

#4182 Add config classes for ascending bootstrap
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
  nano/node/bootstrap/bootstrap_config.cpp
  nano/node/bootstrap/bootstrap_config.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
Labels: enhancement, configuration default change

#4205 Add throttling functionality to the ascending bootstrapper
  nano/core_test/node.cpp
  nano/lib/stats_enums.hpp
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
  nano/node/bootstrap/bootstrap_config.cpp
  nano/node/bootstrap/bootstrap_config.hpp
Labels: bug, enhancement

#4208 Stats bug fix
  nano/node/unchecked_map.cpp
Labels: exclude from changelog

#4207 Updating throttle class
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
Labels: exclude from changelog

#4206 Promote slow core_test to slow_test
  nano/core_test/node.cpp
  nano/slow_test/node.cpp
Labels: routine, exclude from changelog

#4209 Fixing threading errors from review and TSAN
  nano/node/bootstrap/bootstrap_ascending.cpp
Labels: bug, exclude from changelog

#4210 Simplify the injected dependencies to bootstrap ascending
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
  nano/node/node.cpp
Labels: routine, exclude from changelog

#4212 Fixing more locking issues on bootstrap_ascending::stopped identified by TSAN
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
Labels: exclude from changelog

#4150 Github workflow build cache
  .github/actions/restore-git-mtimes/action.yml
  .github/workflows/unit_tests.yml
  ci/build-ci.sh
Labels: ci/cd, exclude from changelog

#4213 Bootstrap ascending class files split
  nano/core_test/bootstrap_ascending.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
  nano/node/bootstrap_ascending/account_sets.cpp
  nano/node/bootstrap_ascending/account_sets.hpp
  nano/node/bootstrap_ascending/common.hpp
  nano/node/bootstrap_ascending/iterators.cpp
  nano/node/bootstrap_ascending/iterators.hpp
  nano/node/bootstrap_ascending/service.cpp
  nano/node/bootstrap_ascending/service.hpp
  nano/node/bootstrap_ascending/throttle.cpp
  nano/node/bootstrap_ascending/throttle.hpp
  nano/node/json_handler.cpp
  nano/node/network.cpp
  nano/node/node.hpp
  nano/slow_test/bootstrap.cpp
Labels: routine, exclude from changelog

#4211 Convert node-wide request rate limiter to a per-channel outstanding request limiter.
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap_config.hpp
  nano/node/bootstrap_ascending/peer_scoring.cpp
  nano/node/bootstrap_ascending/peer_scoring.hpp
  nano/node/bootstrap_ascending/service.cpp
  nano/node/bootstrap_ascending/service.hpp
  nano/node/network.cpp
Labels: enhancement

#4215 Bootstrap dynamic throttle
  nano/core_test/CMakeLists.txt
  nano/core_test/throttle.cpp
  nano/node/bootstrap/bootstrap_config.cpp
  nano/node/bootstrap/bootstrap_config.hpp
  nano/node/bootstrap_ascending/service.cpp
  nano/node/bootstrap_ascending/service.hpp
  nano/node/bootstrap_ascending/throttle.cpp
  nano/node/bootstrap_ascending/throttle.hpp
Labels: enhancement

#4217 Restore support for stacktrace info
  CMakeLists.txt
  ci/build-ci.sh
  docker/ci/Dockerfile-clang
  nano/lib/CMakeLists.txt
  nano/lib/stacktrace.cpp
  nano/lib/stacktrace.hpp
  nano/lib/utility.cpp
  nano/lib/utility.hpp
  nano/nano_node/daemon.cpp
Labels: routine, exclude from changelog

#4216 Remove the unchecked table code from the store classes
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/core_test/unchecked_map.cpp
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/json_handler.cpp
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/unchecked_store.cpp
  nano/node/lmdb/unchecked_store.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/node/rocksdb/unchecked_store.cpp
  nano/node/rocksdb/unchecked_store.hpp
  nano/node/unchecked_map.cpp
  nano/node/unchecked_map.hpp
  nano/secure/store.cpp
  nano/secure/store.hpp
Labels: database

#4219 Remove live updating bandwidth limits
  nano/core_test/network.cpp
  nano/nano_node/daemon.cpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: bug, removal
