Repository nanocurrency/nano-node, pull requests merged in 2023-03, with the labels that each got.

#4163 Lowering block_processor max transaction duration
  nano/node/nodeconfig.hpp
Labels: enhancement, configuration default change

#4165 Block processor cleanup
  nano/nano_node/entry.cpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/node.cpp
Labels: enhancement, exclude from changelog

#4167 Add batch block processing result observer to block_processor
  nano/core_test/active_transactions.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/core_test/websocket.cpp
  nano/lib/errors.cpp
  nano/lib/errors.hpp
  nano/node/CMakeLists.txt
  nano/node/block_broadcast.cpp
  nano/node/block_broadcast.hpp
  nano/node/blocking_observer.cpp
  nano/node/blocking_observer.hpp
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/epoch_upgrader.cpp
  nano/node/json_handler.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/wallet.cpp
Labels: enhancement, exclude from changelog

#4172 Remove unused variable in nano::transport::tcp_channels::collect_container_info
  nano/node/transport/tcp.cpp
Labels: enhancement, exclude from changelog

#4174 Extracting election_insertion_result class in to its own file.
  nano/node/CMakeLists.txt
  nano/node/active_transactions.hpp
  nano/node/election_insertion_result.hpp
Labels: enhancement, exclude from changelog

#4166 Migrate tests from the old message_parser to test the message_deserializer class
  nano/core_test/CMakeLists.txt
  nano/core_test/message_deserializer.cpp
  nano/core_test/message_parser.cpp
Labels: unit test

#4154 Encapsulate handshake parts into `query_payload` and `response_payload`
  nano/core_test/message_deserializer.cpp
  nano/core_test/network.cpp
  nano/node/messages.cpp
  nano/node/messages.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp_server.cpp
  nano/node/transport/tcp_server.hpp
Labels: exclude from changelog

#4175 Remove the message_parser class
  nano/core_test/message.cpp
  nano/node/messages.cpp
  nano/node/messages.hpp
Labels: routine, removal, exclude from changelog

#4168 Handshake V2
  nano/core_test/message.cpp
  nano/core_test/telemetry.cpp
  nano/crypto_lib/random_pool.hpp
  nano/lib/stats_enums.hpp
  nano/node/messages.cpp
  nano/node/messages.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/transport/socket.hpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp_server.cpp
  nano/node/transport/tcp_server.hpp
Labels: enhancement

#4180 Add the gap_tracker class
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/gap_tracker.cpp
  nano/node/gap_tracker.hpp
  nano/node/node.cpp
  nano/node/node.hpp
Labels: enhancement, exclude from changelog

#4179 Directly load bootstrap_peer protocol min from config
  nano/node/network.cpp
  nano/node/transport/tcp.cpp
  nano/node/transport/tcp.hpp
Labels: enhancement, exclude from changelog

#4181 Add the process_live_dipatcher class
  nano/node/CMakeLists.txt
  nano/node/blockprocessor.cpp
  nano/node/blockprocessor.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/process_live_dispatcher.cpp
  nano/node/process_live_dispatcher.hpp
Labels: enhancement, exclude from changelog

#4158 Add the ascending bootstrap client
  nano/core_test/CMakeLists.txt
  nano/core_test/block_store.cpp
  nano/core_test/bootstrap.cpp
  nano/core_test/bootstrap_ascending.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/ledger.cpp
  nano/core_test/node.cpp
  nano/core_test/unchecked_map.cpp
  nano/lib/config.hpp
  nano/lib/stats_enums.hpp
  nano/lib/threading.cpp
  nano/lib/threading.hpp
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/bootstrap/bootstrap.hpp
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/bootstrap/bootstrap_ascending.hpp
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/cli.cpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/network.cpp
  nano/node/network.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/transport/tcp.cpp
  nano/node/unchecked_map.cpp
  nano/node/unchecked_map.hpp
  nano/qt/qt.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/CMakeLists.txt
  nano/slow_test/bootstrap.cpp
  nano/slow_test/node.cpp
Labels: major

#4187 Removing tracking weight from rep_crawler class.
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_solicitor.cpp
  nano/core_test/node.cpp
  nano/node/json_handler.cpp
  nano/node/repcrawler.cpp
  nano/node/repcrawler.hpp
Labels: enhancement, exclude from changelog

#4188 Fixes and cleanup to test::setup_chains functions
  nano/test_common/chains.cpp
  nano/test_common/chains.hpp
Labels: enhancement, exclude from changelog

#4189 Fix cryptopp missing headers and its include path
  CMakeLists.txt
  nano/crypto_lib/random_pool.cpp
Labels: build-error, exclude from changelog

#4190 Add missing lib to nano_rpc build
  nano/nano_rpc/CMakeLists.txt
Labels: build-error, exclude from changelog

#4191 Removing unnecessary class scoped_io_thread_name_change.
  nano/rpc_test/rpc.cpp
Labels: enhancement, exclude from changelog

#4192 Applies a number of cleanups to rpc tests.
  nano/rpc_test/CMakeLists.txt
  nano/rpc_test/common.cpp
  nano/rpc_test/common.hpp
  nano/rpc_test/receivable.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement

#4193 Lowering the number of nodes spawned which is memory intensive.
  nano/core_test/node.cpp
Labels: ci/cd, exclude from changelog

#4196 RPC test cleanup rpc.accounts_receivable
  nano/rpc_test/receivable.cpp
  nano/rpc_test/rpc.cpp
Labels: unit test, exclude from changelog

#4200 Changes the semantics of election::confirmed and clean up several unit tests
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/election.cpp
  nano/core_test/node.cpp
  nano/core_test/vote_processor.cpp
  nano/node/active_transactions.cpp
  nano/node/election.cpp
  nano/node/election.hpp
  nano/rpc_test/rpc.cpp
Labels: unit test, exclude from changelog

#4195 Fix or suppress Windows build warnings
  nano/core_test/message_deserializer.cpp
  nano/core_test/peer_container.cpp
  nano/node/blockprocessor.cpp
  nano/node/bootstrap/bootstrap_ascending.cpp
  nano/node/node.cpp
  nano/node/transport/inproc.cpp
  nano/node/transport/socket.cpp
  nano/node/transport/socket.hpp
  nano/secure/common.cpp
Labels: routine, exclude from changelog
