Repository nanocurrency/nano-node, pull requests merged in 2023-05, with the labels that each got.

#4221 Converting legacy bootstrap shared_ptr's referencing nano::node to weak_ptr's
  nano/node/bootstrap/bootstrap_attempt.cpp
  nano/node/bootstrap/bootstrap_attempt.hpp
  nano/node/bootstrap/bootstrap_bulk_pull.cpp
  nano/node/bootstrap/bootstrap_bulk_push.cpp
  nano/node/bootstrap/bootstrap_connections.cpp
  nano/node/bootstrap/bootstrap_connections.hpp
  nano/node/bootstrap/bootstrap_frontier.cpp
  nano/node/bootstrap/bootstrap_lazy.cpp
  nano/node/bootstrap/bootstrap_legacy.cpp
  nano/node/transport/tcp_server.cpp
  nano/node/transport/tcp_server.hpp
Labels: bug

#4222 Fix data race identified by TSAN where threads terminate after local variables are destroyed.
  nano/core_test/utility.cpp
Labels: bug, exclude from changelog

#4225 Fixes intermittent test failures in several RPC tests when querying setup blocks.
  nano/rpc_test/receivable.cpp
  nano/rpc_test/rpc.cpp
Labels: bug

#4227 Updating major version to 26.
  CMakeLists.txt
Labels: routine, exclude from changelog

#4226 Using canonical way of disabling frontier scan
  nano/rpc_test/receivable.cpp
  nano/rpc_test/rpc.cpp
Labels: enhancement, exclude from changelog

#4229 Update rep weights for V25.
  rep_weights_beta.bin
  rep_weights_live.bin
Labels: routine

#4230 Fix access without lock in active_transactions::confirm_block function
  nano/node/active_transactions.cpp
Labels: bug

#4131 Add LMDB and RocksDB upgrades to v22: Remove unchecked table
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/node/CMakeLists.txt
  nano/node/lmdb/lmdb.cpp
  nano/node/lmdb/lmdb.hpp
  nano/node/lmdb/unchecked_store.hpp
  nano/node/node.cpp
  nano/node/rocksdb/rocksdb.cpp
  nano/node/rocksdb/rocksdb.hpp
  nano/secure/store.hpp
Labels: documentation, database structure

#4223 QoL improvements for `accounts_frontiers` & `accounts_representatives` RPC
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc

#4228 Quality improvements for `accounts_balances` RPC
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: documentation, rpc

#4232 Docker build timeout
  ci/build-docker-image.sh
Labels: build-error, exclude from changelog

#4233 Upgrading macos builders to macos 12.
  .github/workflows/beta_artifacts.yml
  .github/workflows/beta_artifacts_latest_release_branch.yml
  .github/workflows/live_artifacts.yml
  .github/workflows/test_network_artifacts.yml
Labels: build-error, exclude from changelog

#4235 Moving responsibility of trimming active_transaction container
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/election_scheduler.cpp
  nano/node/election_scheduler.hpp
Labels: enhancement

#4237 Create namespace 'scheduler' and class scheduler::component
  nano/core_test/active_transactions.cpp
  nano/core_test/conflicts.cpp
  nano/core_test/election.cpp
  nano/core_test/election_scheduler.cpp
  nano/core_test/ledger.cpp
  nano/core_test/network.cpp
  nano/core_test/node.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/backlog_population.cpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.hpp
  nano/node/process_live_dispatcher.cpp
  nano/node/process_live_dispatcher.hpp
  nano/node/scheduler/buckets.cpp
  nano/node/scheduler/buckets.hpp
  nano/node/scheduler/component.cpp
  nano/node/scheduler/component.hpp
  nano/node/scheduler/hinted.cpp
  nano/node/scheduler/hinted.hpp
  nano/node/scheduler/optimistic.cpp
  nano/node/scheduler/optimistic.hpp
  nano/rpc_test/rpc.cpp
  nano/slow_test/node.cpp
  nano/test_common/testutil.cpp
Labels: enhancement

#4239 Bump RHEL compatible base to Rocky Linux 8
  .github/workflows/beta_artifacts.yml
  .github/workflows/beta_artifacts_latest_release_branch.yml
  .github/workflows/live_artifacts.yml
  ci/actions/linux/ghcr_push.sh
  ci/actions/linux/install_deps.sh
  ci/build-rhel.sh
  docker/ci/Dockerfile-centos
  docker/ci/Dockerfile-rhel
  nanocurrency-beta.spec.in
  nanocurrency.spec.in
  util/build_prep/centos/prep.sh.in
  util/build_prep/macosx/prep.sh.in
  util/build_prep/rhel/prep.sh.in
  util/build_prep/ubuntu/prep.sh.in
Labels: ci/cd
