Repository nanocurrency/nano-node, pull requests merged in 2024-03, with the labels that each got.

#4459 Do not return node_id private key in RPC call
  nano/node/json_handler.cpp
  nano/rpc_test/rpc.cpp
Labels: breaking

#4466 Minor unused test code bugfix (nano::test::account_height)
  nano/test_common/testutil.cpp
Labels: unit test, exclude from changelog

#4467 fix some typos
  CL/cl2.hpp
  boost_checkout_lite.sh
  nano/core_test/confirmation_height.cpp
Labels: exclude from changelog

#4519 Reimplement and simplify confirmation_height_processor
  CMakeLists.txt
  nano/core_test/CMakeLists.txt
  nano/core_test/active_transactions.cpp
  nano/core_test/confirmation_height.cpp
  nano/core_test/confirming_set.cpp
  nano/core_test/ledger_confirm.cpp
  nano/core_test/node.cpp
  nano/core_test/request_aggregator.cpp
  nano/core_test/toml.cpp
  nano/lib/locks.cpp
  nano/lib/locks.hpp
  nano/nano_node/entry.cpp
  nano/node/CMakeLists.txt
  nano/node/active_transactions.cpp
  nano/node/active_transactions.hpp
  nano/node/confirmation_height_bounded.cpp
  nano/node/confirmation_height_bounded.hpp
  nano/node/confirmation_height_processor.cpp
  nano/node/confirmation_height_processor.hpp
  nano/node/confirmation_height_unbounded.cpp
  nano/node/confirmation_height_unbounded.hpp
  nano/node/confirming_set.cpp
  nano/node/confirming_set.hpp
  nano/node/json_handler.cpp
  nano/node/json_handler.hpp
  nano/node/node.cpp
  nano/node/node.hpp
  nano/node/nodeconfig.cpp
  nano/node/nodeconfig.hpp
  nano/node/wallet.cpp
  nano/rpc/rpc_handler.cpp
  nano/rpc_test/rpc.cpp
  nano/secure/common.hpp
  nano/secure/ledger.cpp
  nano/secure/ledger.hpp
  nano/slow_test/node.cpp
Labels: enhancement, breaking

#4425 Remove frontiers table from ledger
  nano/core_test/block_store.cpp
  nano/core_test/ledger.cpp
  nano/node/blockprocessor.cpp
  nano/node/node.cpp
  nano/secure/ledger.cpp
  nano/store/CMakeLists.txt
  nano/store/component.cpp
  nano/store/component.hpp
  nano/store/frontier.cpp
  nano/store/frontier.hpp
  nano/store/lmdb/frontier.cpp
  nano/store/lmdb/frontier.hpp
  nano/store/lmdb/lmdb.cpp
  nano/store/lmdb/lmdb.hpp
  nano/store/rocksdb/frontier.cpp
  nano/store/rocksdb/frontier.hpp
  nano/store/rocksdb/rocksdb.cpp
  nano/store/rocksdb/rocksdb.hpp
  nano/store/tables.hpp
  nano/test_common/testutil.cpp
Labels: enhancement, database

#4529 Fixing shared->unique assignment and no return in control flow.
  nano/nano_wallet/entry.cpp
  nano/rpc/rpc.cpp
Labels: build-error
